uber/baseweb

- rfcs/menulist-component.md
Forgot to include this in the Menulist PR.
> fix: add menulist rfc (oops)

- src/themes/light-theme.js
percentages are not valid values for `letter-spacing`
> fix: change letterSpacing units to em

- package.json
This PR reduces package.json noise by eliminating redundant fields
> style: delete redundant package.json fields

- .storybook/addons.js
- package.json
- yarn.lock
> docs(storybook): add a viewport

- .storybook/addons.js
- .storybook/config.js
- package.json
- yarn.lock
> docs(storybook): add a11y to as a tab to raise awareness

- rfcs/checkbox-component.md
- src/checkbox/__tests__/__snapshots__/styled-components.test.js.snap
- src/checkbox/checkbox.js
- src/checkbox/constants.js
- src/checkbox/examples-toggle.js
- src/checkbox/stories.js
- src/checkbox/styled-components.js
- src/checkbox/types.js
- src/themes/light-theme.js
> feat: create toggle version of checkbox

- rfcs/pagination-component.md
Throwing this up for discussion, some things I really need help thinking through:
* Is it safe to assume that this component will always be dealing with numeric pages?
* Is it a good idea to encapsulate all dropdown/select logic to the `Select` component? i.e. if users want to override fault dropdown behavior (menu open), they will have to pass-thru props to `Select` via `overrides`.
* Do we export the used icons here as well? This component will need at least 3 default icons.
Screenshot of design for easier reference:
> [RFC] Pagination Component

- rfcs/tag-component.md
> feat: create tag rfc

- rfcs/icon-component.md
> docs(icon): icon rfc

- rfcs/toast-component.md
> docs(toast): toast notification rfc

- src/input/__tests__/__snapshots__/base-input.test.js.snap
- src/input/__tests__/__snapshots__/input.test.js.snap
- src/input/__tests__/base-input.test.js
- src/input/base-input.js
- src/input/types.js
- src/select/__tests__/__snapshots__/select.test.js.snap
Fixes https://github.com/uber-web/baseui/issues/237
> fix(input): remove default prop for value in BaseInput

- src/form-control/form-control.js
- src/menu/__tests__/__snapshots__/styled-components.test.js.snap
- src/menu/__tests__/stateful-container.test.js
- src/menu/__tests__/utils.test.js
- src/menu/constants.js
- src/menu/menu.js
- src/menu/stateful-container.js
- src/menu/stateful-menu.js
- src/menu/styled-components.js
- src/menu/types.js
- src/menu/utils.js
Addressing the TODOs in https://github.com/uber-web/baseui/issues/185 as well as pulling in the `Menu` changes from the `Pagination` PRs since those might take some more time to land.
> fix(menu): address Menu todos; fix types; better a11y

- rfcs/file-uploader-component.md
> docs(file-uploader): file uploader rfc

- rfcs/slider-component.md
> docs(slider): add rfc for slider

- rfcs/progress-bar-component.md
> docs(progress-bar): progress bar rfc

- package.json
- rfcs/pagination-component.md
- src/menu/types.js
- src/pagination/__tests__/__snapshots__/styled-components.test.js.snap
- src/pagination/__tests__/pagination.test.js
- src/pagination/__tests__/stateful-container.test.js
- src/pagination/__tests__/stateful-pagination.test.js
- src/pagination/__tests__/styled-components.test.js
- src/pagination/__tests__/utils.test.js
- src/pagination/constants.js
- src/pagination/examples.js
- src/pagination/icons.js
- src/pagination/index.js
- src/pagination/pagination.js
- src/pagination/stateful-container.js
- src/pagination/stateful-pagination.js
- src/pagination/stories.js
- src/pagination/styled-components.js
- src/pagination/types.js
- src/pagination/utils.js
- yarn.lock
Part 1 of series of Pagination PR, each built on top of the previous. This one includes:
* Styled Components
* Types
* Icons
* Utils
> feat(pagination): initial component implementation (part 1)

- src/modal/__tests__/modal-button.test.js
- src/modal/index.js
- src/modal/modal-button.js
- src/modal/styled-components.js
Switch `ModalButton` to use new `Button` component now that it exists.
> chore(modal): use new button component

- rfcs/accordion-component.md
> docs(accordion): add rfc for accordion

- rfcs/accordion-component.md
> feat: add RFC for accordians

- rfcs/tag-component.md
- src/select/__tests__/__snapshots__/styled-components.test.js.snap
- src/select/__tests__/select.test.js
- src/select/__tests__/stateful-select.test.js
- src/select/__tests__/styled-components.test.js
- src/select/constants.js
- src/select/index.js
- src/select/select.js
- src/select/styled-components.js
- src/styles/index.js
- src/styles/util.js
- src/tag/__tests__/__snapshots__/styled-components.test.js.snap
- src/tag/__tests__/__snapshots__/tag.test.js.snap
- src/tag/__tests__/styled-components.test.js
- src/tag/__tests__/tag.test.js
- src/tag/constants.js
- src/tag/examples.js
- src/tag/index.js
- src/tag/stories.js
- src/tag/styled-components.js
- src/tag/tag.js
- src/tag/types.js
> feat: extract Tag into separate component

- src/tag/constants.js
Fixes #273 
Fixes relative import in tags/constants.js
Yes
MIT
> bugfix(tags): correct relative import that breaks in dist

- src/card/card.js
> fix(card): dont include overrides in rest props

- src/popover/__tests__/popover.test.js
- src/popover/popover.js
Fix for part 1 of #288 
Yes
Yes
> fix(tooltip): shouldnt steal onclick events from children

- rfcs/progress-steps-component.md
> docs(progress-steps): progress steps component RFC

- nightwatch.conf.js
Based on https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-BuildNumbers
> fix(e2e): add build numbers

- rfcs/progress-bar-component.md
- src/progressbar/examples.js
- src/progressbar/index.js
- src/progressbar/progressbar.js
- src/progressbar/stories.js
- src/progressbar/styled-components.js
- src/progressbar/types.js
add stateless progressbar implementation
> feat: add stateless progressbar implementation

- src/button/__tests__/button.test.js
- src/button/button.js
Minor regression from #359 reported by an engineer on chat.
> fix(button): propagate event by spreading args

- src/select/types.js
fixes https://github.com/uber-web/baseui/issues/387
> fix(select): filteroption prop flow type

- rfcs/select-component.md
- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/dropdown.js
- src/select/index.js
- src/select/select.js
- src/select/styled-components.js
- src/select/types.js
add accessibility to select component
> feat(select): add accessibility to select component

- src/select/e2e.js
- src/select/examples-list.js
- src/select/examples.js
> test(select): add e2e tests to Select

- src/pagination/__tests__/pagination.test.js
- src/pagination/__tests__/stateful-container.test.js
- src/pagination/pagination.js
- src/pagination/stateful-container.js
- src/pagination/types.js
Selecting a page from the dropdown is returning NaN, seems to be a regression from the handlers change.
> fix(pagination): fix page selection from dropdown menu

- src/pagination/examples.js
- src/pagination/pagination.js
Finally addressing https://github.com/uber-web/baseui/issues/380. This allows the overrides to work as users would expect. The longer term solution is to figure out https://github.com/uber-web/baseui/issues/375 and do proper overrides.
> fix(pagination): fix expected behavior of dropdown menu style override

- src/slider/__tests__/__snapshots__/slider.test.js.snap
- src/slider/__tests__/__snapshots__/stateful-slider-container.test.js.snap
- src/slider/__tests__/__snapshots__/styled-components.test.js.snap
- src/slider/__tests__/slider.test.js
- src/slider/__tests__/stateful-slider-container.test.js
- src/slider/__tests__/stateful-slider.test.js
- src/slider/__tests__/styled-components.test.js
- src/slider/types.js
> test(slider): add unit tests to Slider

- rfcs/block-component.md
Not trying to merge right now, just trying to gather feedback as this is still just an experimental idea. Opened as a PR to make inline comments easier.
> [RFC] Component for quick layout, spacing, and typography

- src/modal/__tests__/modal.test.js
- src/modal/modal.js
Fixes #414
Yes
No
No
Yes
No
MIT
> feat(modal): prevent background scroll when modal opens

- .storybook/config.js
> fix(storybook): with info

- src/accordion/accordion.js
- src/accordion/constants.js
- src/accordion/examples-list.js
- src/accordion/examples.js
- src/accordion/index.js
- src/accordion/panel.js
- src/accordion/stateful-panel-container.js
- src/accordion/stateful-panel.js
- src/accordion/stories.js
- src/accordion/styled-components.js
- src/accordion/types.js
- src/toast/examples.js
- src/toast/toast.js
> feat(accordion): add accordion component (part1)

- .storybook-base/webpack.config.js
- .storybook-move/webpack.config.js
- .storybook/webpack.config.js
In the Storybook examples, we depend on function names, so I'd like to disable minifiction
> fix(storybook): use custom webpack to disable minifiaction

- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/__tests__/__snapshots__/styled-components.test.js.snap
- src/select/select.js
- src/select/styled-components.js
Fixes https://github.com/uber-web/baseui/issues/493
> fix(select): various visual tweaks

- rfcs/progress-steps-component.md
- src/progress-steps/__tests__/__snapshots__/numbered-step.test.js.snap
- src/progress-steps/__tests__/__snapshots__/step.test.js.snap
- src/progress-steps/__tests__/numbered-step.test.js
- src/progress-steps/__tests__/progress-steps.test.js
- src/progress-steps/__tests__/step.test.js
- src/progress-steps/examples-list.js
- src/progress-steps/examples.js
- src/progress-steps/index.js
- src/progress-steps/numbered-step.js
- src/progress-steps/progress-steps.js
- src/progress-steps/step.js
- src/progress-steps/stories.js
- src/progress-steps/styled-components.js
- src/progress-steps/types.js
This PR introduces the new `ProgressSteps` component (including `Step` and `NumberedStep`).
It is a functional component that abstracts the common interactions of a stepper component.
🚧 [WIP] This component is missing animations 🚧 
Yes
MIT
> feat: introduce new ProgressSteps components

- src/button/__tests__/styled-components.test.js
- src/input/__tests__/__snapshots__/styled-components.test.js.snap
- src/input/__tests__/styled-components.test.js
- src/styles/__mocks__/styled.js
Followup from #508, adding tests
> test(various): tests for useRoundedCorners in button and input

- rfcs/header-navigation-component.md
add mini RFC for header navigation
> add mini RFC for header navigation

- CONTRIBUTING.md
adds a couple instructions for how to start a local dev environment
> docs: adds info for new contributors to run a dev version of the project

- src/button/e2e.js
- src/card/e2e.js
- src/checkbox/e2e.js
- src/input/e2e.js
- src/menu/e2e.js
- src/modal/e2e.js
- src/pagination/e2e.js
- src/popover/e2e.js
- src/tag/e2e.js
- src/textarea/e2e.js
- src/tooltip/e2e.js
> fix: disable all a11y tests

- package.json
- src/tag/e2e.js
- yarn.lock
fix malicious version of dependency 
flatmap-stream@0.1.1
https://github.com/dominictarr/event-stream/issues/116
https://github.com/bitpay/copay/issues/9346
https://news.ycombinator.com/item?id=18534392
> fix malicious version of dependency flatmap-stream 

- rfcs/select-component.md
- src/select/dropdown.js
- src/select/index.js
- src/select/styled-components.js
- src/select/types.js
fixes #551 - Note: it fixes the current updated version.
fixes #553
> fix(select): make dropdown positioned absolute and bump z-index

- package.json
- src/select/__tests__/__snapshots__/styled-components.test.js.snap
- src/select/styled-components.js
- src/styles/util.js
> fix: Add ellipsis to long text in Select component

- .flowconfig
- flow/WebpackAsset.js.flow
- src/accordion/stories.js
- src/avatar/stories.js
- src/block/stories.js
- src/breadcrumbs/stories.js
- src/button/stories.js
- src/card/stories.js
- src/checkbox/stories.js
- src/form-control/stories.js
- src/header-navigation/stories.js
- src/icon/stories.js
- src/input/stories.js
- src/menu/stories.js
- src/modal/stories.js
- src/notification/stories.js
- src/pagination/stories.js
- src/popover/stories.js
- src/progress-bar/stories.js
- src/progress-steps/stories.js
- src/radio/stories.js
- src/rating/stories.js
- src/select/stories.js
- src/slider/stories.js
- src/spinner/stories.js
- src/tag/stories.js
- src/template-component/stories.js
- src/textarea/stories.js
- src/toast/stories.js
- src/tooltip/stories.js
last pr got kind of messed up with all of the merge conflicts
https://github.com/uber-web/baseui/pull/589
> build: flow fix me markdown imports (again)

- src/accordion/README.md
- src/avatar/README.md
- src/button/README.md
- src/card/README.md
- src/checkbox/README.md
- src/header-navigation/README.md
- src/input/README.md
- src/menu/README.md
- src/modal/README.md
- src/pagination/README.md
- src/popover/README.md
- src/progress-bar/README.md
- src/progress-steps/README.md
- src/radio/README.md
- src/select/README.md
- src/slider/README.md
- src/tag/README.md
- src/template-component/README.md
- src/toast/README.md
follow up from the rfc review prs
> docs: calls out required props in readmes

- src/select/README.md
LoadingIndocator => LoadingIndicator
> Fix typo in README.md

- docs/pages/introduction/versioning.md
takes some cues from https://emptysqua.re/blog/api-evolution-the-right-way/
> docs(versioning): clarifies feature deprecation path

- README.md
- package.json
- src/styles/styled.js
- yarn.lock
- Removes usage/peer dependency on `styletron-react-core`. Installing this was easy to forget, since it was removed as direct dependency of `styletron-react@4.4` and thus not automatically installed.
- Resolves context/provider issues resulting from `styletron-react-core`.
- Improves Flow types and compatibility w/ newer versions of Flow.
Yes
MIT
> fix(deps): upgrade styletron-react

- src/helpers/__tests__/overrides.test.js
- src/helpers/overrides.js
Export `mergeStyleOverrides`, `StyleOverrideT`, and add tests. Can be helpful for dealing with style overrides outside of Base UI.
> feat(overrides): export `mergeStyleOverrides` and add tests

- documentation-site/components/layout.js
- documentation-site/components/sidebar.js
- documentation-site/routes.js
- netlify.toml
https://deploy-preview-704--baseui.netlify.com/beta/
> feat(docs): add sidenav

- documentation-site/components/component-menu.js
- documentation-site/components/layout.js
- documentation-site/components/nav-link.js
- documentation-site/components/sidebar.js
- documentation-site/routes.js
> feat(docs-site): component menu

- documentation-site/components/component-menu.js
- documentation-site/pages/components/accordion.mdx
- documentation-site/routes.js
- documentation-site/static/examples/accordion/basic.js
- documentation-site/static/examples/accordion/stateful.js
- src/accordion/types.js
https://deploy-preview-719--baseui.netlify.com/beta
> docs(accordion): move to the new doc site

- documentation-site/pages/components/card.mdx
- documentation-site/routes.js
- documentation-site/static/examples/card/basic.js
- documentation-site/static/examples/card/image-cta.js
- documentation-site/static/examples/card/thumbnail-cta.js
- src/card/types.js
https://5c37792c7bb4030009fc9669--baseui.netlify.com/beta/
> docs(card): move to the new doc site

- documentation-site/pages/components/textarea.mdx
- documentation-site/routes.js
- documentation-site/static/examples/textarea/basic.js
- documentation-site/static/examples/textarea/ref.js
API docs pending on https://github.com/atlassian/extract-react-types/pull/42
> docs(textarea): move to the new docs site

- proposals/dnd-list.md
**My first component proposal! So please, tear it apart!**
Since this is a first serious use-case of drag and drop (apart from the file uploader) I did some research and prototyping and put together a section about underlying implementation. 
At the beginning I really hoped that we could use some third-party library to not deal with dnd basics. However, I can't find anything that would be good for a library usage and allow the level of customization that baseui requires. So I've started to prototype my own library that implements dnd from scratch and should meet all our requirements. It doesn't seem terribly complicated and it's nice to have a full control. But...
**...is this the hill I will die on?** If there's some better option, lmk! Happy to ditch that if so.
> docs(dnd-list): add dnd-list proposal

- documentation-site/pages/components/popover.mdx
- documentation-site/routes.js
- documentation-site/static/examples/popover/clipping.js
- documentation-site/static/examples/popover/dismiss.js
- documentation-site/static/examples/popover/overrides.js
- documentation-site/static/examples/popover/placements.js
- documentation-site/static/examples/popover/stateful-click.js
- documentation-site/static/examples/popover/stateful-hover.js
- documentation-site/static/examples/popover/stateless.js
- documentation-site/static/examples/popover/with-arrow.js
- src/popover/stateful-container.js
- src/popover/stateful-popover.js
- src/popover/types.js
edits the default props so that the api component can read from it
> docs(popover): adds popover to docs site

- documentation-site/pages/components/block.mdx
- src/block/README.md
Removing reference to internal framework as it isn't relevant to public.
> docs(block): remove superfine reference

- screener.config.js
- src/button/styled-components.js
> fix(button): fix round shape button radius

- documentation-site/components/code.js
- documentation-site/components/example.js
- package.json
- yarn.lock
> feat(docs): code syntax highlighting

- documentation-site/components/overrides.js
- documentation-site/pages/_app.js
- documentation-site/pages/components/accordion.mdx
> feat(docs): overrides component upgrade

- src/typography/README.md
- src/typography/__tests__/index.js
- src/typography/examples-list.js
- src/typography/examples.js
- src/typography/index.js
- src/typography/stories.js
> feat(typography): a first implementation of typography components

- .buildkite/pipeline.yml
- now.json
- package.json
- yarn.lock
based off this earlier pr to deploy to netlify https://github.com/uber-web/baseui/pull/732
this is an example of the published site: https://baseui-documentation-be1bpgd62.now.sh/
> chore(build): deploy on zeit now on git tag

- .buildkite/pipeline.yml
- now.json
need to call this command to add the alias to the deployment with 'now'
> chore(build): auto alias the now deployment

- README.md
minor nit on punctuation, change `it's` to `its`
> docs(readme): minor nit on punctuation

- src/radio/__tests__/__snapshots__/styled-components.test.js.snap
- src/radio/styled-components.js
> fix(radio): prevent deformations of the radio input

- package.json
> Release v5.13.1

- scripts/now-deploy.sh
build failed on missing package: https://buildkite.com/uberopensource/baseui/builds/3586#ee8c25e3-a947-4590-8cc4-5335e429b071
make sure to update the package lists for `apt-get`
> fix(build): update package lists

- .storybook-base/loadStories.js
- documentation-site/routes.js
- documentation-site/static/examples/file-uploader/_overrides_component.js
- documentation-site/static/examples/file-uploader/basic.js
- documentation-site/static/examples/file-uploader/disabled.js
- documentation-site/static/examples/file-uploader/error.js
- documentation-site/static/examples/file-uploader/indeterminate-progress.js
- documentation-site/static/examples/file-uploader/overrides.js
- src/file-uploader/README.md
- src/file-uploader/__tests__/file-uploader.test.js
- src/file-uploader/examples.js
- src/file-uploader/file-uploader.js
- src/file-uploader/index.js
- src/file-uploader/stories.js
> feat(file-uploader): stabilize it

- .buildkite/pipeline.yml
> fix(build): Use builders queue for puppeteer tests

- scripts/now-deploy.sh
script has been failing on mis-matched git commits. let's figure out what it's getting
> chore: adds debug logs to now deploy script

- documentation-site/static/examples/tag/basic.js
- src/tag/__tests__/__snapshots__/tag.test.js.snap
- src/tag/__tests__/tag-long-text.scenario.js
- src/tag/examples.js
- src/tag/index.js
- src/tag/styled-components.js
- src/tag/tag.js
> fix(tag): handles text overflow

- src/slider/__tests__/slider.e2e.js
- src/slider/__tests__/slider.scenario.js
chose to only test a11y since @tajo did a bunch of tests in the `react-range` lib, but i can add some here if we want
> test(slider): e2e a11y test

- documentation-site/components/layout.js
- documentation-site/components/sidebar.js
Fixing the docs site based on https://community.algolia.com/docsearch/recommended-configuration.html#overview-of-a-clear-layout
> fix(algolia): proper attributes

- src/modal/types.js
closes: https://github.com/uber-web/baseui/issues/406
> fix(modal): removes any type in modal ref def

- src/file-uploader/file-uploader.js
This pattern caused many problems while working on the table filter component. Removing it from everywhere else it's used
> fix: removes overrides helper

- documentation-site/components/example.js
- package.json
- yarn.lock
Since the creation of the doc site, barely anyone used the copy-to-clipboard feature, so removing it.
> docs(copy-to-clipboard): remove

- package.json
Let's wait till https://github.com/uber-web/baseui/pull/937 is merged, so we can try that out
> Release v6.2.0

- package.json
- yarn.lock
> fix(deploy): rolls now version back to v13

- documentation-site/static/examples/table/cells.js
was causing a floating scroll bar. removing that from the example for now
> fix(table): removes expandable cell for now

- documentation-site/pages/components/link.mdx
- documentation-site/routes.js
- documentation-site/static/examples/link/basic.js
> docs(link): add documentation for link

- documentation-site/static/examples/table/sortable.js
removes a stray button from the example
> fix(table): cleans up the table docs

- package.json
Depends on https://github.com/uber-web/baseui/pull/1008
> Release v6.5.2

- src/tag/tag.js
- src/tag/types.js
> fix(tag): make text override-able

- src/accordion/styled-components.js
closes https://github.com/uber-web/baseui/issues/1044
> fix(accordion): remove outline flickering

- src/tabs/__tests__/__snapshots__/stateful-tabs.test.js.snap
- src/tabs/__tests__/tabs-controlled.scenario.js
- src/tabs/tabs.js
- src/tabs/types.js
use-case i overlooked when changing tabs the other day. added to screener so we don't regress in the future
> fix(tabs): ensures proper rendering with no children

- src/toast/__tests__/toast.scenario.js
- src/toast/styled-components.js
- src/toast/toast.js
closes https://github.com/uber-web/baseui/issues/1065
> fix(toast): use flex

- src/radio/radio.js
- src/radio/styled-components.js
> fix(radio): reduces margin if description provided

- documentation-site/routes.js
- src/accordion/styled-components.js
- src/icon/alert.js
- src/icon/arrow-down.js
- src/icon/arrow-left.js
- src/icon/arrow-right.js
- src/icon/arrow-up.js
- src/icon/check-indeterminate.js
- src/icon/check.js
- src/icon/chevron-left.js
- src/icon/chevron-right.js
- src/icon/delete-alt.js
- src/icon/delete.js
- src/icon/filter.js
- src/icon/grab.js
- src/icon/icon-template.txt
- src/icon/menu.js
- src/icon/overflow.js
- src/icon/plus.js
- src/icon/search.js
- src/icon/spinner.js
- src/icon/triangle-down.js
- src/icon/triangle-left.js
- src/icon/triangle-right.js
- src/icon/triangle-up.js
- src/icon/upload.js
> Revert "fix(icon): applies isolated styles to globally overridden icons"

- documentation-site/components/example.js
examples using hooks were breaking
> fix(docs-site): bump react version in sandbox

- documentation-site/pages/components/select.mdx
- documentation-site/static/examples/select/in-modal.js
- src/modal/styled-components.js
- src/pagination/styled-components.js
- src/popover/styled-components.js
- src/select/__tests__/select-in-modal.scenario.js
- src/table/styled-components.js
Remove z-index usage in the modal, pagination, popover and table components
> fix(components): remove z-index usage

- documentation-site/components/header-navigation.js
- documentation-site/components/layout.js
- documentation-site/pages/_app.js
- documentation-site/pages/blog/getting-started-with-base-web/index.mdx
- documentation-site/pages/index.js
> feat: updates to mobile layout + intro to base web tweaks

- documentation-site/pages/_document.js
> feat(docs): add delighted

- documentation-site/static/examples/button/dropdown.js
Minor change; made the example for a button with dropdown stateless
> docs: simplify example for button with dropdown

- src/themes/dark-theme-colors.js
> feat(dark-theme): notification

- documentation-site/static/examples/table/cells.js
- src/styles/types.js
- src/table/filter.js
- src/table/styled-components.js
- src/themes/creator.js
- src/themes/dark-theme-colors.js
> feat(table): dark theme colors

- src/datepicker/datepicker.js
- src/datepicker/types.js
> feat(datepicker): add onClose property to the datepickers API

- README.md
closes: https://github.com/uber-web/baseui/issues/1154
> docs(readme) fix broken themes link

- src/table/types.js
> fix(sort-head-cell): properly relax override types

- src/checkbox/styled-components.js
- src/rating/styled-components.js
Fixes style hydration for these styles resulting from: https://github.com/styletron/styletron/issues/149
> fix(styles): remove semicolons from styles

- documentation-site/pages/getting-started/roadmap.mdx
- documentation-site/routes.js
@tajo @nadiia @chasestarr can you please help me if I missed any items from either sections?
> docs(roadmap): add page

- src/styles/types.js
Add type declaration for my previous PR #1162
> fix(link): add linkActive to ColorsT type

- src/block/styled-components.js
> fix(block): does not apply undefined value in transform

- documentation-site/pages/getting-started/comparison.mdx
> Correct the name of the project

- documentation-site/static/examples/input/with-tags.js
- documentation-site/static/examples/layer/basic-tether.js
- documentation-site/static/examples/side-navigation/nav-overrides.js
- src/accordion/stateful-panel-container.js
- src/block/block.js
- src/card/card.js
- src/checkbox/__tests__/stateful-checkbox.test.js
- src/checkbox/stateful-checkbox-container.js
- src/datepicker/stateful-container.js
- src/dnd-list/stateful-list-container.js
- src/input/input.js
- src/input/stateful-container.js
- src/layer/tether.js
- src/menu/menu.js
- src/radio/stateful-radiogroup-container.js
- src/select/autosize-input.js
- src/select/multi-value.js
- src/select/stateful-select-container.js
- src/select/value.js
- src/side-navigation/stateful-container.js
- src/slider/__tests__/stateful-slider.test.js
- src/slider/stateful-slider-container.js
- src/template-component/examples.js
- src/template-component/stateful-container.js
- src/toast/toaster.js
chore: consistently name rest parameters
> chore: consistently name rest parameters

- documentation-site/pages/theming/custom-themes.mdx
- Fixes typo in `ThemeProvider` docs 👍
> fix: typo in ThemeProvider docs

- documentation-site/pages/_app.js
Fixes theme persistence regression in browsers that don't support `prefers-color-scheme` from #1210 
- [✅] Patch: Bug Fix
> fix(docs): retain theme preference across page loads

- src/popover/popover.js
> fix(popover): avoids menu flash

- .babelrc.js
- documentation-site/static/examples/modal/basic.js
- jest-puppeteer.config.js
- src/button-group/button-group.js
- src/card/card.js
- src/datepicker/day.js
- src/modal/__tests__/modal.scenario.js
- src/modal/modal.js
- src/popover/popover.js
- src/select/select.js
- src/side-navigation/nav.js
Remove redundant conditional expressions and use `!!` instead of `Boolean()` to be consistent with the majority of the codebase.
> chore: remove redundant conditional expressions and consistently use !!

- docs/migrations/01194.md
- documentation-site/pages/components/side-nav.mdx
- documentation-site/routes.js
- documentation-site/static/examples/side-navigation/nav-overrides.js
- src/side-navigation/__tests__/__snapshots__/stateful-nav.test.js.snap
- src/side-navigation/__tests__/nav.scenario.js
- src/side-navigation/__tests__/nav.test.js
- src/side-navigation/__tests__/stateful-nav.test.js
- src/side-navigation/nav.js
- src/side-navigation/types.js
rename subnav -> subNav and sidenav -> side-nav for consistency
> chore(side-navigation): rename subnav -> subNav and sidenav -> side-nav

- documentation-site/pages/components/sidenav.mdx
> docs: describe react-router integration with sidenav

- .storybook/config.js
- documentation-site/pages/_app.js
- documentation-site/pages/components/base-provider.mdx
- documentation-site/pages/components/layer.mdx
- documentation-site/pages/getting-started/usage.mdx
- documentation-site/pages/theming/custom-themes.mdx
- documentation-site/routes.js
- e2e/index.js
- src/helpers/base-provider.js
- src/index.js
Adds a single wrapper that adds Layers and Theme providers.
> feat: add BaseProvider

- src/select/select.js
closes https://github.com/uber-web/baseui/issues/1242
> fix(select): show real value in DOM

- src/locale/en_US.js
- src/locale/types.js
- src/menu/__tests__/menu-empty.scenario.js
- src/menu/__tests__/menu.test.js
- src/menu/__tests__/option-list.test.js
- src/menu/__tests__/option-profile.test.js
- src/menu/index.js
- src/menu/locale.js
- src/menu/menu.js
- src/menu/option-list.js
- src/menu/option-profile.js
- src/menu/styled-components.js
- src/menu/types.js
- src/select/dropdown.js
- src/select/locale.js
- src/select/select.js
- src/select/types.js
> feat(menu and select): add empty/no results state

- src/block/block.js
- src/block/styled-components.js
- src/block/types.js
allow gridRowGap and alphabetize to be consistent with gridColumnGap
> feat(block): allow gridRowGap

- src/layer/layers-manager.js
> fix(layer-manager): use exact element type in ref instance

- src/accordion/stateful-panel-container.js
- src/accordion/types.js
> fix(accordion): fix StatefulPanel props list in docs

- documentation-site/pages/components/input.mdx
- documentation-site/static/examples/input/basic-uncontrolled-default-value.js
Simple example for how to get behaviour of `defaultValue` in "_uncontrolled_" `Input` component.
> docs: uncontrolled input with default value

- documentation-site/components/layout.js
- documentation-site/pages/_app.js
- documentation-site/static/examples/block/responsive.js
- documentation-site/static/examples/layer/basic-tether.js
- documentation-site/static/examples/layer/basic.js
- documentation-site/static/examples/select/label.js
After #1286, we can use backgroundColor prop when possible
> chore(block): use backgroundColor prop when possible

- docs/migrations/01207.md
adds instructions to run the styled function `// $FlowFixMe` codemod
> docs(styletron-codemod): adds instructions to run

- docs/migrations/01207.md
- documentation-site/pages/blog/base-web-v7/index.mdx
- src/datepicker/__tests__/datepicker.e2e.js
- src/datepicker/calendar-header.js
- src/datepicker/types.js
- Enter key to select an item closes the menu
- Tab away from button closes the menu
- Arrow up/down opens the menu
> fix(datepicker): keyboard control ally improvements

- documentation-site/components/search.js
- documentation-site/components/theming-values/borders.js
- documentation-site/components/theming-values/lighting.js
- documentation-site/static/examples/datepicker/with-overrides.js
- documentation-site/static/examples/popover/overrides.js
- src/card/styled-components.js
- src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
- src/file-uploader/styled-components.js
- src/modal/styled-components.js
- src/popover/__tests__/__snapshots__/popover.test.js.snap
- src/popover/styled-components.js
- src/toast/styled-components.js
- src/tooltip/styled-components.js
removes border-radius from the following components:
- card
- file-uploader
- modal
- popover
- toast
- tooltip
> feat(border-radius): removes radius from components

- documentation-site/helpers/polyfills.js
- src/datepicker/timepicker.js
* adds a polyfill for the doc site
* removes usage from component code
> fix(compatiblity): ie11 starts-with

- docs/migrations/01207.md
forgot to add this information earlier
> docs(v7-migration): adds info about withStyle

- README.md
- documentation-site/pages/getting-started/learn.mdx
Fixes #1272 
Adds [this showcase example](https://codesandbox.io/s/patient-sky-nn8t7) in README and documentation
> feat(documentation): adds new showcase example in README and docs

- src/menu/stateful-container.js
- src/select/__tests__/select.e2e.js
Left/right arrow keys were being captured by the menu component. See integration test to reproduction steps.
> fix(select): left/right arrows should navigate input

- documentation-site/pages/blog/base-web-v7/index.mdx
updated the blogpost from the migration docs, so they are in sync
> fix(blog-post): add migrations

- package.json
> Release v7.0.0

- src/datepicker/__tests__/datepicker-range.scenario.js
- src/datepicker/__tests__/datepicker.e2e.js
adding this because of https://github.com/uber-web/baseui/issues/1301
> test(datepicker): add test to verify date-fns

- package.json
Version `7.1.0` of Base Web includes:
- New `PhoneInput` component! #1367
> Release v7.1.0

- documentation-site/pages/components/phone-input.mdx
- Add a missing override, `DialCode`
- Add country support table
> docs: update phone-input docs with helpful information

- documentation-site/pages/components/base-provider.mdx
> fix: typo in BaseProvider docs

- documentation-site/pages/components/datepicker.mdx
- documentation-site/static/examples/datepicker/i18n.js
this was hard to understand from the api definition. added an example for clarity
> feat(docs): adds datepicker example with localization

- src/slider/index.js
Export StyledThumbValue, which was missing in index.js
> feat(slider): export StyledThumbValue

- package.json
Release v7.4.0
- Modal a11y enhancements (#1406)
> Release v7.4.0

- src/helpers/overrides.js
- Addresses #1209 by splitting union into two exported types
> feat: expose StyleOverridesFunctionT + StyleOverridesObjectT

- src/popover/stateful-container.js
- src/popover/types.js
- Resolves #1282 by adding `onClick` support
- Does pose the question of exposing other event handler events
> feat: resolve #1282 exposing events in handlers and supporting onClick

- package.json
- src/select/__tests__/select.test.js
- src/select/types.js
- Resolves #1328 by allowing custom options in flow type declaration
> feat: resolve #1328 allowing custom keys in options

- package.json
- #1474 Fix for selects in modals
> Release v8.0.1

- package.json
- #1476 Fix codesandbox modal examples
> Release v8.0.2

- documentation-site/components/footer.js
- documentation-site/components/layout.js
- documentation-site/pages/_app.js
> feat(docs): add footer

- src/typography/index.js
Consistently export type components as arrow functions
> chore(types): consistently export type components

- documentation-site/components/layout.js
The layout was slightly off-center (-8px).
> docs: center docs

- documentation-site/static/examples/dnd-list/removable.js
- package.json
- src/dnd-list/__tests__/stateful-list-container.test.js
- src/dnd-list/list.js
- src/dnd-list/stateful-list-container.js
- src/dnd-list/types.js
- yarn.lock
> feat(dnd-list): make items removable when out of bounds, add targetRect

- documentation-site/components/meta-favicons.js
- documentation-site/components/meta-seo.js
- documentation-site/pages/_document.js
- documentation-site/pages/components/accordion.mdx
- documentation-site/pages/index.js
for now, this is just a PoC - if we agree that this is a good approach, I'll add information for all the rest of the components
> feat(seo): add keywords and description for components

- documentation-site/components/header-navigation.js
- documentation-site/components/markdown-elements.js
- documentation-site/components/sidebar.js
- documentation-site/next.config.js
- package.json
- yarn.lock
> chore: Next.js v9

- package.json
> Release v8.5.1

- Dockerfile
- documentation-site/components/markdown-elements.js
- documentation-site/env-config.js
- netlify.toml
> fix(build): use NODE_ENV for everything

- src/datepicker/__tests__/stateful-datepicker-min-max-date.scenario.js
- src/datepicker/__tests__/stateful-datepicker-quick-select.scenario.js
- src/datepicker/__tests__/stateful-datepicker.e2e.js
- src/datepicker/__tests__/stateful-datepicker.scenario.js
- src/datepicker/__tests__/stateful-range-quick-select.scenario.js
- src/datepicker/calendar-header.js
- Fixes #1470 by removing `isDisabled` conditional
- Adds `e2e` test for this
> fix: stateful datepicker browsing

- package.json
This patch contains a [few fixes](https://github.com/uber-web/baseui/compare/v8.6.0...uber-web:v8.6.1).
> Release v8.6.1

- package.json
A minor version bump including the `PinCode` component.
> Release v8.8.0

- documentation-site/examples/pin-code/event.js
Fix a little leftover comment in the event example. Trying to up my diff count!
> fix(docs): remove comment

- documentation-site/pages/components/select.mdx
- documentation-site/pages/getting-started/internationalization.mdx
- documentation-site/pages/getting-started/usage.mdx
- documentation-site/pages/theming/overriding-icons.mdx
- documentation-site/pages/theming/understanding-overrides.mdx
> fix(examples): broken example links

- documentation-site/pages/blog/base-web-v7/index.mdx
> fix(docs): add commas

- package.json
> Release v8.9.0

- package.json
> Release v8.10.0

- src/button/index.d.ts
- src/button/types.js
- yarn.lock
> fix(button-types): add type prop

- src/modal/__tests__/__snapshots__/modal.test.js.snap
- src/modal/styled-components.js
- Resolves #1616 
- Can't handle SSR due to no portal support
> feat: seo improvements for modal w/out SSR

- documentation-site/examples/modal/autofocus.js
- documentation-site/examples/modal/buried-interactive-element.js
closes https://github.com/uber-web/baseui/issues/1634
> fix(modal): markup for examples

- documentation-site/examples/breadcrumbs/pseudo.tsx
- src/breadcrumbs/index.d.ts
> fix: add breadcrumbs pseudo tsx example

- documentation-site/examples/accordion/renderpanelcontent.js
- documentation-site/examples/accordion/renderpanelcontent.tsx
- documentation-site/pages/components/accordion.mdx
- package.json
- src/accordion/__tests__/__snapshots__/accordion.test.js.snap
- src/accordion/__tests__/accordion.e2e.js
- src/accordion/__tests__/accordion.test.js
- src/accordion/accordion.js
- src/accordion/index.d.ts
- src/accordion/panel.js
- src/accordion/styled-components.js
- src/accordion/types.js
- yarn.lock
> feat: seo improvements for accordion

- src/input/__tests__/__snapshots__/base-input.test.js.snap
- src/input/__tests__/__snapshots__/input.test.js.snap
- src/input/base-input.js
- src/textarea/__tests__/__snapshots__/textarea.test.js.snap
Pass through the `required` prop to the base input element in the `Input` component.
> fix(input): pass down 'required' prop

- package.json
- src/slider/slider.js
- src/slider/styled-components.js
- yarn.lock
> feat: Slider label overlap

- src/side-navigation/__tests__/nav.e2e.js
- src/side-navigation/nav.js
- src/side-navigation/styled-components.js
> feat: seo improvements for side nav

- src/input/__tests__/input-password.scenario.js
- src/input/__tests__/input.e2e.js
A couple regression tests for #1662.
> test(input): add regression tests for password masking

- src/modal/__tests__/__snapshots__/modal.test.js.snap
- src/modal/styled-components.js
Fixes #1691 
This is a revert.
> feat(modal): seo improvements w/out SSR (#1627) REVERT

- documentation-site/components/yard/ast.ts
- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/const.ts
- documentation-site/components/yard/theme-editor.tsx
- documentation-site/components/yard/types.ts
- documentation-site/components/yard/yard.tsx
The code is still quite hacky. Will be improved later.
> feat(yard): add theme editor

- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/const.ts
- documentation-site/components/yard/knob.tsx
- documentation-site/components/yard/knobs.tsx
- documentation-site/components/yard/override.tsx
- documentation-site/components/yard/theme-editor.tsx
- documentation-site/components/yard/types.ts
- documentation-site/components/yard/yard.tsx
- documentation-site/pages/components/input.mdx
> feat(yard): add input

- src/select/types.js
> fix(select): type typo fix

- documentation-site/examples/tabs/controlled.js
- documentation-site/examples/tabs/controlled.tsx
- documentation-site/examples/tabs/overrides.js
- documentation-site/examples/tabs/overrides.tsx
- documentation-site/pages/components/tabs.mdx
- src/tabs/__tests__/tabs-controlled.scenario.js
Add example of stateful tabs with overrides.
> fix(tabs): add example with overrides

- src/flex-grid/flex-grid-item.js
> fix(flex-grid): rtl support

- src/menu/__tests__/menu-stateful.scenario.js
- src/menu/stateful-container.js
- src/menu/stateful-menu.js
- src/menu/types.js
When a partial initialState value is passed in props the rest of the initial state was set incorrectly.
> fix(menu): set the initial state correctly

- documentation-site/components/layout.js
- documentation-site/pages/index.js
* make the edit on github button direction aware
* fix the color of the new blogpost text on the main page
> fix(docs): small fixes

- documentation-site/pages/components/dnd-list.mdx
- netlify.toml
orders the stateless dnd list above the stateful
> Docs content stateless examples

- documentation-site/examples/modal/nested.js
- documentation-site/examples/modal/nested.tsx
- documentation-site/pages/components/modal.mdx
Add an example of handling/dismissing stacked modals.
> fix(modal): add an example of how to handle closing of stacked modals

- package.json
Closes https://github.com/uber-web/baseui/issues/1770
We add it for testing in the Dockerfile, so we can remove from here
> fix(bundle): remove puppeteer

- documentation-site/pages/getting-started/learn.mdx
There is a missing context on what this concept is about.
> docs: Update Learning Base Web - Overrides

- src/side-navigation/nav.js
- src/table-grid/styled-components.js
> fix(data-attr): add mising data-baseweb attributes

- documentation-site/pages/_app.js
Reverts uber-web/baseui#1844
This addition adds many warnings in dev mode. Let's hold off on merging to master so that those issues can be fixed incrementally
> fix(docs): revert: using StrictMode for docs site

- src/tag/__tests__/tag.test.js
- src/tag/constants.js
fixes: https://github.com/uber-web/baseui/issues/1910
> fix(tag): improve tag kind type

- src/button/index.d.ts
Fixes #1924
Fix typing for Button onClick
> Fix Button onClick typing

- documentation-site/pages/_app.js
With the introduction of yard, we started to track lots of different urls
> docs(ga): track clean urls

- src/popover/index.d.ts
Relates to https://github.com/uber-web/baseui/issues/1152
Adds popperOptions to popover type defintions, was somehow missed back in June.
> fix(popover): fix type definition

- deploy.sh
forgot to add this yesterday, so now all branches are deploying to prod 🤦‍♂
> docs(deploy): only from master

- src/popover/types.js
> docs(tooltip): fix multiline comment in types

- src/accordion/accordion.js
fixes a regression introduced here: https://github.com/uber-web/baseui/commit/74b5170f762e068cb71142bca3609ecfc759b5a2#diff-2dce9f94e01818aa021674f79ec803b7R94
> fix(accordion): keep child overrides

- documentation-site/components/yard/config/table.ts
- documentation-site/pages/components/table.mdx
> docs(yard): add table

- package.json
- yarn.lock
we updated the peer dep, but did not include internal dependency
> bug(styletron): updates dependency to 5.2.2

- packages/baseui-codemods/package.json
- packages/baseui-codemods/yarn.lock
Also regenerate yarn.lock so it doesn't point to `unpm`.
> chore: update dubstep/core

- documentation-site/components/const.js
- documentation-site/components/example.js
- documentation-site/components/yard/yard.tsx
At any point you can bring your yard code into the CodeSandbox.
> docs(yard): add codesandbox

- vrt/ci.js
The base for the PR was incorrect - noticed on #2103. Fixed that and some comments that had incorrect links. Also made naming a bit more consistent.
Note, adding labels and reviewers won't work on forks by default due to permissions.
> fix(vrt): pull requests from forks

- documentation-site/components/yard/README.md
- documentation-site/components/yard/overrides.tsx
**This is not the final README or documentation**. It also doesn't go into a great detail since that will be in flux. However, it should give you the idea about overall architecture and APIs.
[**RENDERED**](https://github.com/uber/baseweb/blob/0c121e7b3e7d15fb50635be3eb4b45ebd62a0649/documentation-site/components/yard/README.md)
> docs(yard): react view proposal

- vrt/ci.js
Includes:
- Fixes pulling the original repository owner & name.
- Fixes pulling pull requests from forks. (See L294)
- Some renaming to be consistent.
> fix(vrt): original repository information

- documentation-site/components/yard/knobs.tsx
- documentation-site/components/yard/override.tsx
- documentation-site/components/yard/theme-editor.tsx
- documentation-site/components/yard/yard.tsx
Fixes https://twitter.com/andreujuanc/status/1185471571248459776
> docs(yard): fix mobile view

- src/modal/__tests__/__snapshots__/modal.test.js.snap
- src/modal/modal.js
- src/modal/styled-components.js
Revert #2206 due to a regression described in #2224
> fix(modal): revert PR #2206

- package.json
Preparing a release for https://github.com/uber/baseweb/pull/2225
> Release v9.14.0

- documentation-site/pages/components/input.mdx
closes https://github.com/uber/baseweb/issues/2258
> docs(input): password example to use input component

- documentation-site/pages/index.js
> fix typo on docs homepage

- src/flex-grid/flex-grid-item.js
- src/helpers/__tests__/responsive-helpers.test.js
- src/helpers/responsive-helpers.js
- src/themes/creator.js
Simplify getMediaQuery to the min-width case used by getMediaQueries and throughout the app.
> chore(media-query): simplify getMediaQuery to min-width case

- package.json
- yarn.lock
Fixes two bugs: 
- booleans with `defaultValue` were uncheckable
- reset didn't clear out theme values
> docs(yard): react-view 1.0.4

- documentation-site/pages/components/datepicker.mdx
closes https://github.com/uber/baseweb/issues/2400
> docs(datepicker): more information on localization

- package.json
> Release v9.25.0

- documentation-site/pages/components/layer.mdx
This solution came from discussion with maintainers.
> docs(layer): update to include detail on using BaseProvider overrides

- documentation-site/pages/discover-more/roadmap.mdx
It's been 3 months since updated.
> docs(roadmap): update

- src/input/masked-input.js
Fixes https://github.com/uber/baseweb/issues/2436
> fix(masked-input): do not pass the prop positive

- src/select/utils/default-filter-options.js
Clean up default filter, simplifying start and case insensitive logic using regex and speeding up exclusion checks using Set(). Also avoid declaring variables with `let` and use `const` instead.
> chore(select): clean up default filter

- package.json
> Release v9.29.0

- package.json
- src/checkbox/checkbox.js
- yarn.lock
The fix itself is in [react-movable](https://github.com/tajo/react-movable/pull/32).
Added the `role="checkbox"` to our checkbox so it is recognized as an interactive elements.
> fix(dnd-list): handle interactive elements better, role checkbox

- src/radio/styled-components.js
Add transition to RadioMarkOuter for background-color changes
> feat(radio): add transition to RadioMarkOuter

- src/select/utils/default-filter-options.js
Use String.prototype.trim() instead of declaring a new function.
> chore(utils): use String.prototype.trim() instead

- src/data-table/filter-menu.js
closes: https://github.com/uber/baseweb/issues/2487
flow failed to identify this as an issue!
> fix(data-table): properly map row data to filter

- documentation-site/pages/components/aspect-ratio-box.mdx
- documentation-site/pages/components/block.mdx
- documentation-site/pages/components/checkbox.mdx
- documentation-site/pages/components/datepicker.mdx
- documentation-site/pages/components/flex-grid.mdx
- documentation-site/pages/components/heading.mdx
- documentation-site/pages/components/layer.mdx
- documentation-site/pages/components/layout-grid.mdx
- documentation-site/pages/components/link.mdx
- documentation-site/pages/components/pagination.mdx
- documentation-site/pages/components/payment-card.mdx
- documentation-site/pages/components/progress-bar.mdx
- documentation-site/pages/components/radio.mdx
- documentation-site/pages/components/rating.mdx
- documentation-site/pages/components/select.mdx
- documentation-site/pages/components/styled.mdx
- documentation-site/pages/components/table-grid.mdx
- documentation-site/pages/components/table-semantic.mdx
- documentation-site/pages/components/table.mdx
- documentation-site/pages/components/tabs.mdx
- documentation-site/pages/components/tokens.mdx
- documentation-site/pages/components/unstable-a11y.mdx
- documentation-site/pages/components/unstable-data-table.mdx
- documentation-site/pages/components/use-styletron.mdx
- documentation-site/routes.js
While doing some QA on site I noticed a few inconsistencies with the exports section. Made a follow up PR to smooth those out.
> docs: make exports section consistent

- documentation-site/components/sidebar.js
This reverts commit 097f203e12da034dad1d7742209dec86ab9d0a52.
This PR had some unintended side-effect (removal of client-side routing), or https://github.com/uber/baseweb/issues/2525
cc @leyanlo
> Revert "docs(sidebar): fix sidebar links (#2489)"

- src/accordion/accordion.js
- src/checkbox/checkbox.js
- src/phone-input/utils.js
- src/spinner/spinner.js
adds some missing checks for `__DEV__` before `console.warn`
> fix: backfill some missing checks for dev

- src/checkbox/checkbox.js
So we can close https://github.com/uber/baseweb/pull/2172/files till v10
> chore(checkbox): add comment for v10 change

- src/checkbox/styled-components.js
> fix(checkbox): fix undefined style value when disabled/not checked

- src/select/select-component.js
Closes https://github.com/uber/baseweb/issues/2586
> fix(select): add warning for value prop miss-use

- src/layer/types.js
- src/popover/types.js
popper js updated its docs to v2
> fix(popover): update link to popper.js docs

- package.json
Bump to publish `eslint-plugin-baseui`.
> Release v9.41.0

- packages/eslint-plugin-baseui/README.md
- packages/eslint-plugin-baseui/package.json
- Update package.json so that the sub directory for this project is exposed on npm.
- Update README.md versioning snippet so that people are more likely to use v9.41.0 and up.
> docs(eslint-plugin-baseui): small tweaks

- src/aspect-ratio-box/__tests__/__snapshots__/aspect-ratio-box.test.js.snap
- src/aspect-ratio-box/aspect-ratio-box.js
- src/aspect-ratio-box/types.js
- src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
- src/flex-grid/__tests__/__snapshots__/flex-grid.test.js.snap
- src/flex-grid/flex-grid-item.js
- src/flex-grid/flex-grid.js
Forward refs for FlexGrid, FlexGridItem, and AspectRatioBox.
> chore(refs): forward refs for FlexGrid, FlexGridItem, and AspectRatioBox

- src/datepicker/day.js
- src/datepicker/styled-components.js
Bug repro: https://codesandbox.io/s/datepicker-3tfqp
> fix(datepicker): pass sharedProps and custom dayProps to empty days rendered

- packages/baseweb-vscode-extension/package.json
Missed this part in the original setup: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#create-a-publisher
> fix(vscode): add publisher

- documentation-site/pages/guides/theming.mdx
Fixes invalid object syntax in the theming docs
> docs(theming): fix object syntax

- documentation-site/components/yard/config/select.ts
Related to https://github.com/uber/baseweb/issues/2739
> docs(select): clarify filteroutselected prop

- packages/eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js
- packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Closes https://github.com/uber/baseweb/issues/2754
> fix(eslint-plugin): missing $theme

- src/toast/__tests__/toast.test.js
- src/toast/toast.js
> fix(notification): do not clear animateInTimer on focus

- src/data-table/index.d.ts
- src/phone-input/index.d.ts
Fix1:  typescript issues for phone input as it's missing error positive etc
Fix2: Data Table expose new features for typescript users
as above
> fix(typescript) types for phone input and data-table

- documentation-site/components/theming/animations.js
- documentation-site/components/theming/borders.js
- documentation-site/components/theming/breakpoints.js
- documentation-site/components/theming/colors.js
- documentation-site/components/theming/common.js
- documentation-site/components/theming/grid.js
- documentation-site/components/theming/lighting.js
- documentation-site/components/theming/sizing.js
- documentation-site/components/theming/typography.js
- documentation-site/pages/guides/theming.mdx
A re-styling of the theme properties section.
- Include light & dark theme comparisons where appropriate.
- Show path to theme property.
- Some drying up and refactoring.
> docs(theming): always show dark theme & restyling

- package.json
- yarn.lock
Will fix the modal not re-opening the second time.
> chore: bump react-view

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
> fix(eslint-plugin): update error message

- documentation-site/components/yard/config/tooltip.ts
closes https://github.com/uber/baseweb/issues/2831
> docs(tooltip): fix yard config

- documentation-site/examples/menu/href.js
- documentation-site/examples/menu/href.tsx
- scripts/link-checker.js
the example.com is already excluded from the link checker
> docs(menu): example to use example.com

- src/timepicker/timepicker.js
Closes https://github.com/uber/baseweb/issues/2870
> fix(timepicker): handle midnight properly

- packages/baseweb-vscode-extension/README.md
> docs: update VS code extension's README

- src/theme.ts
Interface is missign some properties
> fix(typescript): add missing theme properties

- package.json
Depends on https://github.com/uber/baseweb/pull/2939
> Release v9.59.0

- documentation-site/pages/getting-started/setup.mdx
- documentation-site/pages/index.js
Related to https://github.com/uber/baseweb/issues/2955
> docs(figma): add to the doc pages

- src/data-table/__tests__/data-table-columns.e2e.js
- src/data-table/__tests__/data-table-unreliable.e2e.js
- src/datepicker/__tests__/datepicker-range.e2e.js
- src/datepicker/__tests__/datepicker-unreliable.e2e.js
> fix(test): retry flakey e2e tests

- documentation-site/components/yard/type-definition.js
> docs: fix type tooltips

- vrt/ci.js
Update logic for determining the snapshot branch name.
> build(vrt): fix logic for generating snapshot branches from forks

- scripts/deploy-docs.sh
In the previous change, I didn't account for the fact that current working directory was not changed
> fix(deploy): netlify deploy, take 2

- now.json
this PR adds a test alias too, so we can try the change out before making it to the production website
> docs(deploy): move to zeit

- src/rating/__tests__/rating-emoticon.scenario.js
I thought this was a bug with the rating component, but turned out to be inconsistency with out scenarios
> fix(rating): update scenario to controlled value

- e2e/storybook/config.js
This was still happening, but preserving the engine instance solves this
> fix(storybook):  HMR styling issues

- documentation-site/pages/discover-more/versioning-policy.mdx
> docs(versioning-policy): add info on versioning together

- packages/baseweb-vscode-extension/ext-src/coloring.ts
> feat(vscode): show more theme prop values in tooltip hints

- src/select/select-component.js
- src/select/types.js
fixes the issues Nadiia brought up in  #3075
> fix(select): backspaceRemoves fixes

- .buildkite/pipeline.yml
in our builds `BUILDKITE_TAG=""` (we never push a tag up, it's created by probots), so the `build.tag` conditional was empty - this PR changes it to use the message instead
> fix(build): use message instead of tag

- documentation-site/components/version-selector.js
Depends on https://github.com/uber/baseweb/pull/3086
> docs(version-selector): update disabled versions

- documentation-site/examples/accordion/stateful.js
- documentation-site/examples/accordion/stateful.tsx
Fixes #2658 
I have added `<ul></ul>` to the examples as per the description of @gergelyke.
@gergelyke , Please review.
> docs(accordion):  add ul wrapper for standalone panel

- src/menu/__tests__/menu.e2e.js
- src/menu/constants.js
- src/menu/menu.js
- src/menu/stateful-container.js
- src/menu/types.js
Fixes https://github.com/uber/baseweb/issues/3049
> fix(menu): unhighlights item on mouse leave

- package.json
> Release v9.65.3

- src/list/index.d.ts
closes https://github.com/uber/baseweb/issues/3133
Make ListItem overrides typings optional.
> fix(list): Make list item overrides typings optional

- src/file-uploader/file-uploader.js
- src/select/select-component.js
- src/spinner/spinner.js
- src/spinner/types.js
fixes: https://github.com/uber/baseweb/issues/2836
> fix(spinner): only warn on usage outside of baseui

- src/locale/index.js
> fix(locale-provider): check if locale.datepicker exists

- .eslintignore
- .gitignore
- packages/eslint-plugin-baseui/README.md
- packages/eslint-plugin-baseui/__tests__/config.test.js
- packages/eslint-plugin-baseui/__tests__/example-config/.eslintrc.js
- packages/eslint-plugin-baseui/__tests__/example-config/fixture.js
- packages/eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui/index.js
- packages/eslint-plugin-baseui/__tests__/example-config/node_modules/eslint-plugin-baseui/package.json
- packages/eslint-plugin-baseui/src/index.js
Adds recommended configuration for eslint-plugin-baseui
> feat(eslint): add recommended config

- src/index.js
Export `createDarkTheme` and `createLightTheme` from root index. Fixes #3198.
> fix(theme): export createDarkTheme and createLightTheme

- documentation-site/pages/index.js
Fixes a misspelling of components.
> docs(): fix typo on front page

- src/datepicker/__tests__/datepicker-keyboard-nav.e2e.js
- src/popover/__tests__/__snapshots__/stateful-container.test.js.snap
- src/popover/__tests__/stateful-container.test.js
- src/popover/popover.js
- src/popover/stateful-container.js
- src/popover/types.js
> feat(popover): accept event handlers on stateful similar to stateless

- src/button-group/index.d.ts
Closes https://github.com/uber/baseweb/issues/3290
> fix(button-group): remove duplicate definition

- .github/PULL_REQUEST_TEMPLATE.md
Makes the template not use lists with checkboxes as github thinks those are tasks as it adds description like "1 of 3 Tasks completed" in the linked issues, PRs, etc
> chore(.github): PR template

- src/toast/__tests__/toast.test.js
- src/toast/toast.js
> fix(toast): don't reset animateOutCompleteTimer when toast dismissed

- scripts/github-release.js
In my pr the other week, I didn't realize commit messages will include all of the squashed commit messages. This change will only get the first line. [example](https://codesandbox.io/s/jolly-zhukovsky-bpd82?file=/src/index.js)
Patch: Bug Fix
> fix(release): cleans up the release notes

- src/menu/__tests__/stateful-container.test.js
- src/menu/stateful-container.js
> fix(menu): use disabled value that comes from getRequiredItemProps

- package.json
- yarn.lock
> chore(deps): update react-range

- package.json
> Release v9.76.0

- documentation-site/components/yard/config/list-item.ts
On codesandbox the List example was giving an error and the end enhacer was unstyled.
Patch: Bug Fix
> docs(list): fix List example

- documentation-site/pages/getting-started/learn.mdx
> docs: fix grammatical error in Learning Base Web

- src/datepicker/index.js
Add DatePicker export for #3368
Fixed #3368
Updated the exports to include DatePicker for consistency with TimePicker
Bug Fix
> fix(datepicker): consistent export names

- src/app-nav-bar/app-nav-bar.js
- src/app-nav-bar/mobile-menu/mobile-nav-menu.js
- src/app-nav-bar/user-menu/user-menu.js
- src/app-nav-bar/user-menu/user-profile-tile.js
Fixes #3348 
It errored out when no username was provided.
Patch: Bug Fix
> fix(app-nav-bar): pass a str to Avatar, no drawer menu if no menu items

- src/accordion/accordion.js
Fixed a typo in a warning message.
> fix(accordion): fixed a typo in the deprecation warning

- src/combobox/__tests__/combobox.test.js
- src/combobox/combobox.js
Before this change, value state updates originating from outside of the component were not handled.
Patch: Bug Fix
> fix(combobox): handles clear value

- documentation-site/examples/select/async-options.js
- documentation-site/examples/select/async-options.tsx
- documentation-site/pages/components/select.mdx
> docs(select): add select example with async options

- src/button/styled-components.js
Set spinner's dimensions taking into the account its border width.
Patch: Bug Fix
> fix(button): fix spinner's size to include border

- documentation-site/components/header-navigation.js
- documentation-site/components/search.js
Clean up some confusing CSS in the header and make it more responsive.
Here are a couple gifs to compare the changes:
<details>
<summary>Old header</summary>
</details>
<details>
<summary>New header</summary>
> docs: refactor nav and search

- documentation-site/next.config.js
[More details](https://github.com/styletron/styletron/issues/366#issuecomment-654540311)
> docs: fix Styletron debug mode errors

- documentation-site/examples/table-grid/basic.js
- documentation-site/examples/table-grid/basic.tsx
- documentation-site/examples/table-grid/nested.js
- documentation-site/examples/table-grid/nested.tsx
- documentation-site/examples/table-grid/sortable.js
- documentation-site/examples/table-grid/sortable.tsx
> fix(table grid):modifies example to better navigate

- documentation-site/components/yard/config/popover.ts
Fixes `onMouseLeaveDelay` description.
Patch: Bug Fix
> docs(Popover): fix `onMouseLeaveDelay` description

- src/tabs-motion/__tests__/tabs-motion.scenario.js
- src/tabs-motion/tabs.js
closes https://github.com/uber/baseweb/issues/3519
> fix(tabs-motion): buttons should not trigger form submit

- documentation-site/components/yard/config/file-uploader.ts
- src/file-uploader/file-uploader.js
- src/file-uploader/index.d.ts
- src/file-uploader/types.js
Original work: https://github.com/uber/baseweb/pull/3537, thanks @kizmo04!
We've discussed internally, and moved the spinner to spinnerNext, so opened a follow up
> feat(file-uploader): make spinner overridable

- documentation-site/components/yard/config/datepicker.ts
- src/datepicker/index.d.ts
> fix(datepicker): add missing ts override

- documentation-site/pages/guides/theming.mdx
Closes https://github.com/uber/baseweb/issues/3433
> docs(icons): ask users not to pass in the props to the DOM

- src/locale.ts
Fixes #3572
Updated locale TypeScript types to match the Flow types. The TypeScript types seemed to have fallen behind the Flow types.
Patch: Bug Fix
> fix: updated locale typescript types to match the flow types

- scripts/publish-to-npm.js
so I made a diff for this yesterday.. but for some reason this line change was not included in master 🤔
> fix(publish): corrects eslint publish

- DEPLOYMENTS.md
@tajo to address our discussion from yesterday - anything else where I should add more details?
> docs(deployments): add info on how the doc site is deployed

- scripts/publish-to-npm.js
> fix(alpha-publish): eslint-plugin has no dist

- documentation-site/components/yard/config/input.ts
Adds documentation for step attribute
Adds documentation for step attribute recently added to the input component. Follow up to https://github.com/uber/baseweb/pull/3630
Patch: Bug Fix
> docs(input): add documentation on step attribute for input

- package.json
So many new things that I'd like to start using :)
> Release v9.99.0

- src/modal/modal-button.js
> chore(button): forward ref to ModalButton

- src/radio/styled-components.js
Removes an unused code path. cc @leyanlo
> fix(radio): cleanup unused path

- src/link/index.d.ts
> fix(link): styletron component typescript

- package.json
> Release v9.100.0

- package.json
> Release v9.101.0

- src/link/styled-components.js
fixes: https://github.com/uber/baseweb/issues/3784
Patch: Bug Fix
> fix(StyledLink): remove unused css rule

- documentation-site/components/yard/config/input.ts
> fix(docs): correct input type config

- src/input/index.d.ts
Fixes #3790 
Added type declaration for `maxLength` prop for Input component
Patch: Bug Fix
> fix(input): add maxLength prop type in .d.ts file for Input component

- documentation-site/components/footer.js
- documentation-site/components/header-navigation.js
- documentation-site/pages/getting-started/learn.mdx
Fixes: https://github.com/uber/baseweb/issues/3808
Thank you for reporting @colinnielsen
> fix(docs): updates the slack invite link

- src/header-navigation/styled-components.js
> fix(header-navigation): update style to longhand

- src/radio/styled-components.js
> fix(radio): expand shorthand css properties

- documentation-site/pages/components/snackbar.mdx
- src/snackbar/index.d.ts
- src/snackbar/snackbar-context.js
- src/snackbar/types.js
Fixes #3838 
- I changed the default duration of snackbar from short to meduim
- I updated the documentation to reflect the changes made
Patch: Bug Fix
> fix: change duration of snackbar from short to medium

- src/slider/slider.js
> fix(dnd-list): add thumbIndex to ThumbValue

- package.json
> Release v9.104.0

- src/datepicker/__tests__/datepicker.test.js
> fix(tests): handle date test failure

- documentation-site/examples/dnd-list/overrides_style.js
- documentation-site/examples/dnd-list/overrides_style.tsx
- documentation-site/pages/guides/understanding-overrides.mdx
> fix(docs): data testid

- src/theme.ts
> fix(type): Bug with theme sizing type

- src/spinner/spinner-determinate.js
This PR intends to fix the issue happening with [Spinner Determinate](http://localhost:3000/components/spinner#spinner-determinate) (v9.104.0) when resetting to zero value
Patch: Bug Fix
> fix(spinner-determinate) fix resetting to zero value

- src/menu/styled-components.js
Fixes #3925 
Fixed the spacing issues in Menu with Profile Menu in RTL mode.
Patch: Bug Fix
> fix(menu): fix spacing of menu with profile menu

- src/table-semantic/styled-components.js
Fixes #3928 
Fixed table header text alignment and border issue in rtl mode. 
Patch: Bug Fix
> fix(table): fix header and border alignment in rtl

- src/table/index.d.ts
- src/table/sortable-head-cell.js
- src/table/types.js
> feat(table): head cell accepts non string title

- documentation-site/components/yard/nested-tooltip.tsx
Super minor copy update for the nested tooltip
> chore(nested-tooltip): minor copy update

- documentation-site/components/header-navigation.js
- documentation-site/components/table-of-contents.js
- documentation-site/components/yard/index.tsx
- documentation-site/components/yard/styled-components.tsx
- documentation-site/components/yard/types.ts
- documentation-site/pages/blog/nested-overrides-playground/index.mdx
- documentation-site/pages/blog/nested-overrides-playground/live-editor-tag.js
- documentation-site/pages/blog/nested-overrides-playground/live-editor.js
- documentation-site/pages/blog/nested-overrides-playground/metadata.json
[RENDERED blogpost](https://baseweb-git-nested-blog.uber-ui-platform.vercel.app/blog/nested-overrides-playground).
> docs(blog): Nested Overrides Playground

- documentation-site/components/yard/config/tag.ts
- documentation-site/components/yard/custom-props.ts
- documentation-site/pages/blog/nested-overrides-playground/live-editor-tag.js
- documentation-site/pages/blog/nested-overrides-playground/live-editor.js
> fix(yard): nested override ignore nulls

- documentation-site/examples/table-semantic/alternating.tsx
> fix(ts): handle ts error in example

- documentation-site/components/theming/borders.js
- documentation-site/components/theming/grid.js
- documentation-site/components/theming/typography.js
> docs: show border values as objects

- package.json
> Release v9.107.0

- documentation-site/components/yard/config/select.ts
- src/select/default-props.js
- src/select/select-component.js
- src/select/types.js
fixes #4097 
Adds a case-sensitive comparison prop to Select. This allows adding multiple creatable values that only differ in case.
> feat(select): adds ignoreCase

- documentation-site/components/yard/config/select.ts
- src/select/types.js
Fixes #4097
Update based on clarification with @ksnyder9801 
Patch: Doc Fix
> docs(select): update description for ignoreCase

- src/button-group/styled-components.js
Fix typo in button-group styled component
Patch: Bug Fix
> fix(button-group): fix length typo in styled component

- .buildkite/pipeline.yml
- scripts/publish-to-npm.js
also disabling vscode publish until we can refresh our azure credentials
> chore(publish): change deploy stdio to debug npm publish failure

- package.json
> Release v9.111.1

- src/input/base-input.js
> fix(input): correct typeof usage

- src/input/styled-components.js
fixes: https://github.com/uber/baseweb/issues/4127
> fix(input): avoid webkit input text fade

- src/slider/slider.js
> feat(slider): provide index as markIndex prop to Mark component (#4151)

- documentation-site/pages/guides/styling.mdx
Added a missing `
Patch: Bug Fix
> fix(docs): Add a missing ` in styling.mdx

- src/app-nav-bar/index.d.ts
- src/tooltip/__tests__/tooltip-interactive-element.scenario.js
Fixes #4204
Changes ts type of mixed to any. 
Patch: Bug Fix
> fix(app-nav-bar): fix ts type mixed -> any

- package.json
- yarn.lock
> fix(dnd-list): update react-movabe to fix mobile scrolling

- package.json
> Release v9.114.0

- src/select/dropdown.js
Remove unnecessary listbox role since the child already has the listbox role.
> chore(select): remove unnecessary listbox role

- src/accordion/__tests__/panel.test.js
- src/accordion/panel.js
> fix: panel should not render content when not expanded

- package.json
> Release v9.115.1

- src/radio/__tests__/radio.test.js
- src/radio/radio.js
> fix(radio): fix event from label and input

- src/data-table/data-table.js
Fixes a bug in Data Table component where row's actions remain visible after the row is deleted. 
Patch: Bug Fix
> fix(data-table): ensure row is defined before showing its actions

- documentation-site/components/yard/config/avatar.ts
- documentation-site/examples/aspect-ratio-box/image.js
- documentation-site/examples/aspect-ratio-box/image.tsx
- documentation-site/examples/avatar/override.js
- documentation-site/examples/avatar/override.tsx
- documentation-site/examples/avatar/sizes.js
- documentation-site/examples/avatar/sizes.tsx
- adorable.io stopped serving free avatars due to the cost
- repalced by https://avatars.dicebear.com/ (MIT licensed), different style but similar API
> fix: replace adorable avatars with dicebear

- src/menu/__tests__/menu-child.scenario.js
- src/menu/__tests__/menu.e2e.js
- src/menu/maybe-child-menu.js
- src/menu/option-list.js
- src/menu/types.js
Fix Menu component so that items with child menus will trigger click handler
Patch: Bug Fix
> fix(menu): item with child menu triggers click handler

- .buildkite/pipeline.yml
- deploy-versioned-docs.sh
Temporarily adjusted the pipeline to test out the now command working as intended in this update. 
https://buildkite.com/uberopensource/baseweb/builds/18750#38d9e9ea-cd82-4a3e-9e5b-bd09691f4391
> chore(deploy): update deploy docs script to install now globally

- src/snackbar/__tests__/snackbar-element.test.js
> chore(snackbar): remove mock from test

- src/menu/__tests__/stateful-container.test.js
- src/menu/stateful-container.js
Fixes #4331 
Only calls toUpperCase is the function exists. 
Patch: Bug Fix
> fix(menu): prevent error when label is component

- src/progress-steps/types.js
> docs(progress-steps): clarify some props are overriden by ProgressSteps

- src/tabs-motion/index.d.ts
Fixes #4104 
Fixes #3989 
Patch: Bug Fix
> fix(tabs-motion): update ts

- src/index.d.ts
> chore(ts): add withWrapper def

- CONTRIBUTING.md
- documentation-site/pages/components/unstable-a11y.mdx
> docs(a11y): update axe-core version in docs

- documentation-site/examples/table/vertical-scroll.js
- documentation-site/examples/table/vertical-scroll.tsx
Fixes #4376 
Update example in vertical scroll to have lesser height to demonstrate vertical scrolling
Patch: Bug Fix
> docs(table): update example for vertical scroll

- package.json
> Release v9.116.3

- CONTRIBUTING.md
> docs(contributing): Update to include more testing information

- src/toast/toaster.js
> fix(toast): set toasterRef in componentDidMount

- src/app-nav-bar/index.d.ts
app-nav-bar component misses overrides props type definition under typescript.
Patch: Bug Fix
> fix(app-nav-bar): add the missing ts type

- src/phone-input/__tests__/phone-input-next-dropdown.e2e.js
- src/phone-input/__tests__/phone-input.e2e.js
- src/phone-input/base-country-picker.js
fixes: https://github.com/uber/baseweb/issues/3846
Patch: Bug Fix
> fix(phone-input): does not autofill country value

- documentation-site/components/yard/config/tabs-motion.ts
- documentation-site/pages/components/tabs-motion.mdx
Add documentation for the uid prop.
> docs(tabs): update docs to add uid

- documentation-site/components/yard/config/button-group.ts
- documentation-site/components/yard/config/button.ts
> docs(button-group): clarify click handler in docs

- src/phone-input/base-country-picker.js
Fixes issue described in https://github.com/uber/baseweb/pull/4438#issuecomment-903340033
> fix(country-picker): change autocomplete to autoComplete

- documentation-site/components/yard/config/tag.ts
- src/datepicker/__tests__/datepicker-unreliable.e2e.js
Adds missing override from the startenhancer to the documentation site.
> docs(tag): add missing override

- src/layout-grid/grid.js
- src/layout-grid/index.d.ts
- src/layout-grid/types.js
> fix(layout-grid): make the root component overridable

- package.json
> Release 10.2.0

- documentation-site/examples/select/async-options.js
- documentation-site/examples/select/async-options.tsx
> docs(select): update example for async options

- src/drawer/close-icon.js
- src/drawer/drawer.js
> fix(drawer): add title to close icon

- src/drawer/__tests__/drawer.e2e.js
- src/drawer/drawer.js
> fix(drawer): remove focus guards due to tabIndex a11y issue

- documentation-site/components/header-navigation.js
> docs(site): add blog to header navigation

- documentation-site/components/yard/config/accordion.ts
> docs(accordion): add accordion option to yard

- documentation-site/components/yard/config/fixed-marker.ts
- documentation-site/components/yard/config/floating-marker.ts
- documentation-site/pages/components/fixed-marker.mdx
- documentation-site/pages/components/floating-marker.mdx
Add Yard for the documentation of Fixed Marker and Floating Marker
Patch
> chore(map-marker): add yard

- README.md
- package.json
- src/datepicker/__tests__/datepicker.test.js
- yarn.lock
Fixes current master branch failing due to date picker expectation of it being November.
> fix(datepicker): set static date for tests

- src/dnd-list/list.js
- src/dnd-list/styled-components.js
fixes https://github.com/uber/baseweb/issues/4676
> fix(dnd-list): move color property to styled-component

- documentation-site/components/yard/config/fixed-marker.ts
- documentation-site/examples/fixed-marker/badge-and-label-enhancers.js
- documentation-site/examples/fixed-marker/badge-and-label-enhancers.tsx
- documentation-site/examples/fixed-marker/badge-enhancer-text.js
- documentation-site/examples/fixed-marker/badge-enhancer-text.tsx
- documentation-site/pages/components/fixed-marker.mdx
- src/map-marker/__tests__/eats-pickup-marker.scenario.js
- src/map-marker/__tests__/fixed-marker-map.scenario.js
- src/map-marker/__tests__/fixed-marker.scenario.js
- src/map-marker/__tests__/floating-marker-map.scenario.js
- src/map-marker/__tests__/floating-marker.scenario.js
- src/map-marker/constants.js
- src/map-marker/fixed-marker.js
- src/map-marker/floating-marker.js
- src/map-marker/index.d.ts
- src/map-marker/styled-components.js
- src/map-marker/types.js
* Fixes remaining flow errors
* Updates the TypeScript definitions to match the Flow definitions
* Fix alignment of `xxSmall*` markers
* Split `medium` badge enhancer size into `mediumText`  and `mediumIcon`
* Improve eats markers example in the storybook (add badge and label, hovered and selected states)
Patch: Bug Fix
> Map marker label enhancer

- documentation-site/examples/datepicker/with-callback-overrides.js
- documentation-site/examples/heading/basic.js
- documentation-site/examples/heading/decouple-styles.js
- documentation-site/examples/popover/clipping.js
- documentation-site/examples/popover/dismiss.js
- documentation-site/examples/popover/link.js
- documentation-site/examples/popover/overrides.js
- documentation-site/examples/popover/placements.js
- documentation-site/examples/popover/ref-handling.js
- documentation-site/examples/popover/ssr-render-all.js
- documentation-site/examples/popover/stateful-click.js
- documentation-site/examples/popover/stateful-hover.js
- documentation-site/examples/popover/stateless.js
- documentation-site/examples/popover/with-arrow.js
- documentation-site/examples/radio/overrides.js
- documentation-site/examples/table/cells.js
- documentation-site/examples/tabs/overrides.js
- documentation-site/examples/typography/display.js
- documentation-site/examples/typography/heading.js
- documentation-site/examples/typography/text.js
- src/typography/__tests__/typography-display.scenario.js
Fixed missed typography component references.
> chore(typography): fix missed doc-site references'

- src/datepicker/locale.js
- src/locale.ts
- src/locale/index.js
- src/timepicker/timepicker.js
Removes `timePickerAriaLabel`. This has been replaced with `timePickerAriaLabel12Hour` and `timePickerAriaLabel24Hour`
> feat(timepicker): remove timePickerAriaLabel

- documentation-site/examples/fixed-marker/badge-and-label-enhancers.js
- documentation-site/examples/fixed-marker/badge-and-label-enhancers.tsx
- documentation-site/examples/fixed-marker/badge-enhancer-text.js
- documentation-site/examples/fixed-marker/badge-enhancer-text.tsx
- src/map-marker/index.d.ts
Fixes typescript errors
Patch: Bug Fix
> fix(map-marker): fix typescript errors

- src/accordion/__tests__/panel.test.js
- src/accordion/accordion.js
- src/accordion/index.d.ts
- src/accordion/panel.js
- src/accordion/stateless-accordion.js
- src/accordion/types.js
Removes renderPanelContent prop from the accordion.
> feat(accordion): remove renderPanelContent prop

- packages/eslint-plugin-baseui/README.md
- packages/eslint-plugin-baseui/__tests__/no-block-style.test.js
- packages/eslint-plugin-baseui/__tests__/no-component-classname.test.js
- packages/eslint-plugin-baseui/package.json
- packages/eslint-plugin-baseui/src/index.js
- packages/eslint-plugin-baseui/src/messages.js
- packages/eslint-plugin-baseui/src/no-block-style.js
- packages/eslint-plugin-baseui/src/no-component-classname.js
- packages/eslint-plugin-baseui/yarn.lock
Adds a lint rule to warn users when applying styles via className to base web components.
> feat(eslint): add no-component-classname lint rule

- src/menu/index.d.ts
Fixing incorrect type definitions for Menu component
> fix(menu): Fix typo in TS definitions

- packages/eslint-plugin-baseui/package.json
> chore(eslint): update peer deps

- .ladle/config.mjs
- package.json
- yarn.lock
- flow is an opt-in feature of Ladle (since it comes with a perf hit compare to typescript and not really used as often)
- using the latest vite 2.9 beta
> chore: upgrade ladle

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
- packages/eslint-plugin-baseui/src/no-shorthand-properties.js
> fix(eslint-plugin): add radiogroup override test and fix error

- README.md
I misconfigured the commit message in the feature branch here https://github.com/uber/baseweb/pull/4787
Creating a new one to trigger release scripts
> Release v11.0.0

- scripts/collect-bundle-sizes.js
Visits pages in batches of 10 instead of sequentially. This could likely be improved by fully parallelizing the task but this is straightforward and should be very similar speed
[before](https://buildkite.com/uberopensource/baseweb/builds/20665#ef3e2e3c-d4fd-40b6-b3da-da5001412875/197): 7m 45s
[after](https://buildkite.com/uberopensource/baseweb/builds/20725#70dddf33-fc48-4274-9df6-3a37e00c7f8a/197): 2m 3s
> chore(bundle-size): batch page visits to improve perf

- src/tag/types.js
Set $isFocusVisible to be optional for consistency.
> fix(tag): set $isFocusVisible to be optional

- documentation-site/components/version-selector.js
- package.json
removes all versions from v10 docs site version selector besides majors
> chore(docs): edit v10 version selector

- documentation-site/examples/empty-state/empty-state.js
- documentation-site/examples/empty-state/empty-state.tsx
- documentation-site/examples/empty-state/loading.js
- documentation-site/examples/empty-state/loading.tsx
- documentation-site/pages/components/empty-state.mdx
- documentation-site/routes.js
> feat(empty-state): add documentation

- src/select/__tests__/select-controlref.test.js
- src/select/__tests__/select-many-options.scenario.js
- src/select/__tests__/select.stories.js
- src/select/select-component.js
reverts https://github.com/uber/baseweb/commit/6720b356517448c3cd900c59e6de7ffc46ad6c9b
> Fix select with many options

- src/data-table/data-table.tsx
> fix(data-table): correct data-table rendering in react 18

- documentation-site/pages/blog/base-web-v7/index.mdx
- src/layer/tether.js.flow
- src/layer/tether.ts
- src/popover/popover.js.flow
- src/popover/popover.tsx
- src/select/__tests__/select-disable-href-anchor.scenario.tsx
Fix base web links updating http://baseui.design -> https://baseweb.design
> fix(dev): fix base web links

- documentation-site/cheat-sheet.js
- src/tabs-motion/tabs.js.flow
- src/tabs-motion/tabs.tsx
- src/tabs-motion/types.js.flow
- src/tabs-motion/types.ts
> fix(tabs-motion): expose TabBar override

- documentation-site/pages/guides/tables.mdx
> docs(table-guide): fix file ext

- documentation-site/components/yard/config/badge.ts
- documentation-site/components/yard/config/combobox.ts
- documentation-site/components/yard/config/datepicker.ts
- documentation-site/components/yard/config/message-card.ts
- documentation-site/components/yard/config/popover.ts
- documentation-site/routes.js
- src/datepicker/index.js.flow
- rangedCalendarBehavior isn’t showing up as a prop in Datepicker
- update docs for clearable combobox
- MessageCard `Button` override should indicate that it's a nested component
- baseui Badge doc playground has typo
- `triggerType` helper text for popover is wrong
- add Stepper to routes.js
> Docs cleanup

- documentation-site/components/yard/config/tile.ts
- documentation-site/examples/tile/action.tsx
- documentation-site/examples/tile/alignment.tsx
- documentation-site/examples/tile/multi-select-batch.tsx
- documentation-site/examples/tile/multi-select-live.tsx
- documentation-site/examples/tile/selection-no-trailing-content.tsx
- documentation-site/examples/tile/single-select.tsx
- documentation-site/pages/components/tile.mdx
- documentation-site/routes.js
Added documentation for Tile component.
https://github.com/uber/baseweb/assets/48413510/4742c5bc-b13a-4893-ae9e-2cc16cfb82b5
> Tile component documentation

- documentation-site/components/yard/config/file-uploader-beta.ts
- documentation-site/pages/components/file-uploader-beta.mdx
- package-lock.json
- Remove `FileUploader` Style Overrides and add `FileUploaderBeta` Style Overrides\
- Update the main description and include a note about how the existing `FileUploader` Style Overrides are accepted
- Verify on local dev environment that each style renders when set through the doc page
> Update Style Overrides

- documentation-site/components/yard/config/file-uploader-beta.ts
- documentation-site/pages/components/file-uploader-beta.mdx
- Enumerate props list
- Add `Inheritance` section detailing how the component leverages `FileUploader` props
- Change `When to use` -> `How to use` section and include brief details on new funcitonality.
> Update Props and Usage Description for File Uploader Beta

- documentation-site/examples/file-uploader-beta/basic.tsx
- documentation-site/pages/components/file-uploader-beta.mdx
- Add basic example for file uploader beta
> File uploader beta basic example

- documentation-site/examples/file-uploader-beta/upload-restrictions.tsx
- documentation-site/pages/components/file-uploader-beta.mdx
- Add upload restrictions example
- Remove extra props from basic example
> File uploader beta upload restrictions example

- documentation-site/examples/file-uploader-beta/item-preview.tsx
- documentation-site/pages/components/file-uploader-beta.mdx
> File uploader beta item preview example

- documentation-site/examples/file-uploader-beta/item-preview.tsx
- documentation-site/examples/file-uploader-beta/upload-restrictions.tsx
- Hard code uploaded files for examples
> File uploader beta hard code file examples

- src/file-uploader-beta/__tests__/file-uploader-beta.test.tsx
- src/file-uploader-beta/file-uploader-beta.tsx
- src/file-uploader-beta/styled-components.ts
- src/file-uploader-beta/types.ts
- src/file-uploader-beta/utils.ts
- Fork baseui from monorepo, includes
- Test changes
- Style changes
- Animation additions
- Type cleanups
> Fork file uploader beta from basui

- documentation-site/examples/file-uploader/upload-restrictions.tsx
Fix text on upload restriction example
Patch: Bug Fix
Before:
After:
> Fix file count on upload restriction example

- .github/workflows/release.yml
Upgrade pnpm/action-setup  to fix cloudflare delpoyment issue. Taken from https://github.com/pnpm/action-setup/issues/135
> Upgrade pnpm/action-setup
