uber/baseweb

- src/components/popover/popover.js
Fixes an issue that happened with opening an closing popovers really quickly.
The issue is that when the popover closes, we still want to leave it in the DOM for a couple hundred milliseconds so it can animate out. To make that work, we do a setTimeout for a few hundred milliseconds into the future, when we'll remove the popover from the DOM. But this causes an issue if the popover is immediately opened again before that timeout fires. To fix that, we clear any existing timers when opening.
> fix(popover): fix behavior when opening and closing quickly

- .buildkite/pipeline.yml
- README.md
In an effort to move to the buildkite org `uberopensource`, we have to assign queues to build steps.
> refactor(buildkite): use worker and builder queues

- src/components/radio/radiogroup.js
It is not possible to disable an option in a `RadioGroup`, this change correctly disables a radio option if the `RadioGroup` is disabled or itself is disabled.
> Radio option should be disabled if the group or itself is disabled

- flow-typed/globals.js
- src/components/menu/stateful-container.js
- src/components/popover/popover.js
Same thing that exists in fusion:
https://github.com/fusionjs/fusion-core/blob/master/flow-typed/globals.js
Prevents us from needing $FlowFixMe comments around these.
> chore(flow): set up types for cup globals

- src/styles/__tests__/styled.test.js
- src/styles/styled.js
This allows this behavior to work as expected
```js
import {styled} from 'baseui';
const Base = styled('div', {color: 'red'});
const BaseBlue = styled(Base, {color: 'blue'});
```
Yes
MIT
> feat: extend styled function to use withStyleDeep

- rfcs/modal-component.md
RFC for modal component (Click "Files changed" above). Attempts to take all the best API design bits from other modals on the market (material-ui, antd, palantir, etc), as well as accessibility best practices.
Two other lingering topics that I'd appreciate your feedback on:
People can render whatever arbitrary content they want, but we also want to make it easy to create a beautiful standard modal. After some thought, I think one of the two following APIs would be best:
```js
<Modal
isOpen={this.state.open}
title="Hello world!" // string|React.node
actions={[{
// Actions are mapped to `<Button>` instances, essentially same props
type: 'secondary'
label: 'Close'
onClick: this.handleClose
}, {
type: 'primary'
label: 'Close'
onClick: this.handleSubmit
isLoading: this.state.isSubmitting
}]}
> …
```
> [RFC] Modal Component

- src/menu/utils.js
Fix for an issue reported by @nudge:
```
ReferenceError: window is not defined
at Object.polyfill (/Users/davidng/Uber/src/riderpayments/web-payments-experience-2/node_modules/smoothscroll-polyfill/dist/smoothscroll.js:8:13)
at Object.<anonymous> (/Users/davidng/Uber/src/riderpayments/web-payments-experience-2/node_modules/baseui/menu/utils.js:18:32)
7:33 AM
```
> i think because the smoothscroll polyfill is being called regardless of browser/backend inside menu/utils.js
Wrapping this call in a `__BROWSER__` should do the trick.
> fix(menu): only polyfill smoothscroll in browser env

- rfcs/button-component.md
These are only needed if using `overrides` I think.
> docs(button): remove enhancers from usage example

- src/button/button.js
- src/button/examples.js
Properly set default button shape to `default`. This is what was causing the weird padding we were seeing, @schnerd
Default
Compact
> fix(button): set default shape to default

- src/button/__tests__/__snapshots__/styled-components.test.js.snap
- src/button/styled-components.js
Adding `:focus:enabled` styling so that keyboard users will know which button is focused when tabbing through.
Seems to be in line with what antd and material-ui are doing. I'm using our `hover` style here because we don't have a separate styling for `focus`. @nguyensomniac can you take a look?
[Live Preview](https://deploy-preview-216--baseui.netlify.com/)
> fix(button): add focus style in-lieu of outline

- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/select.js
- src/select/types.js
According to discussions here: https://github.com/uber-web/baseui/pull/227#pullrequestreview-154460579
`defaultProps` will properly marked "required" props from `PropsT` as optional so we do not need the additional typing.
> fix(select): remove DefaultPropsT

- src/helpers/__tests__/__snapshots__/overrides.test.js.snap
- src/helpers/__tests__/overrides.test.js
- src/helpers/overrides.js
- src/utils/__tests__/deep-merge.test.js
- src/utils/deep-merge.js
This PR updates our `overrides` logic to have more intelligent merging capabilities.
We'll use an example of ModalButton, which is just a `Button` with some default margin applied to it:
```js
const overrides = {
BaseButton: {
style: ({$theme}) => ({
marginLeft: $theme.sizing.scale500,
}),
},
};
export default class ModalButton extends React.Component<ButtonPropsT> {
static defaultProps = Button.defaultProps;
render() {
return (
<Button
{...this.props}
overrides={mergeOverrides(overrides, this.props.overrides)}
>
{this.props.children}
</Button>
);
}
}
```
With the existing logic on master, someone passing in a style override to ModalButton would _replace_ the margin styles here. The same goes for props (although we don't have any props in this example).
Ideally we can apply our …
> chore(overrides): better merging of overrides objects

- src/modal/examples.js
- src/popover/examples.js
- src/tooltip/examples.js
I've been using a fake button for the popover/tooltip/modal stories – updating these to use the new Button component.
> docs: update stories to use new button component

- .buildkite/pipeline.yml
- .eslintignore
- TESTING.md
- docker-compose.yml
- jest-e2e.config.js
- src/checkbox/e2e.js
- src/e2e-test-utils.js
- src/e2e-test.setup.js
- src/modal/e2e.js
This initial PR just integrates Sauce Labs with the project, but does not address a few important things, that will be covered in follow up PRs:
* run tests in different browsers
* proper instructions on running Sauce Labs tests from local dev envs
* migrating over to Nightwatch
* link sauce lab builds to PRs
* "thank you" to sauce labs in the README
https://saucelabs.com/beta/tests/b14ca805d1174333bb8949c5a2715389/commands
> feat(testing): integrate saucelabs

- package.json
Sometimes the sauce lab connection from buildkite to suacelab seems flaky. It causes tests to fail sometimes - this will try any failed tests cases up to two more times.
> fix(e2e): add retry logic

- src/menu/types.js
- src/select/__tests__/select.test.js
- src/select/examples.js
- src/select/select.js
- src/select/types.js
Fix for #312 
Since `selectedOptions` is the value of the form control, it should _not_ be part of the state. Since `Select` is intended to be a controlled component, it should always reflect the value passed in through props.
> fix(select): remove selectedOptions from controlled select state

- rfcs/toast-component.md
- src/toast/__tests__/__snapshots__/styled-components.test.js.snap
- src/toast/__tests__/toaster.test.js
- src/toast/constants.js
- src/toast/examples-list.js
- src/toast/examples.js
- src/toast/index.js
- src/toast/styled-components.js
- src/toast/toast.js
- src/toast/toaster.js
- src/toast/types.js
API:
```
create: function create(props?: $Shape<ToasterPropsT>): React.Node {},
show: (children: React.Nade, props: $Shape<ToastPropsT>): ?React.Key => {},
info: (children: React.Nade, props: $Shape<ToastPropsT>): ?React.Key => {},
positive: (children: React.Nade, props: $Shape<ToastPropsT>): ?React.Key => {},
warning: (children: React.Nade, props: $Shape<ToastPropsT>): ?React.Key => {},
negative: (children: React.Nade, props: $Shape<ToastPropsT>): ?React.Key => {},
update: (key: React.Key, props: $Shape<ToastPropsT>): void => {},
clear: (key?: React.Key): void => {},
```
Toaster rendered using portals so it's only rendered on a client side. Therefore any toast can only be added after a component mounted.
[Examples](https://deploy-preview-370--baseui.netlify.com/?selectedKind=Toast&selecte …
> feat(toast): add toaster component (part 1)

- package.json
Otherwise will see the following warning on commit
```
Warning: Setting pre-commit script in package.json > scripts will be deprecated
Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
Or run ./node_modules/.bin/husky-upgrade for automatic update
See https://github.com/typicode/husky for usage
```
> chore(package): move commit hooks to husky.hooks to avoid warnings

- rfcs/select-component.md
- src/menu/option-list.js
- src/menu/types.js
#377
Fix for 4
> When a custom option is used, the keyboard arrows will accurately navigate through the dropdown options. However, the style of the focused item is overridden by the custom option (this means you cannot see which item is focused on the UI any longer). There is no prop that I can find that indicates which option/index is focused. Therefore I cannot apply custom styles to the focused option to indicate to the user that it will be selected once Enter is pressed.
> fix(menu): propagate props for highlight state

- README.md
Baseui requires peer dependencies, which should be installed but are not listed in the `Usage` section. Additionally, update the example with loading of the Styletron Client and Provider (seems required?)
> Update README.md to handle dependencies

- src/select/styled-components.js
> fix(select): position the search icon in the middle vertically

- src/themes/README.md
The file where these primitives are defined changed in #460. This updates the themes README to point to the correct file, and updates the code example to correct usage
> docs(readme): fix themes code example

- src/button/styled-components.js
- src/input/styled-components.js
Makes `Button` and `Input` respect the `borders.useRoundedCorners` theme setting
> Make button/input respect useRoundedCorners

- src/progress-steps/examples.js
- src/progress-steps/styled-components.js
The original examples for `ProgressSteps` didn't apply the correct font styles to the step content.  The examples now use the `Block` component to apply the correct styles.
MIT
> fix: update styles of ProgressSteps example

- src/form-control/__tests__/form-control.test.js
- src/form-control/form-control.js
- src/form-control/types.js
The form control container is not currently capable of being overridden. According to the [Form Control docs](https://baseui.netlify.com/?selectedKind=Form%20control&selectedStory=controls%20with%20label%20and%20caption&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) `ControlContainer` should be part of the `overrides`. This PR adds that missing functionality.
Yes
No
MIT
> fix(form-control): add support for control container override

- rfcs/modal-component.md
Pretty sure I messed this up – should be `onClose` not `close`
> docs: fix modal example [skip ci]

- src/toast/__tests__/__snapshots__/styled-components.test.js.snap
- src/toast/__tests__/styled-components.test.js
- src/toast/__tests__/toast.test.js
- src/toast/styled-components.js
- src/toast/toast.js
- src/toast/toaster.js
- src/toast/types.js
As of right now, `Toast`s do not animate in – they only animate out. This PR updates the logic so that they animate in as well.
Yes
No
No
Yes
> fix(toast): fix animate in

- .eslintrc.js
- e2e/tests.js
- src/card/__tests__/card.test.js
- src/checkbox/examples.js
- src/input/examples.js
- src/modal/__tests__/modal.test.js
- src/pagination/icons.js
- src/tag/examples.js
- src/textarea/examples.js
Even though we had the `jsx-a11y` dependency installed, the eslint rule wasn't enabled for some reason.
This PR enables the recommended linting rules and corrects the failing areas (most of which are in our examples).
Here is an example output for an accessibility issue:
MIT
> fix: enable jsx-a11y checks in eslint

- src/radio/__tests__/__snapshots__/styled-components.test.js.snap
- src/radio/__tests__/styled-components.test.js
- src/radio/index.js
- src/radio/radiogroup.js
- src/radio/radiomark.js
- src/radio/styled-components.js
Selecting a radio element in firefox previously caused a 'jitter' due to animating both the element `width/height` and `border-width` at the same time. Isolating either the `width/height` or `border-width` animations resulted in smooth transitions. [minimal reproducing example](https://codesandbox.io/s/v387xqmq0y)
Approach to fix was to break the single element into two nested elements so that only the inner circle needs to animate.
> fix: remove radio animation jitter in firefox

- src/select/types.js
Referencing `e.target.value` throws flow error `Cannot get e.target.value because property value is missing in EventTarget [1].`.  Input type should be updated to `SyntheticInputEvent`
> fix(input): change onInputChange event to be type input

- src/icon/__tests__/styled-components.test.js
- src/icon/examples.js
- src/icon/styled-components.js
Previously, if you passed in a string for $size, Icon would set the height and width to that string, resulting in an invalid CSS property (and causing the icon to not render). This is easy to repro by supplying an icon as a Button enhancer and leaving the size as the default. (Button spreads the $size prop to the Icon eventually)
This didn't get caught before because the examples use
`enhancer={() => <Icon />}` instead of `enhancer={Icon}`, which creates an intermediate component layer between Button and Icon, which "traps" the props and prevents them from being spread all the way down.
> fix: proper fallback for size prop

- rfcs/breadcrumbs-component.md
- screener.config.js
- src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
- src/breadcrumbs/__tests__/__snapshots__/styled-components.test.js.snap
- src/breadcrumbs/__tests__/breadcrumbs.test.js
- src/breadcrumbs/__tests__/styled-components.test.js
- src/breadcrumbs/breadcrumbs.js
- src/breadcrumbs/examples-list.js
- src/breadcrumbs/examples.js
- src/breadcrumbs/index.js
- src/breadcrumbs/stories.js
- src/breadcrumbs/styled-components.js
- src/breadcrumbs/types.js
- src/styles/types.js
- src/themes/creator.js
- src/themes/dark-theme.js
This PR introduces the new `Breadcrumbs` component. To increase flexibility this component only applies styling and chevron separators between its children.
Yes
MIT
> feat: introduce Breadcrumbs component

- src/select/types.js
```
Cannot assign object literal to opt because property content is missing in object literal [1] but exists in OptionT [2].
3│
4│ import {Select, TYPE, type OptionT, type ValueT} from 'baseui/select';
5│
[2][1]  6│ const opt: OptionT = {
7│   id: 'test',
8│   content: 'red',
9│ };
10│
```
$Shape makes all properties optional but also makes it an exact type where no other keys are allowed. This prevents us from using the `labelKey` prop to control which object property is used as the label.
> fix(select): make option type inexact

- rfcs/header-navigation-component.md
- src/header-navigation/__tests__/__snapshots__/header-navigation.test.js.snap
- src/header-navigation/__tests__/__snapshots__/styled-components.test.js.snap
- src/header-navigation/__tests__/header-navigation.test.js
- src/header-navigation/__tests__/styled-components.test.js
- src/header-navigation/constants.js
- src/header-navigation/examples-icons.js
- src/header-navigation/examples-list.js
- src/header-navigation/examples.js
- src/header-navigation/header-navigation.js
- src/header-navigation/index.js
- src/header-navigation/stories.js
- src/header-navigation/styled-components.js
- src/header-navigation/types.js
- src/styles/__mocks__/as-primary-export-hoc.js
- src/styles/as-primary-export-hoc.js
- src/styles/index.js
- src/test/test-framework-setup.js
add header navigation implementation
Header navigation is highly customizable component. All examples provide different ways customers can address their design and concerns. They mainly show flexibility of Base UI rather than component itself.
> feat(header-navigation): add implementation

- src/accordion/__tests__/panel.test.js
- src/accordion/accordion.js
- src/accordion/examples.js
- src/accordion/types.js
based fix on flow children docs [here](https://flow.org/en/docs/react/children/#toc-only-allowing-a-specific-element-type-as-children) and information in flow issue [here](https://github.com/facebook/flow/issues/4625)
another issue was coming from how we reused the `key` prop. i replaces type references to that prop with reacts provided type `React.Key` for compatibility
> fix(accordion): removes flowfixme comments in accordion component

- src/tag/examples-list.js
- src/tag/examples.js
I did not find a use case where we want to render images inside tags - so I'd like to remove this example that could potentially mislead folks
> docs(tag): remove example with components inside a tag

- README.md
- package.json
N/A
Yes
No
No
No code changes
README updated
Only for consumers (removed peer dependency)
MIT
styletron-standard is a utility package that developers using BaseUI should never interact with directly. There's no reason this should be a peer dependency so it can be removed.
> chore: remove styletron-standard peer dependency

- src/popover/__tests__/stateful-container.test.js
- src/popover/stateful-container.js
Correctly wires up the `onOpen` `onClose` callbacks for StatefulPopover that exist in the docs but not in the implementation.
Yes
No
No
Yes
> fix(popover): fix onOpen/onClose callbacks

- src/block/README.md
- src/block/__tests__/block.test.js
- src/block/block.js
- src/block/examples-list.js
- src/block/examples.js
- src/block/styled-components.js
- src/block/types.js
Block component should support basic layout CSS properties. It already supported flexbox, this PR adds grid as well. Adding more new props doesn't scale all that well, but for now I guess it's ok.
> feat(block): add CSS Grid properties

- flow-typed/npm/jest_v23.x.x.js
- src/popover/__tests__/popover.test.js
`yarn test` currently has the following warning for popover:
```
PASS  src/popover/__tests__/popover.test.js
● Console
console.warn node_modules/enzyme-matchers/lib/utils/deprecate.js:19
Matcher toHaveTagName is deprecated and will be removed in a future release. Use the replacement, toHaveDisplayName instead.
```
This PR migrates from toHaveTagName to toHaveDisplayName to fix this issue.
> fix(popover): fix enzyme matcher warning in tests

- src/rating/__tests__/star-rating.test.js
ensures that the `StarRating` component can be `mount`ed
> test(rating): mount star rating test

- src/input/__tests__/__snapshots__/styled-components.test.js.snap
- src/themes/creator.js
- src/themes/light-theme-primitives.js
Hi all!
There's a few small PRs I want to open to help sync type styles with what designers currently use. The first step is to get both the internal and external type ramps consistent with each other.
This way we can tweak type styles without any negative side effects to the OS version of baseui and vice versa. In addition, fixes #226 so the metrics of the type we use match up better.
I suppose this is technically a breaking change...but I'd rather rip the bandaid off sooner so we can keep things in sync.
#226 
MIT
> Change default type ramp to be consistent with Uber move theme

- src/input/__tests__/__snapshots__/styled-components.test.js.snap
- src/themes/dark-theme-primitives.js
- src/themes/light-theme-primitives.js
- src/themes/light-theme-with-move.js
Addresses @gergelyke's comments in #645 and changes fallback fonts to be more consistent.
Removes Open Sans from our font stack and replaces it with `system-ui`, since from my knowledge Open Sans doesn't come preinstalled on any OS and is therefore redundant.
> fix: Type stack fixes

- .storybook-base/loadStories.js
- .storybook-dark/config.js
- .storybook-move/config.js
- .storybook/config.js
- src/file-uploader/stories.js
updates the storybook site to sort 'unstable' components to the end.
> fix: organize unstable components in storybook

- src/header-navigation/styled-components.js
While trying to use this component, flow was complaining about undefined `React`. Also `React$Node` is a typo + both props should be optional?
> fix(header-navigation): optionals

- src/menu/stateful-container.js
- src/menu/utils.js
- src/select/dropdown.js
Resolves #658 
When you select an item and re-open the select you should be scrolled to it.
**Before**
**After**
> feat(select): scroll to the selected option

- src/header-navigation/__tests__/__snapshots__/styled-components.test.js.snap
- src/header-navigation/styled-components.js
Yes
For some reason the root header navigation element has `cursor: pointer`. This is unnecessary and misleading, and the interactive elements _within_ a header should be the ones controlling cursor behavior.
> fix(header-navigation): use normal cursor

- src/breadcrumbs/README.md
The Link component exports as `StyledLink`, not `Link`. Although maybe we should export as both?
> fix: Update breadcrumbs docs

- src/popover/README.md
- src/tooltip/README.md
Looked at the popover docs again the other day and realized I wasn't super thorough or accurate when writing them the first time around. This PR attempts to fix this and make sure all available props for each export are thoroughly documented.
> docs(popover): update popover and tooltip docs [skip ci]

- .eslintignore
- .gitignore
- documentation-site/next.config.js
- netlify.toml
- package.json
we use the docs folder to keep source files, but also as an output folder for generate static sites - this PR introduces a new folder that's exclusively used for building static sites
once merged, I'll update the netlify config
> fix(build): use the public folder

- src/header-navigation/examples-list.js
Caught a minor spelling mistake: https://baseui.netlify.com/?selectedKind=Header%20Navigation&selectedStory=With%20different%20styled%20Navigstion%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
> Spelling mistake in example

- .github/ISSUE_TEMPLATE/1.bug.md
- .github/ISSUE_TEMPLATE/2.feature.md
- .github/PULL_REQUEST_TEMPLATE.md
It simplifies all GitHub templates (especially the one for PRs). Feedback appreciated! 
The idea is to make them more detailed again if needed (once the contributor base is much larger). For now, let's keep it as minimal as possible?
> chore: simplify github templates

- src/select/__tests__/__snapshots__/styled-components.test.js.snap
- src/select/styled-components.js
search icon is no longer above an overlapping dropdown menu
> fix(Select): fix select search icon z-index

- documentation-site/pages/components/checkbox.mdx
- documentation-site/static/examples/checkbox/toggle.js
currently, this is its own section in storybook but I find it a bit misleading since we are re-using the same Checkbox import. Happy to change to it's own page if others feel strongly
> docs(Checkbox): adds toggle example

- documentation-site/components/example.js
- documentation-site/pages/components/menu.mdx
- documentation-site/pages/components/select.mdx
- documentation-site/routes.js
- documentation-site/static/examples/menu/basic.js
- documentation-site/static/examples/menu/child.js
- documentation-site/static/examples/menu/compact.js
- documentation-site/static/examples/menu/profile.js
- documentation-site/static/examples/menu/stateful.js
- documentation-site/static/examples/menu/virtual-list.js
- src/menu/README.md
- src/menu/stateful-menu.js
- src/menu/types.js
adds a new prop to the `Example` component to pass additional npm packages. This ensures that the `react-virtualized` example works correctly in the code sandbox
> docs(menu): adds menu to docs site

- src/pagination/__tests__/__snapshots__/styled-components.test.js.snap
- src/pagination/styled-components.js
`Fixes #1, Fixes #2` 
before:
after:
> fix(pagination): dropdown z-index bug

- documentation-site/components/component-menu.js
- documentation-site/components/example.js
- documentation-site/components/github-logo.js
- documentation-site/components/layout.js
- documentation-site/components/sidebar.js
- documentation-site/routes.js
- add github link to the header
- remove `Storybook (legacy)` link, mostly because it doesn't fit and it also doesn't seem that useful? If so we could add it to the sidebar
- add github links to all code examples
- make sidebar spacing more condensed and even
Let me know what you think!
> feat(docs): add github links and simplify spacing in the sidebar

- documentation-site/components/layout.js
- documentation-site/components/search.js
- documentation-site/pages/_document.js
Note that in the preview it redirects from `localhost` to `baseui.design`, that's why the search input jumps.
> feat(docs): add algolia search

- src/toast/__tests__/toaster.test.js
- src/toast/examples.js
- src/toast/toaster.js
- src/toast/types.js
Based on the [API doc](https://github.com/uber-web/baseui/tree/master/src/toast#toastercontainer-api), ToasterContainer API states there is `autoHideDuration` but it isn't implemented
To test this is working, I added an example in storybook:
The right most button will be dismissed after 0.5 seconds as the ToasterContainer has the following property set:
<ToasterContainer
placement={PLACEMENT.bottomRight}
autoHideDuration={500}
/>
The `toaster` props `autoHideDuration` overrides the `ToasterContainer`'s `autoHideDuration` if present.
> feat(toast): add autoHideDuration to ToasterContainer

- package.json
- yarn.lock
There's no actual breaking change between 0.x and 1.x.
> chore: bump react-movable to v1

- scripts/now-deploy.sh
deploy to now failed on `jq` not found. i wonder why... 😈
> fix(build): uncomments the jq install >.<

- src/accordion/e2e.js
- src/accordion/styled-components.js
Adds a11y test for accordion. This required changing an element from an `h3` to a `div` because `button` is not an appropriate `role` for an `h3` element.
> test(e2e): adds accordion a11y test

- documentation-site/pages/components/dnd-list.mdx
- package.json
- src/dnd-list/list.js
- src/dnd-list/types.js
- yarn.lock
It brings much better [support for iOS Safari](https://github.com/tajo/react-movable/releases/tag/v2.0.0) and there is no need to `stopPropagation` for remove handle.
Also, underlying flow types are now correctly linked, so some updates were necessary to fix it for baseui.
> react-movable v2 upgrade

- docs/migrations/00875.md
- src/table/__tests__/__snapshots__/styled-components.test.js.snap
- src/table/__tests__/styled-components.test.js
- src/table/index.js
- src/table/styled-components.js
this `styled` component is no longer used
> chore(table): removes styledcontent component

- docs/migrations/00874.md
- src/button-group/README.md
- src/button-group/button-group.js
- src/button-group/types.js
deprecates the `kind` prop from `button-group`. design only wants a single option here
> chore(button-group): deprecate kind prop

- src/datepicker/calendar-header.js
> fix(datepicker): remove padding in the select dropdown container

- src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
- src/datepicker/__tests__/stateful-calendar.scenario.js
- src/datepicker/__tests__/stateful-datepicker-quick-select.scenario.js
- src/datepicker/__tests__/stateful-range-quick-select.scenario.js
screener was failing on mismatched dates (the scenarios were running based on the current date)
> fix: ensures consistent date in calendar screener

- package.json
- yarn.lock
`styletron-atomic-engine` update gracefully handles error thrown from older browsers. see relevant pr and linked discussions here: https://github.com/styletron/styletron/pull/282
> fix(input): update styletron-atomic to handle ie 11 placeholder fail

- scripts/now-deploy.sh
_Developers using the project find it hard to know what features are unavailable in older package versions based on the documentation site. This is because we only publish the most up to date documentation._
Idea for how to keep a log of docs site versions. 
In addition to updating the alias to the most up-to-date site, we can maintain an alias to older deployments based on commit hash. To map releases to deployments, we can first request from github the [list of tags](https://developer.github.com/v3/git/refs/#get-all-references)  (which include the commit hash). On zeit's side we can request for [aliases](https://zeit.co/docs/api#endpoints/aliases) we have, then do a merge on matches. I looked at the way react handles keeping docs around and it seems like they are doing something similar …
> feat(docs-site): adds an alias mapping to commit hash

- documentation-site/static/examples/table/cells.js
width was too tight to fit all of the columns
> fix(table): fixes table docs example

- documentation-site/pages/components/table.mdx
- documentation-site/static/examples/table/graph.js
- package.json
- yarn.lock
This adds a new table example. It doesn't modify the table component. 
The visualizations are slightly different than Figma since `react-vis` is pretty opinionated.
> docs(table): add example using react-vis

- src/avatar/__tests__/__snapshots__/styled-components.test.js.snap
- src/avatar/styled-components.js
handles the transparent image issue that was apparent in the contributors list
> fix(avatar): handle transparent avatar images

- documentation-site/pages/components/progress-bar.mdx
- documentation-site/pages/components/spinner.mdx
- documentation-site/static/examples/progress-bar/negative.js
- documentation-site/static/examples/spinner/negative.js
- src/progress-bar/__tests__/progressbar-negative.scenario.js
- src/spinner/__tests__/__snapshots__/styled-components.test.js.snap
- src/spinner/__tests__/component.test.js
- src/spinner/__tests__/spinner-negative.scenario.js
- src/spinner/__tests__/styled-components.test.js
- src/spinner/index.js
- src/spinner/spinner.js
- src/spinner/styled-components.js
- src/spinner/types.js
Aligns the spinner design more with mocks. Broke the component out into two overridable `path` elements. This was important so that the 'track' color is not hard-coded for if this is on an alternate theme.
> feat(spinner): enables negative color

- documentation-site/pages/getting-started/installation.mdx
- `styletron-react-core` is a legacy version of `styletron-react`, should not be installed
- `styletron-standard` is a dep of `styletron-react`, no need to install separately
- adding links to styletron.js.org
**DON'T merge until styletron.js.org goes alive**
> docs: update the installation page

- documentation-site/components/api.js
- documentation-site/pages/components/tabs.mdx
- documentation-site/static/examples/tabs/basic.js
- documentation-site/static/examples/tabs/vertical.js
Fix to use the new `Heading` component. I've also changed the expand buttons from `primary` to `tertiary` since they were too "loud".
`activeKey` doesn't exist, `initialState={{ activeKey }}` is the right way.
> docs: fix API doc headings and StatefulTab examples

- src/menu/styled-components.js
Some CSS libraries/UI kits add a bottom margin to list items by default (I know it's a bad practice).
Set this up so the menu items don't look wonky when using it with those libraries, to aid users who are migrating off other UI kits.
> fix(menu): add marginBottom: 0 for list items

- src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
- src/breadcrumbs/breadcrumbs.js
closes  https://github.com/uber-web/baseui/issues/969
fixes https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318
> fix(breadcrumbs): key prop

- documentation-site/components/api.js
- documentation-site/components/example.js
- documentation-site/prism-coy.css
- increase the top margin of `<h2>`
- use the size compact, kind secondary for all action buttons (Show source code, CodeSandbox, Expand Prop Shape)
- Prop API docs should have the same spacing after their title as all other elements
> docs: spacing improvements

- CONTRIBUTING.md
- documentation-site/pages/getting-started/learn.mdx
- fix typo in `learn.mdx`.
- fix typos in `CONTRIBUTING.md`. Not sure if `T0D0` is intentional though for CI.
- remove dead link in `CONTRIBUTING.md`.
> docs: fix typos and remove broken link

- src/datepicker/calendar.js
> fix(datepicker): safari stacked buttons

- src/datepicker/__tests__/datepicker.e2e.js
- src/datepicker/__tests__/datepicker.scenario.js
- src/datepicker/datepicker.js
- src/popover/__tests__/popover.test.js
- src/popover/popover.js
- src/select/__tests__/__snapshots__/dropdown.test.js.snap
- src/select/dropdown.js
> fix(datepicker): ensures sub-popovers do not trigger close

- documentation-site/components/overrides.js
- documentation-site/pages/theming/understanding-overrides.mdx
There was some confusion about shorthand vs longhand CSS properties so I've added some description into the Understanding Overrides page and overrides inspector.
> docs: add notes about longhand vs shorthand props

- documentation-site/static/examples/table/fixed-width-column.js
Related Codesandbox https://codesandbox.io/s/p7zpq9qo7
Fix example to show smaller width for cell in Documentation website
> fix(table): updates example in table so smaller width works

- documentation-site/components/example.js
- documentation-site/components/layout.js
- documentation-site/components/markdown-elements.js
- documentation-site/components/nav-link.js
- documentation-site/pages/_app.js
- src/index.js
- src/themes/dark-theme-colors.js
- src/themes/dark-theme-with-move.js
- src/themes/dark-theme.js
- src/themes/index.js
This PR just enables the development of the Dark Theme - the look and feel will be off for the time being!
If you'd like to try it out, just visit any url using the `theme=dark` query string - once you want to change back to the light theme, use `theme=light`
> feat(docs): add dark theme switcher

- src/popover/__tests__/popover.test.js
- src/popover/popover.js
[reproducing example](https://codesandbox.io/s/91x3noq55o) (click a couple times and the popover should close without clicking outside of popover content)
This bug was caused by the change [here](https://github.com/uber-web/baseui/pull/1008/files#diff-7ec0bdc9296aa57a335fbcb29c2a0dfeR279). Reasoning for the change was to cause a failing test for the bug fix in related PR.
Issues surfaced because popover's `onDocumentClick` method was now called after click events on child elements. Once `onDocumentClick` was called (_after_ the popover component updated its children) it sees the updated tree and finds false-positive clicks outside of the popover.
**with `click` event listener**
**with `mousedown` event listener**
> fix(popover): ensure priority event timing

- documentation-site/static/examples/menu/child.js
- src/menu/__tests__/maybe-child-menu.test.js
- src/menu/__tests__/menu-child.scenario.js
- src/menu/__tests__/menu.e2e.js
- src/menu/__tests__/stateful-container.test.js
- src/menu/__tests__/utils.test.js
- src/menu/constants.js
- src/menu/index.js
- src/menu/maybe-child-menu.js
- src/menu/menu.js
- src/menu/nested-menus.js
- src/menu/option-list.js
- src/menu/option-profile.js
- src/menu/stateful-container.js
- src/menu/stateful-menu.js
- src/menu/styled-components.js
- src/menu/types.js
- src/menu/utils.js
- src/select/dropdown.js
- src/select/styled-components.js
- src/styles/types.js
- src/themes/creator.js
- src/themes/dark-theme-colors.js
- **Ensures targeted focus coloring** - Only one menu may be 'active' at any time. If the menu is active, highlighted menu item is blue. If inactive, highlighted menu item is black.
- **Fixes doubled item highlight** - Bug is described in [this issue](https://github.com/uber-web/baseui/issues/993). Mouse hover now triggers a state update, and this change removes highlight from css `:hover` pseudo-selector. Keyboard navigation between items will overwrite a mouse highlight and vice-versa. Always prefers the most recent action.
- **Fixes keyboard navigation with multiple menus** - Only initializes keyboard navigation on menu focus. Previously if multiple menus were on the page, they would all change the highlighted item.
- **Enables keyboard navigation between nested menus** - Adds a new …
> feat(menu): enables keyboard navigation between nested menus, provides proper focus feedback

- src/select/types.js
- fixes typo in `Select` prop description for `searchable`
> fix: select prop typo

- documentation-site/routes.js
- src/accordion/styled-components.js
- src/icon/alert.js
- src/icon/arrow-down.js
- src/icon/arrow-left.js
- src/icon/arrow-right.js
- src/icon/arrow-up.js
- src/icon/check-indeterminate.js
- src/icon/check.js
- src/icon/chevron-left.js
- src/icon/chevron-right.js
- src/icon/delete-alt.js
- src/icon/delete.js
- src/icon/filter.js
- src/icon/grab.js
- src/icon/icon-template.txt
- src/icon/menu.js
- src/icon/overflow.js
- src/icon/plus.js
- src/icon/search.js
- src/icon/spinner.js
- src/icon/triangle-down.js
- src/icon/triangle-left.js
- src/icon/triangle-right.js
- src/icon/triangle-up.js
- src/icon/upload.js
Some components allow for style overrides of icons, and apply their own styles to the icons. For example, the close icon on 'toast' has the cursor be a pointer on hover. Refactored the icons to call the main `Icon` component if globally overridden.
> fix(icon): applies isolated styles to globally overridden icons

- src/select/__tests__/select-creatable-multi.scenario.js
- src/select/__tests__/select.e2e.js
- src/select/select.js
Fixes problems mentioned in:
https://github.com/uber-web/baseui/pull/1086#pullrequestreview-219212436
https://github.com/uber-web/baseui/pull/1086#issuecomment-476900871
It now considers already created/selected values when filtering the list of options, so it doesn't suggest to create a new option if it already was created/selected.
> fix(select): don't suggest creation of an option that was already picked

- documentation-site/routes.js
- src/accordion/styled-components.js
Previously, if the 'plus' icon was overridden, it would not float to the right
> fix(accordion): icon layout evenly if overridden

- src/table/styled-components.js
StyledHead can't be styled with `withStyle` now
> fix(table): styledHead is missing styletron reassign

- src/link/styled-components.js
- src/themes/creator.js
- src/themes/dark-theme-colors.js
Make the Link component use the related theme tokens for its text color values.
> fix(link): get color values from related theme tokens

- package.json
- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/select.js
- src/select/styled-components.js
When importing and overriding an icon not included in baseui, the search icon was unstyled. This was due to the code assuming that the icon would always have the `overrides` prop.
before:
after:
> fix(select): enables globally overrided search icon

- src/avatar/styled-components.js
When `Avatar` is used with non-square images, they are displayed stretched (forced to square aspect ratio) unless an override is used. This makes the default behavior to center & crop using `object-fit: cover`.
> feat(avatar): crop non-square images

- src/block/__tests__/block.test.js
- src/block/styled-components.js
See new unit test. Previously, if the font value was not found in theme, the app would crash.
> fix(block): use safe get for font values

- src/button/styled-components.js
by default, safari ships buttons with margins of 2px, that's why the space between the buttons in the buttongroup component
> fix(button-group): add margins with values of zero

- documentation-site/pages/theming/custom-themes.mdx
I was also thinking about adding this to the Utility component section - what do you all think, should I leave this here, or move it to the Utilities?
> docs(themeprovider): add to the theming intro pages

- docs/migrations/01206.md
- src/tag/constants.js
- src/tag/index.js
This is a PR against the new `v7` branch.
> chore(tag): remove deprecated COLOR_STYLE_KEYS export

- docs/migrations/01204.md
- documentation-site/pages/blog/getting-started-with-base-web/index.mdx
- documentation-site/static/examples/button/basic-compact.js
- documentation-site/static/examples/button/shapes.js
- documentation-site/static/examples/icon/button.js
- src/button-group/__tests__/button-group-sizes.scenario.js
- src/button-group/button-group.js
- src/button/__tests__/button-sizes.scenario.js
- src/button/constants.js
- src/button/styled-components.js
- src/icon/__tests__/icon-buttons.scenario.js
Updates `Button` & `ButtonGroup` styles to match latest Base designs:
- Remove rounded corners from `Button`/`ButtonGroup`
- Adds a `large` size to `Button`/`ButtonGroup`
- Updates padding for all buttons to match latest Base designs
- Updates docs with new sizing option
- Removes `'square'` option for `shape` property (horizontal/vertical padding is the same by default now)
Existing buttons:
New buttons:
> feat(button): update button styles

- documentation-site/pages/_app.js
In browsers that expose `prefers-color-scheme` this will match the docs theme to the OS theme. Currently supported browsers are Safari and Firefox:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
The theme is set on initial page load and whenever the OS theme is changed. The theme toggle button continues to functional as it did previously.
- [✅] Minor: New Feature
> feat(theme): theme docs respect OS theme preference

- .buildkite/pipeline.yml
By default plugins always pull from the latest version unless they are pinned. Pin to v3.0.3 to see if we can avoid breakage with the latest commit.
> fix(buildkite): pin docker-compose plugin version

- package.json
Node is used only for our build tools and we don't really keep track with Node releases anyway. 
Also, **right now you can't deploy next.js app with baseui as a serverless lamba** since their environment currently supports only Node 8.10 and we are enforcing 8.11, so the build fails.
For `yarn` and `npm`, we don't have practical reasons to be restrictive.
> Remove engines fields, too restrictive and not being used

- src/pagination/pagination.js
- src/pagination/styled-components.js
Accessibility addition suggestions for pagination
Adds aria attributes to pagination controls for a11y. 
- `aria-haspopup="true"`
- `aria-expanded="false"`
- `aria-label="next page. current page 2 of 20"`
- `role="menu"`
> feat: accessibility addition suggestions for pagination

- src/block/types.js
Allow zero for scale props and numbers for flex props, as allowed in CSS
> fix(block): allow zero for scale props and numbers for flex props

- docs/migrations/01251.md
- documentation-site/static/examples/side-navigation/nav-overrides.js
- src/side-navigation/__tests__/__snapshots__/stateful-nav.test.js.snap
- src/side-navigation/nav-item.js
- src/side-navigation/nav.js
- src/side-navigation/types.js
`renderItem` is not necessary since it's identical to `overrides.NavLink.component`. However, overrides were not previously passed to `NavLink` and `NavItem` components. Also, simplifying the override example to focus on `style` rather than swapping the whole complicated component.
> feat(side-navigation): Remove renderItem prop, fix overrides

- documentation-site/pages/components/sidenav.mdx
Fixes wrong destructuring naming in the React Router side navigation example. This should be correct unless the example should rather be in the `onChange={({event: e, item}) => {` form.
> fix(docs): update react router sidenav example

- documentation-site/pages/components/select.mdx
- documentation-site/static/examples/select/label.js
Add custom label example. Also consistently title examples with sentence case.
> docs(select): add custom label example

- src/toast/toast.js
Adds a `tabIndex` attribute to the `<Toast/>` body so it can be focused and allow the the `onFocus`/`onBlur` event handlers to work correctly.
> fix(toast): add tabIndex to <Toast/> body so it can be focused

- documentation-site/components/theming-values/borders.js
- documentation-site/pages/theming/theming-values.mdx
Add example borders to documentation
> docs(theming-values): add example borders

- src/block/__tests__/block.test.js
- src/block/block.js
- src/block/styled-components.js
- src/block/types.js
Fixes #859
Add backgroundColor prop to Block, following the pattern of the color prop
> feat(block): add backgroundColor prop to Block

- documentation-site/pages/components/menu.mdx
- src/menu/__tests__/stateful-container.test.js
- src/menu/menu.js
- src/menu/stateful-container.js
- src/menu/stateful-menu.js
- src/menu/types.js
`aria-activedescendant` has to be an `id` of the active menu element. In the current PR I added a simple default id values for the menu items. 
I propose we don't add id values by default but put the functionality in place to handle it if there are ids provided for the items through `getRequiredItemProps` handler. It's due to the `id` attribute value has to be unique on a page, with SSR using `Math.random` or UUIDs will result in invalid checksum warnings.
> fix(menu): add aria-activedescendant

- documentation-site/components/sidebar.js
- src/side-navigation/nav-item.js
Initial problem: The documentation site sidebar looks wrong.
Turns out the sidebar was still using a now deleted `renderItem` property on the `Navigation` component to customize each item in the nav.
This PR fixes the issue by updating the sidebar to use the `NavItem` override on `Navigation`.
There is also a tangential fix to pass through a missing `item` property to the `NavItem`. This was already in the `NavItemPropsT` type but was not being passed through.
> fix(nav-item): add missing item prop and update doc site sidebar

- src/menu/__tests__/stateful-container.test.js
- src/menu/stateful-container.js
Passes the click event through onItemSelect when stateful container items are clicked to allow users to intercept the event. The use case I have is for a button dropdown nested inside of another clickable element. This is my first PR to baseui, any comments/suggestions are would be great 😄
> feat(menu): pass event to onItemSelect when called with onClick

- src/input/__tests__/__snapshots__/masked-input.test.js.snap
- src/input/masked-input.js
- src/input/types.js
Avoid passing overrides to MaskOverride. These overrides do nothing here and show up in the DOM and cause React warnings.
Note that the snapshot `MaskedInput - basic functionality: Masked input has correct props 1` now matches `Input - basic functionality: input has correct props 1`.
Also:
* Still allows for `{Input: {style}}` overrides
* Export MaskedInputPropsT type
* Remove weak Flow type
> fix(masked-input): avoid passing overrides to MaskOverride

- package.json
v6.19.2 has some issues with the currently published version. Publish a new release so folks will skip the mis-published version.
> Release v6.19.3

- src/input/__tests__/__snapshots__/masked-input.test.js.snap
- src/input/__tests__/masked-input.test.js
- src/input/masked-input.js
Properly pass props to the `<input>` element in a MaskedInput component. According to the docs, react-input-mask does not pass down [certain props](https://github.com/sanniassin/react-input-mask#children--function) to its children. This broken behavior is easily reproduced by trying to disable a MaskedInput, and explicitly passing these to its children resolves the issue.
> fix(masked-input): pass props to input

- src/select/styled-components.js
In dark mode color of the input blends with the background , so one can't see what is the value
> fix: updating Select/StyledValueContainer to fix text color in dark mode

- src/datepicker/timezone-picker.js
I needed to make the TimezonePicker disabled in the project I am working on and found that it was impossible to do it through the overrides prop. The TimezonePicker supports overriding the Select element, but the overridden props were not properly passed to the Select element. 
I have now added the select overrides to the OverriddenSelect element.
> fix(timezone-picker): fix select overrides

- documentation-site/components/header-navigation.js
It's probably not used very often but it stands out a lot. Changed the KIND from `primary` to `minimal` and removed the chevron since that's [not a pattern](https://baseweb.design/components/popover/#popover-opens-on-click) in our design system.
> docs: deemphasize version selector

- documentation-site/components/blog.js
- documentation-site/components/posts.js
- documentation-site/pages/_app.js
- documentation-site/tomorrow-night.css
It was a huge eyesore. 
Also some minor dark theme fixes in the blog section:
- meta text (author, date, subttitle) were invisible
- `Read` button did a full page reload (unnecessary and the flashing white background looked really bad)
> docs: dark theme for code examples

- documentation-site/static/examples/datepicker/with-overrides.js
- src/datepicker/__tests__/stateful-calendar-overrides.scenario.js
- src/datepicker/styled-components.js
- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/select.js
Also fixed tabbing order in the datepicker popover with a quick select option.
> fix(datepicker): remove rounded corners, fix overrides example

- documentation-site/pages/blog/base-web-v7/index.mdx
This PR updates the blog post for `v7` to expose the new theme variables for customizing border radii. It includes the values needed to preserve the pre-`v7` corner styles.
> docs: update v7 blog post with new borderRadius theme variables

- src/dnd-list/list.js
Fixes scenarios where `onChange` is improperly called multiple times.
> fix(dnd-list): prevent default to avoid double removals

- documentation-site/pages/components/textarea.mdx
- documentation-site/static/examples/textarea/resizable.js
Resolves #1348 by showing docs example of a resizable textarea with restrictions.
> docs: resolve #1348 by including resizable textarea example

- documentation-site/static/examples/aspect-ratio-box/calendar.js
Remove padding from calendar example so it doesn’t wrap on mobile.
Before: ![calendar-before](https://user-images.githubusercontent.com/1285326/59798610-3be66400-927e-11e9-9fc9-21ef03b8b075.png)
After: ![calendar-after](https://user-images.githubusercontent.com/1285326/59798618-40ab1800-927e-11e9-8cbe-c1afb4216f00.png)
> docs(aspect-ratio-box): remove padding from calendar example

- src/popover/popover.js
- src/popover/types.js
- Resolves #1152 by supporting `popperOptions` on `Popover` component
- adds `popperOptions?: any` to types. Similar to how `Tether` is doing so.
- Extends current default options passed in.
> feat(popover): accepting popperOptions

- README.md
- documentation-site/components/markdown-elements.js
- documentation-site/pages/getting-started/installation.mdx
> docs: add TypeScript info, don't wrap code snippets

- src/datepicker/calendar.js
- Fixes #1141 
- `onMonthChange` will no longer set a highlighted date 👍
> fix: random day highlight onMonthChange for DatePicker

- package.json
- src/modal/__tests__/__snapshots__/modal.test.js.snap
- src/modal/__tests__/modal-select.scenario.js
- src/modal/__tests__/modal.e2e.js
- src/modal/focus-once.js
- src/modal/modal.js
- src/table/filter.js
- yarn.lock
This PR fixes a regression introduced in #1406 which was a new feature in v7.4.0.
You can see the bug in [this codepen](https://codesandbox.io/s/modal-select-bug-x9svk). Basically, you can't interact with the select dropdown using clicks when it is inside a modal.
The issue was that the library we use for focus trapping does not inherently respect react portals. It tests to see where the click event occurred, and if it is outside the container element it cancels the event. This is an issue with portals because the elements in the portal are not descendants of the container element.
The fix in this PR comes from swapping the `focus-trap-react` library out with a different one, `react-focus-lock`, which has built in support for portals.
There should be no noticeable change in the modal a11y …
> fix(modal): allow interaction with select (& other portals)

- package.json
- src/modal/__tests__/__snapshots__/modal.test.js.snap
- yarn.lock
In #1474 I introduced a new dependency, react-focus-lock. There is an issue on codesandbox where it cannot compile v2.0.0 of that library- v1.9.1 works so this PR downgrades to that version.
I opened an [issue](https://github.com/theKashey/react-focus-lock/issues/72) with the library to let them know.
Note, this fix is only to restore the codesandbox modal examples, which won't compile right now. Apps using 8.0.1 of baseui should not have any issues right now.
I'll need to release a new minor version after this PR to update the examples.
> fix: codesandbox modal examples

- documentation-site/components/blog.js
- documentation-site/pages/blog/base-web-v7/metadata.json
- documentation-site/pages/blog/base-web-v8/metadata.json
- documentation-site/pages/blog/getting-started-with-base-web/metadata.json
- documentation-site/pages/blog/getting-started-with-styletron/metadata.json
- documentation-site/pages/blog/phone-input/metadata.json
This PR adds some more meta tags to the head of our blog posts. The main change is that each post's cover image will be used for sharing previews.
The main goal is to have more control over what scrapers will choose to use for share previews on social networking sites ([Facebook](https://developers.facebook.com/tools/debug/sharing), [Linkedin](https://www.linkedin.com/post-inspector/inspect/), etc). [OGP](http://ogp.me/) meta tags are the main way to control this.
---
While researching this I found [an article](https://iamturns.com/open-graph-image-size/) recommending cover images be `1200w630h` for sharing purposes.
Another best practice is to define the image height and width attributes explicitly as `og:image:width` and `og:image:height` properties. It doesn't seem to affect the result …
> [WIP] feat(blog): add more metadata to blog posts

- src/phone-input/country-select.js
- src/phone-input/types.js
Fixes #1483 
This PR makes the Country Select in the Phone Input respect a top level `disabled` prop.
> fix(phone-input): add disabled property to country select

- documentation-site/static/examples/textarea/resizable.js
Fixes #1466 
The outer container aligns in both dimensions `height` and `width` with resizable textaera.
> fix(docs): update example for the resizable textarea with restrictions

- documentation-site/pages/blog/phone-input/index.mdx
This PR adds a small update to the phone input blog post. The post is currently misleading about filtering in the country dropdown. I forgot that we didn't have any designs around filtering so we cut it from the initial version of the component. I wanted to update the post so that folks aren't confused about whether or not the component currently supports it.
I also added a short section on using an IP address to optimize the UX.
> docs(blog): update commentary about phone input filtering

- src/phone-input/constants.js
- src/phone-input/country-select-dropdown.js
- src/phone-input/country-select.js
- src/phone-input/default-props.js
- src/phone-input/phone-input.js
- src/phone-input/stateful-phone-input-container.js
- src/phone-input/stateful-phone-input.js
- src/phone-input/styled-components.js
- src/phone-input/types.js
This PR reorganizes the flow types for the phone input a bit.
It _shouldn't_ be breaking even though I've made some properties required. I added defaults in defaultProps to make up for those but there may be some other issues I've overlooked.
After hooking up the disabled property in #1487, I noticed that the types were a bit messy and inconsistent with some patterns elsewhere. I also wanted to make the types a bit more explicit about which props were actually accepted and used.
Previously I was just spreading everything the phone input didn't use over the inner input element- but it feels better to be intentional about what is passed through and makes for better documentation. I don't think the phone input should just proxy every prop input accepts - that is what overrides are for.
> feat(phone-input): flow & prop enhancements

- src/button-group/button-group.js
does not apply corner styles if only one button is in group
> fix(button-group): handles one button in group

- documentation-site/components/example.js
Portal divs were not being cleaned up in codesandbox because the app was not wrapped in the new `BaseProvider` component. This issue only came up in codesandbox because we neglected to update that part of the code when the new context provider was created. Was interesting to track the issue down because we configured the scenarios and doc site correctly
> fix(docs-site): update example to include base provider

- src/codemods/__testfixtures__/styled-flowfixme-existing-generics.input.js
- src/codemods/__testfixtures__/styled-flowfixme-existing-generics.output.js
- src/codemods/__tests__/styled-flowfixme-test.js
- src/codemods/styled-flowfixme.js
v7 codemod now handles the case where `styled` call already has type annotations
> fix(codemod): update codemod to handle styled calls with existing generics

- src/select/__tests__/select.e2e.js
- src/select/dropdown.js
When the select menu is open and mounted, always highlight the first item initially. There is no reason to do filtering based on the input value because the options are naturally filtered so the first item should be highlighted.
This was causing a bug with multi select when on the second input, the menu was unfocused.
> fix(select): always highlight the first item initially

- src/phone-input/__tests__/phone-input-overrides.scenario.js
- src/phone-input/country-select.js
- src/phone-input/phone-input.js
This PR fixes a regression introduced in #1490. The issue was that some of the country select related overrides in the phone input were no longer working properly. This was because `overrides` was not being passed through to through to the `CountrySelect`. This is a one-line fix.
While playing around with overrides though, I noticed that nested overrides were not working correctly either. If you tried to pass nested overrides through `props` to `Input` and `CountrySelect`, they would overwrite (rather than deep merge with) all the built in overrides from the original source. I corrected the merging logic in this PR, but I had to add a couple `$FlowFixMe`s until we solve the underlying Flow issue with `mergeOverrides`.
In the interest of getting this patch out I think we should push that …
> fix(phone-input): fix country-select overrides and nested overrides

- src/styles/__tests__/styled.test.js
- src/styles/styled.js
Fixes #1535
Changed the type of `styled()`
> fix(types): fix styled() type so it can take a single string arg

- scripts/ts-copy.js
- src/datepicker/index.d.ts
- src/index.d.ts
- src/locale.ts
- src/overrides.ts
- src/pagination/index.d.ts
- src/rating/index.d.ts
- src/select/index.d.ts
- src/theme.ts
- replace all triple-slash directives `/// <reference path="...">` with ES modules, seems to be the preferred/modern way of composing typedefs, also it makes type dependencies explicit
- copy and publish these new `.ts` files (not only `.d.ts`) so it actually works
- tested with a 3rd party app
> fix(ts): fix overrides, theme and locale exports

- documentation-site/pages/components/select.mdx
- documentation-site/static/examples/select/open.js
- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/__tests__/select-open.scenario.js
- src/select/default-props.js
- src/select/select.js
- src/select/types.js
Fixes #744 
This PR adds an `openOnMount` prop to the `Select` component. If true, the dropdown will open upon mounting. By default the prop is `false`.
> feat(select): add startOpen property

- src/side-navigation/nav-item.js
```
<Navigation
items={nav}
activeItemId={location}
onChange={({ item }) => setLocation(item.itemId)}
overrides={{
NavItem: props => {
return <StyledNavItem {...props} />;
}
}}
/>
```
code above gives the error below
```
Warning: React does not recognize the `itemMemoizationComparator` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `itemmemoizationcomparator` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div (created by Context.Consumer)
in DevConsumer (created by ForwardRef)
in ForwardRef (created by Context.Consumer)
in StyledNavItem (created by NavItem)
in NavItem (created by NavItem)
in a (created by Context.Consumer)
in DevConsumer (created by ForwardRef)
in …
```
> fix(side-nav): removes memo fn from being passed to styled nav-item

- documentation-site/pages/components/select.mdx
Problem: <img width="622" alt="Screen Shot 2019-07-16 at 10 38 29 AM" src="https://user-images.githubusercontent.com/1939257/61316470-e4bcac00-a7b5-11e9-835b-5aaa119a17e3.png">
This PR fixes this by adding the path to the example in `select.mdx`.
> fix(docs): add path to select open example

- src/phone-input/country-select.js
Fix a flow type error where `inputRef` cannot be `null`.
> fix(phone-input): correct flow type for inputRef

- src/styles/styled.js
- src/table/styled-components.js
Previously these wrappers were not forwarding refs through to the 'actual' styled component. 
- I wanted to use `useWrapper` from `styletron-react`, but that util does not allow for style extensions ex. `withStyle(wrapped, {})`.
- This approach feels even hacky-er that it was already. Casting to any, then `StyletronComponent`. It signals to me that we should rethink the `useWrapper` helper maybe? or create a new utility for doing what we have here.
> fix(table): forward refs to wrapped table style components

- src/helpers/__tests__/responsive-helpers.test.js
- src/helpers/responsive-helpers.js
Javascript objects do not guarantee stable property order.  When generating media queries, the breakpoints could be referenced in the wrong order and the resulting media queries would apply to the wrong style values.
> fix(breakpoints): stable breakpoint keys

- documentation-site/components/code-icon.js
Currently, the doc site shows an error in dev mode, and says it expects `aira-hidden`
> fix(docs): use aria-hidden

- src/input/base-input.js
- src/input/styled-components.js
- Fix a bug where theme values are being applied to SVG rather than actual pixel values. This is a problem if someone brings their own SVG.
- Normalize clearable icon across select and input by removing alternate sizing, passing sharedProps
> fix(input): clearable icon sizing

- documentation-site/examples/radio/overrides.js
- documentation-site/examples/radio/overrides.tsx
This example isn't showing the radio button changing from blue to green (positive)
The current docs doesn't change color to `positive`:
It appears that `borderColor` isn't the right attribute to change. Changing `backgroundColor` give you this:
Regression likely caused by 59c8dc6819c3433e859d6b0960e88ca38e4bcab9
> docs(radio): change override of radio example to use backgroundColor

- src/input/__tests__/input-clearable.scenario.js
- src/input/__tests__/input.e2e.js
- src/input/__tests__/input.scenario.js
- src/input/base-input.js
- src/input/types.js
- src/textarea/__tests__/__snapshots__/stateful-textarea.test.js.snap
- src/textarea/__tests__/__snapshots__/textarea.test.js.snap
- src/textarea/__tests__/textarea.e2e.js
- src/textarea/__tests__/textarea.scenario.js
- src/textarea/textarea.js
Fixes #1643 
This PR updates `Input` and `Textarea` so that they create their own internal `inputRef`s rather than sharing a single instance via the static `defaultProps` property.
When a user clears an input, the last input on the page is cleared and focused.
The issue here is that every mounted `Input` is sharing the value returned by `React.createRef()` in `defaultProps`. This makes every instance of `Input` (that does not receive `inputRef`) point to the last `Input` rendered via `inputRef.current`.
```jsx
class Input extends React.Component {
defaultProps = {
inputRef: React.createRef(), // called once, reference shared between all Inputs
};
}
```
`clearable` relies on `this.props.inputRef` in order to manage focus and create the clear value event on the input element. When the …
> fix(input): clear and focus correct input when using clearable prop

- src/button-group/__tests__/button-group-overrides.scenario.js
- src/button-group/button-group.js
The overrides for ButtonGroup children were being spread in the BaseButton override rather than the top level override object. This PR adds a one line fix in addition to a visual regression test.
> fix(button-group): apply overrides to children correctly

- documentation-site/components/example.js
- documentation-site/examples/datepicker/nested-override.js
- documentation-site/examples/datepicker/nested-override.tsx
- documentation-site/examples/select/overriden-tag.js
- documentation-site/examples/select/overriden-tag.tsx
- documentation-site/pages/components/datepicker.mdx
- documentation-site/pages/components/select.mdx
- documentation-site/pages/theming/understanding-overrides.mdx
Updates the doc site to have a more robust explanation of nested overrides.
> docs: update nested overrides copy and example

- src/input/__tests__/__snapshots__/base-input.test.js.snap
- src/input/__tests__/__snapshots__/input.test.js.snap
- src/input/__tests__/__snapshots__/masked-input.test.js.snap
- src/input/styled-components.js
- src/textarea/__tests__/__snapshots__/textarea.test.js.snap
- Resolves #1576 
- Ensures `input` has no `margin` (was only being applied in Safari)
> fix: match input height cross browser

- packages/baseui-codemods/package.json
fixes
```
error An unexpected error occurred: "ENOENT: no such file or directory, symlink '../../dist/cli.js' -> '/Users/derekju/Library/Caches/Yarn/v4/npm-@uber-web-ui-baseui-codemods-1.0.8-db04d6eda3cf38934315cd8de10a3dddcfeeb8ba/node_modules/@uber-web-ui/baseui-codemods/.bin/@uber-web-ui/baseui-codemods'".
```
> fix(codemod): edit bin field

- src/input/base-input.js
Fixes #1662 
Adds `type="button"` to the password mask toggle button so that it does not erroneously fire inside of a `form` element.
> fix(button): password mask button should not fire form submit

- documentation-site/components/yard/yard.tsx
When hydrating the source code from the URL, it was not wrapped by try/catch so these steps killed the page:
- click in the onClick input
- select all
- type `}` (kills the page)
- try to refresh (the page is still dead)
Fix: set the source code but ignore AST parsing errors - let react-live deal with it and display the error.
> fix(yard): recover from bad URL source code

- screener.config.js
- src/progress-steps/__tests__/progress-steps-rtl.scenario.js
- src/progress-steps/styled-components.js
- src/styles/types.js
- src/theme.ts
- src/themes/creator.js
- Resolves #1682 
- Requires a new `string` key on `Theme` for `direction` in order to get around SSR issues and no `document` in scope.
> feat: rtl support progress steps

- documentation-site/pages/index.js
User logos are not visible on the documentation site when in dark mode:
Sets the `background-color` of the surrounding `<Block>` to `mono100` (white in light mode, gray in dark mode) and ensures proper padding around logos by setting `justify-items` to `center`.
> fix(docs): ensure user logos are visible in dark mode

- src/datepicker/__tests__/stateful-range-datepicker.scenario.js
- src/datepicker/stateful-datepicker.js
Fixes #1651
We handle setting the initial state value in the StatefulContainer component. It sets the value to an empty array in case of a range picker. This PR removes the default value override in the StatefulDatepicker and lets the stateful container take care of it.
> fix(datepicker): let stateful container to take care of the initial state value in stateful datepicker

- netlify.toml
netlify builds are timing out.. this will hopefully allow us to publish the site while we figure out a more sustainable fix
> fix(docs): removes storybook build

- component-sizes.json
- package.json
- scripts/component-sizes.js
- yarn.lock
* adds an option to trigger the bundle analyzer
* build the main component file, instead of the index, so webpack can treeshake it properly
> fix(bundle-size): update build script

- documentation-site/components/cheat-sheet.js
My assumption is that we will be able to see trends on which properties are being looked up most often and can make improvements to the main documentation site pages.
> feat(docs): adds ga events to cheat sheet

- documentation-site/pages/getting-started/versioning-policy.mdx
After discussing this with the team and stakeholders, I am on the fence of making the visual breaking changes stricter.
For now, I'd just change it a bit, so it enables us to do breaking changes in case a sweeping visual changes.
> docs(versioning): small update to visual changes

- documentation-site/components/table-of-contents.js
`Fixes #1, Fixes #2` 
In Base Web demo today, I noticed the whole page jumps when navigate between pages on the documentation site, for example: https://baseweb.design/getting-started/usage/ and https://baseweb.design/getting-started/learn/
This happened because the Table of Content component has unset width which grows and shrinks based on its children link. Setting the width to a fixed width would fix it. 160px was chosen because it's a reasonable width and it's based on the 8px grid used in designs. - Vietanh
> fix(docs): avoid page layout jumping when ToC changes

- package.json
```
prepublish: Run BEFORE the package is packed and published, as well as on local npm install without any arguments. (See below)
```
we do not this anymore, because install is handled by our buildkite job - previously it was in a separate buildkite job, that's why we had it
this will speed up builds because we won't do the babel builds twice
> fix(build): remove prepublish

- src/tag/__tests__/tag.test.js
- src/tag/tag.js
Fixes https://github.com/uber-web/baseui/issues/1788 
Added unit test for the change
Ran e2e tests in local mentioned in TESTING.md
If a Tag component is disabled, removing aria-label and role from it. If disabled Tag has close button then it should not have these attributes as well.
> fix(tag component): removing role and aria-label attrib if disabled

- src/styles/types.js
- src/theme.ts
Adds `scale750` to existing types, to reflect already existing theme variable.
> fix: add type annotation for scale750 in theme.sizing

- src/modal/styled-components.js
- src/styles/types.js
- src/theme.ts
- src/themes/creator.js
- src/themes/dark-theme-colors.js
Fixes #1809 
- add contrasting color for close button in modal
- handle case of light and dark theme
> fix(modal): add contrasting color for close button in modal

- component-sizes.json
- documentation-site/examples/phone-input/flag-overrides.js
- documentation-site/examples/phone-input/flag-overrides.tsx
- documentation-site/examples/phone-input/localized.js
- documentation-site/examples/phone-input/localized.tsx
- documentation-site/pages/components/phone-input.mdx
- src/phone-input/__tests__/country-select-dropdown.scenario.js
- src/phone-input/__tests__/phone-input.e2e.js
- src/phone-input/__tests__/phone-input.scenario.js
- src/phone-input/country-select-dropdown.js
- src/phone-input/country-select.js
- src/phone-input/flag.js
- src/phone-input/index.d.ts
- src/phone-input/index.js
- src/phone-input/phone-input.js
- src/phone-input/styled-components.js
- src/phone-input/types.js
- src/phone-input/utils.js
Replaces default flag svgs usage with emojis. It results in the phone-input size reduction from 136.17 KB to 10.79 KB.
> feat(phone-input): replace flag svg with emoji

- src/datepicker/calendar-header.js
- src/datepicker/styled-components.js
> fix(datepicker): make the calendar arrows larger

- documentation-site/pages/_app.js
I prefer to view doc site in light theme but my OS has dark mode set. Every time I load a page I have to toggle the theme to light because it detects my dark mode preference.
This change makes it so that if a theme preference is already set in localStorage we will use that instead of the OS preference. For folks visiting the first time it will use OS preference. After that it will use whatever they last used.
> docs: prioritize local storage for theme

- package.json
Clean build tests are failing locally because we don't build the doc site there
> fix(build): add doc site generation for tests

- src/tag/__tests__/__snapshots__/tag.test.js.snap
- src/tag/__tests__/utils.test.js
- src/tag/tag.js
- src/tag/types.js
- src/tag/utils.js
When `<Tag>` content is truncated, there's no means of seeing the complete text of the tag.
Updated the `<Tag>` component to add the text of the tag as an HTML `title` attribute so the full text is visible via a native OS tooltip on long hover. The `title` will only be added if each of the shallow children are a string or a number. The user must continue to specify their own `title` attribute for non trivial content.
> feat(tag): add title attribute when children is a string

- .storybook/load-stories.js
Add a dark background to dark mode storybook scenarios. It is a bit difficult to test dark mode components in storybook with a white background.
> feat(storybook): add dark background for dark mode

- src/avatar/__tests__/avatar.test.js
- src/avatar/avatar.js
Ad test: I was not able to get the final rendered state through enzyme's `wrapper.find()`, so at least testing the internal state values.
> fix(avatar): reset the error state when src is updated

- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/yard.tsx
- src/index.js
Added an effect that runs when the theme.name (context) is changed. It resets the theme editor so the initial values and imports are correct and user changes are discarded.
> fix(yard): fix theme switching (reset when changed)

- documentation-site/components/markdown-elements.js
Currently the generated documentation at https://baseweb.design appears to have only the default user-agent styles applied to most links ([example](https://baseweb.design/getting-started/setup/)) which make it hard to see the links when the dark theme is used. This change should have the effect of using the `<StyledLink>` from baseui instead of a plain `<a>` and should thus have the appropriate colors applied to it.
This should not require any version change since the change is only applied to the generated documentation styling.
> fix(docs): use styledlink in docs

- src/datepicker/__tests__/calendar-multi-month.scenario.js
we didn't have a date set for the datepicker, so every day, the screener test would fail, because it uses the current day as the default
like this one: https://github.com/uber-web/baseui/pull/1834
> test(datepicker): multi-month screener test

- documentation-site/examples/styled/basic.tsx
- documentation-site/examples/table/cells.tsx
- src/index.d.ts
Allow typescript to use custom theme types when using the `createTheme` and `styled` functions.
> fix(typescript): custom theme type support

- documentation-site/examples/input/focus.js
- documentation-site/examples/input/focus.tsx
Small fix to an example on input page which makes buttons and inputs look like they have incorrect sizing.
> docs(input): fix alignment in focus example

- documentation-site/components/gallery.js
Just a little tweak to the component gallery page to increase contrast on borders a bit. They were not being set explicitly before.
> docs(gallery): update borders for more contrast

- src/input/__tests__/__snapshots__/masked-input.test.js.snap
- src/input/__tests__/input-mask.scenario.js
- src/input/masked-input.js
The issue here was that `MaskedInput` had default props that overrides the `onFocus` for `Input`. `Input` then cannot set the focus state to true, and does not style the `InputContainer`.
There is no need for `MaskedInput` to duplicate `Input` default props so I removed the duplicates. 
I also added a visual regression test.
> fix(masked-input): fix focus styling

- documentation-site/pages/guides/understanding-overrides.mdx
removed the entire block because it seemed out of place while reading the page
> fix(docs): removes props override function

- documentation-site/pages/components/typography.mdx
Add exports to typography page and fix the heading example (was showing display again)
> docs(typography): add exports and fix heading example

- src/breadcrumbs/index.d.ts
The Breadcrumbs component was missing `List` property in its overrides interface.
> fix(breadcrumbs): add missing List override property

- src/data-table/measure-column-widths.js
strangely this bug only occurs in the docs site, not in the scenarios. that's why CI allowed prior diffs to land. to be honest i'm not sure what was causing the width dimensions to be missing in the docs site, but i've updated the code to only update the widths if a value is present
> fix(data-table): ensure width dim exists before setting

- documentation-site/components/yard/__tests__/ast.test.ts
- documentation-site/components/yard/__tests__/code-generator.test.ts
- documentation-site/components/yard/__tests__/utils.test.ts
- documentation-site/components/yard/ast.ts
- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/config/button-group.ts
- documentation-site/components/yard/config/tabs.ts
- documentation-site/components/yard/editor.tsx
- documentation-site/components/yard/index.tsx
- documentation-site/components/yard/knob.tsx
- documentation-site/components/yard/popup-error.tsx
- documentation-site/components/yard/types.ts
- documentation-site/components/yard/utils.ts
- documentation-site/components/yard/yard.tsx
- documentation-site/pages/components/tabs.mdx
- **added the Tabs component**
- `PropTypes.ReactNode` is now properly parsed and formatted (works great for nested components). There is no need inventing some complicated cross-reference mechanism at this point. Nested components can be just edited through the code (they usually don't have many options anyway).
- all knob textareas switched to the `Editor` component to get that nice highlighting
- better popup babel parse errors (LoC numbers were off)
- added an API for extra imports and supporting default imports as well
> feat(yard): add the Tabs component (nested components support)

- component-sizes.json
- flow-typed/npm/smoothscroll-polyfill_v0.x.x.js
- package.json
- src/menu/utils.js
- yarn.lock
Removes the smoothscroll-polyfill. It was never needed it in the first place because we did not specify the `Node.scrollIntoView` 'smooth' [behavior](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).
> feat(menu): removes smoothscroll-polyfill

- documentation-site/components/yard/__tests__/ast.test.ts
- documentation-site/components/yard/__tests__/code-generator.test.ts
- documentation-site/components/yard/actions.ts
- documentation-site/components/yard/ast.ts
- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/config/button-group.ts
- documentation-site/components/yard/config/button.ts
- documentation-site/components/yard/config/checkbox.ts
- documentation-site/components/yard/config/input.ts
- documentation-site/components/yard/config/tabs.ts
- documentation-site/components/yard/config/textarea.ts
- documentation-site/components/yard/editor.tsx
- documentation-site/components/yard/index.tsx
- documentation-site/components/yard/knob.tsx
- documentation-site/components/yard/knobs.tsx
- documentation-site/components/yard/override.tsx
- documentation-site/components/yard/overrides.tsx
- documentation-site/components/yard/reducer.ts
- documentation-site/components/yard/styled-components.tsx
- documentation-site/components/yard/types.ts
- documentation-site/components/yard/utils.ts
- documentation-site/components/yard/yard.tsx
- abstracting some code / removing repetition from the main file
- more comments
- `meta` config object is gone, all options are now on the same (first) level
- `extraImports` config option renamed to `importsConfig` to match `propsConfig` etc
- some internal renaming to better describe what is going on
- improving typescript types
- set theme values were not preserved when user typed into the rendered input (changing the internal state)
**I avoided further steps to decompose the whole project for OSS purposes.** Can be done in the future when we are happy with the overall functionality and have time (it will be a significant effort).
> feat(yard): cleaning up the code, config shape changes, better types

- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/config/radio.ts
- documentation-site/components/yard/editor.tsx
- documentation-site/components/yard/knob.tsx
- src/select/index.d.ts
- all knobs use compact inputs / compact select
- some tweaks of the editor sizing so it matches input when not focused
- fixed the editor cursor position bug in Chrome by adding `white-space: break-spaces`
- prettier's printWidth of the main code formatting lowered to 58 to prevent multi-line break
> feat(yard): better knob sizing, editor bug

- documentation-site/components/yard/__tests__/code-generator.test.ts
- documentation-site/components/yard/code-generator.ts
- documentation-site/components/yard/config/card.ts
- documentation-site/components/yard/config/side-nav.ts
- documentation-site/components/yard/knob.tsx
- documentation-site/pages/components/accordion.mdx
- documentation-site/pages/components/avatar.mdx
- documentation-site/pages/components/breadcrumbs.mdx
- documentation-site/pages/components/button-group.mdx
- documentation-site/pages/components/button.mdx
- documentation-site/pages/components/card.mdx
- documentation-site/pages/components/checkbox.mdx
- documentation-site/pages/components/file-uploader.mdx
- documentation-site/pages/components/form-control.mdx
- documentation-site/pages/components/input.mdx
- documentation-site/pages/components/pagination.mdx
- documentation-site/pages/components/phone-input.mdx
- documentation-site/pages/components/pin-code.mdx
- documentation-site/pages/components/progress-bar.mdx
- documentation-site/pages/components/radio.mdx
- documentation-site/pages/components/rating.mdx
- documentation-site/pages/components/side-nav.mdx
- documentation-site/pages/components/slider.mdx
- documentation-site/pages/components/spinner.mdx
- documentation-site/pages/components/tabs.mdx
- documentation-site/pages/components/textarea.mdx
- fixes side-nav `items` knob formatting
- `PropTypes.ReactNode` works for non-`children` cases, `children` treated as a snowflake
- assume that user never means to use a variable (identifier) as the knob value and translate it into string
It allows this
```
$
```
->
```jsx
<Input startEnhancer="$" />
```
vs previously
```
'$'
```
->
```jsx
<Input startEnhancer={"$"} />
```
where
```
$
```
would just throw a reference error.
- cleanup examples, remove unused imports, fix minHeights
> docs(yard): cleanup docs, more robust code generation

- src/themes/creator.js
Update Modal's close button to black per discussion with the design team.
Because the X icon is so thin, I followed the link colors for hover so there is enough contrast to be perceived. It is still pretty close colors but that's a more general system issue.
> fix(modal): update close button colors

- src/dnd-list/styled-components.js
A subtle bug. When you do dnd and move rapidly, the mouse gets ahead of the ghost item and starts triggering `:hover` effect of other items on the background. It doesn't look pretty. This fixes it.
> fix(dnd-list): prevent list hover being triggered when dragging

- vrt/ci.js
Just a little protection against recursive builds. The PR and commit messages for snapshot updates should prevent builds via `[skip ci]` but just in case this check will prevent anything running.
> fix(vrt): guard against recursive builds

- vrt/ci.js
Buildkite passes a `BUILDKITE_PULL_REQUEST_REPO=""` if the repo is owned by `uber`. I assumed it would always return the url so this fails the build without an additional check.
> fix(vrt): get owner logic

- package.json
- src/layer/__tests__/tether.test.js
- src/layer/tether.js
- yarn.lock
Applications using `baseui` reported errors coming from the `node_modules/baseui/.../tether` directory. The reason why this was not caught in this repo was that the `yarn.lock` file pinned `popper.js` version to `1.14.3` where applications were installing `1.16.0` which contained new flow type definitions.
> fix(tether): ensures no flow errors from tether

- documentation-site/pages/blog/responsive-web/index.mdx
`getMediaQuery` is not exported from the directory level, but only from a file in baseui
> docs(blog-post): removes getMediaQuery from responsive blog post

- documentation-site/components/survey.js
Currently, the survey can show up on each pages, because the cookie is placed on the context on the path of the currently viewed component
> docs(survey): fix cookie path

- src/modal/types.js
The property definition collided with `children` implicitly defined on [override component types](https://github.com/uber/baseweb/blob/master/src/helpers/overrides.js#L29).
> fix(modal): removes children type from shared style props

- documentation-site/components/yard/yard.tsx
- package.json
- yarn.lock
With the addition of a [new button](https://github.com/uber/baseweb/pull/2263), the space really got limited. This PR changes the 3 edit buttons to icons
> docs(yard): add icons for actions

- vrt/ci.js
When a new PR is opened with updated snapshots, our bot posts a comment to the original PR, with a link to the snapshot PR.
There was a small regression introduced a week ago where the comment did not properly link to the snapshot PR, instead printing out the issue number of the PR.
This PR fixes the issue by properly passing the snapshot PR url rather than the snapshot PR issue number to the function that handles this logic.
> fix(vrt): link to snapshot pr url in bot comments

- src/menu/stateful-container.js
Fixes #2215 
Borrowed the idea from react-select. We want to ignore the keydown on Enter from IME.
https://github.com/JedWatson/react-select/blob/e12b42b0e7598ec4a96a1a6480e0b2b4c7dc03e3/packages/react-select/src/Select.js#L1209
> [Select] Ignore keyevent Enter from IME

- documentation-site/examples/select/with-many-options.js
- documentation-site/examples/select/with-many-options.tsx
- Use `box-sizing: border-box` so list items fit in list. Also avoid `item="[object Object]" overrides="[object Object]"` from appearing in DOM.
Before:
After:
- Avoid mis-sized lists by resizing the height based on the number of children. E.g. try searching for `1111` and see the list height resize now.
Before:
After:
> docs(select): fix virtualized example

- documentation-site/components/yard/utils.ts
When you go to the button component and edit the code, radio buttons as KIND and SIZE get empty, since the `defaultValue` is not preserved. This PR fixes it.
> docs(yard): preserve defaultValue when value is undefined

- documentation-site/components/yard/config/checkbox.ts
As it turns out, the component worked fine - it's just the default value that works differently for different types of checkboxes. Note the difference between the following images:
and
The issue was, that the default is different for the different checkbox types, so we always have to add it to the source code to make the examples work.
> docs(checkbox): remove default value for placement

- documentation-site/examples/layout-grid/skip-shrink.js
- documentation-site/examples/layout-grid/skip-shrink.tsx
- documentation-site/pages/components/layout-grid.mdx
Just some tweaks to the example copy and a fix for the shrink example, which did not match description.
> docs(layout-grid): edit copy and fix shrink example

- documentation-site/components/header-navigation.js
- documentation-site/components/help.js
- documentation-site/components/layout.js
- documentation-site/components/posts.js
- documentation-site/components/search.js
- documentation-site/components/survey.js
- documentation-site/components/walkthrough.js
- documentation-site/components/yard/knobs.tsx
- documentation-site/components/yard/override.tsx
- documentation-site/components/yard/theme-editor.tsx
- documentation-site/pages/_app.js
- documentation-site/pages/blog/responsive-web/index.mdx
- documentation-site/pages/components/block.mdx
- documentation-site/pages/index.js
- src/styles/types.js
- src/theme.ts
- src/themes/creator.js
* Add mediaQuery object to theme based on breakpoints
* Update docs to use mediaQuery instead of media
* Follow mobile-first pattern in docs when possible
* Fix Block documentation which said there was a media query for below the first breakpoint
> feat(media-query): add mediaQuery object to theme and update docs

- package.json
- scripts/bundle-size/.gitignore
- scripts/bundle-size/bundle-size.js
- scripts/bundle-size/webpack.config.js
- yarn.lock
This is the first step to improve our understanding of the base web bundle
```
./scripts/bundle-size/bundle-size.js -c input -e Input
```
```
./scripts/bundle-size/bundle-size.js -c input -e Input -a
```
> chore(bundle): add better support for checking each component size

- documentation-site/pages/components/layout-grid.mdx
- src/layout-grid/styled-components.js
- src/styles/types.js
- src/theme.ts
- src/themes/creator.js
This updates the layout-grid module to use theme values for default grid values. This requires some new properties on the theme object.
Also added a bit of clarity in docs around "responsive" props.
> feat(theme): add default grid values

- src/datepicker/types.js
`Fix`
The `mask` property within `Datepicker` should be able to take in the argument of `null`. When doing so flow gives an error, only allowing `mask` to take in strings. 
Added null type into mask property arguments.
> fix(datepicker): mask argument accepts null

- src/accordion/panel.js
- src/tabs/tab.js
[Tabs](https://baseweb.design/components/tabs/) and [Accordion](https://baseweb.design/components/accordion/) components makes the scroll jump when navigating using Space key. This is really annoying for accessibility.
The fix is really easy, just need to `e.preventDefault()` the event when it's triggered via space key.
> fix(tabs): space key a11y on Tabs and Accordion component.

- package.json
- yarn.lock
this is just a cosmetic bump since technically v1 should not be used bc of the ownership transfer
> chore: update react-view dep

- package.json
Parcel looks to ignore the absolute path.
The `package.json` included in subfolder has a relative path on `module` field. Parcel ignores the absolute path on the main `package.json` for `import { LightTheme, DarkTheme, BaseProvider } from "baseui"`. It leads the bundle to include two different ThemeProvider files breaking theming for example.
> fix(package): update module field to relative path

- src/icon/styled-components.js
Allow icons to use colors from theme. Seems fair since we do the same with size.
> feat(icon): allow icons to use colors from theme

- src/typography/index.d.ts
- src/typography/index.js
This PR updates the typography component names to match the Base design system typography names, making it easier for engineers to find the typography component that matches the text styles found in Figma.
The existing names are moved to aliases to keep backward compatibility.
> feat(typography): rename components to match Base typography style names

- documentation-site/examples/popover/ref-handling.js
Single word typo in popover/ref-handling.js:  'Chackbox' -> 'Checkbox'
> docs(popover): fix typo in ref-handling description

- documentation-site/components/yard/config/select.ts
Update select placeholders with working examples and remove unnecessary spaces
Before: 
After:
> docs(select): update select placeholders with working examples

- src/select/__tests__/select.e2e.js
- src/select/select-component.js
Use quotation marks instead of straight quotes for creatable options.
See https://practicaltypography.com/straight-and-curly-quotes.html
> fix(select): use quotation marks for creatable options

- src/select/__tests__/dropdown.test.js
- src/select/dropdown.js
Merge StatefulMenu overrides instead of replacing. This fixes the issue of getOptionLabel not working when you try overriding the StatefulMenu’s EmptyState.
> fix(select): merge StatefulMenu overrides

- documentation-site/pages/getting-started/setup.mdx
I noticed that the text read:
> **an** example declaration**s**
So I thought I'll just fix it (can't use `an` and plural)
> docs(setup): fix styletron section

- src/datepicker/calendar-header.js
- src/datepicker/calendar.js
- src/datepicker/datepicker.js
- src/datepicker/types.js
When clicking the popover which contains `calendar-header` in the datepicker, `onClickOutside` in the popover that contains the `calendar` is called. This is because the calendar-header is not rendered _in_ the parent popover, but in a separate node. The closing of the parent popover is prevented with a hack, that checks if the `role` of the clicked element is "option". However, if the scroll bar is clicked, the `menu`-element is the target, and the component closes(even though the user wanted to scroll). 
This PR renders calender-header popover as a child of the popover that renders the calendar, so that clicking calendar-header is not considered "outside" of the calendar.
> fix(datepicker): clicking scroll in month selection closes datepicker

- documentation-site/examples/radio/basic.tsx
- documentation-site/examples/radio/error.tsx
- documentation-site/examples/radio/horizontal-align.tsx
- documentation-site/examples/radio/overrides.tsx
- src/radio/index.d.ts
Fixes #2469 
Update the onChange props typescript definition all radio components (Radio, RadioGroup, StatefulRadioGroup & StatefulContainer)
from `onChange?: React.FormEventHandler<HTMLInputElement>;`
to `onChange?: React.ChangeEventHandler<HTMLInputElement>;`
This removes the need to cast the event's target as a "HTMLInputElement"  inside the onChange callback
> fix(radio): radio's onChange prop typescript definition

- src/table/styled-components.js
This hides the horizontal scrollbar when content doesn't require it by default.
> Change StyledTable overflowX to 'auto'

- src/modal/__tests__/modal.test.js
- src/modal/modal.js
Resolves https://github.com/uber/baseweb/issues/2435
When closing nested modals simultaneously (e.g. press ESC), the bottom one can unmount before the top one. This causes the top modal to reset the mountNode's overflow to 'hidden', which locks scrolling.
The flow goes like this:
1. Bottom modal mounts, caches last overflow as '', and sets overflow to 'hidden'
2. Top modal mounts, caches last overflow as 'hidden', and sets overflow to 'hidden'
3. Bottom modal unmounts and resets overflow to ''
4. Top modal unmounts and resets overflow to 'hidden'
This change bails out of resetting overflow if it's changed since the modal mounted.
So now the flow would be:
1. Bottom modal mounts, caches last overflow as '', and sets overflow to 'hidden'
2. Top modal mounts, caches last overflow as …
> fix(modal): handle nested modal overflow reset

- documentation-site/components/sidebar.js
Fix sidebar links, which were unnecessarily nested inside Labels and had href attributes on divs. Now, cmd+click will properly open link in a new tab.
Before: 
After:
> docs(sidebar): fix sidebar links

- documentation-site/components/yard/config/datepicker.ts
- src/datepicker/calendar.js
- src/datepicker/index.d.ts
- src/datepicker/types.js
Allow for endDate in quickSelectOptions, so user can build custom ranges.
> feat(datepicker): allow for endDate in quickSelectOptions

- documentation-site/pages/components/datepicker.mdx
Rename Datepicker basic usage example to avoid React warning:
```
Warning: Encountered two children with the same key, `Datepicker`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
> fix(docs): rename Datepicker basic usage example

- documentation-site/components/yard/props-tooltip.tsx
Avoid React warning:
```
Warning: React does not recognize the `typeDefinition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `typedefinition` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
> chore(yard): avoid React warning

- documentation-site/components/yard/config/button-group.ts
There are missing theme color keys for button group component
> docs(button-group): add relevant theme keys

- documentation-site/components/sidebar.js
Second attempt at #2489, this time keeping Link from 'next/link'.
Clean up sidebar links, which were unnecessarily nested inside Labels and had href attributes on divs. Now, cmd+click will properly open link in a new tab.
Before: 
After:
> docs(sidebar): clean up sidebar links

- documentation-site/components/sidebar.js
Fix an error being thrown when `href` is not provided to `Link`.
Solution: only use `Link` if an `href` is provided, otherwise use `StyledNavLink`.
> docs(sidebar): fix link missing href

- documentation-site/examples/spinner/next-custom.js
- documentation-site/examples/spinner/next-custom.tsx
- documentation-site/pages/components/spinner.mdx
update docs for `spinner` to use `withStyle` rather than `$style`
> docs(spinner): update example to use withstyle rather than $style

- documentation-site/pages/components/select.mdx
there was no mention of the importance of having id and label properties in options array objects. the document does not explain the utalization of labelKey and valueKey.
Left a not on the documentation to stress it out.
> docs(select): stress importance of id and label as default properties

- src/toast/index.d.ts
Adds InnerContainer props to overrides for Notification.
Fixes type error for notification component in override props for InnerContainer
> fix(toast): adds override props InnerContainer to the typescript def

- src/card/styled-components.js
- src/table-semantic/styled-components.js
Update Card Root to follow BorderT pattern so it can be overridden with theme values without Styletron warnings. Also fix Table Semantic StyledTableHeadCell, which could potentially break since JS Object order is not guaranteed.
> chore(border): update Card Root to follow BorderT pattern

- documentation-site/pages/_document.js
seems to be a simple fix - tested on some different browsers to make sure it caches properly.
> docs: fix font flash on initial page loads

- src/flex-grid/__tests__/__snapshots__/flex-grid-item.test.js.snap
- src/flex-grid/__tests__/__snapshots__/flex-grid.test.js.snap
- src/flex-grid/__tests__/flex-grid-item.test.js
- src/flex-grid/flex-grid-item.js
- src/flex-grid/flex-grid.js
- src/flex-grid/index.d.ts
- src/flex-grid/types.js
Re-implement FlexGridItem to avoid nth-child selectors. Original implementation relied on the order of rules in the stylesheet, which is not guaranteed with Styletron, sometimes causing layout bugs if rules are out of order.
By passing the index and count props to each FlexGridItem, we can explicitly set margin-right and margin-bottom without relying on nth-child selectors. This also cleans up the DOM and reduces the number of classes:
FlexGridItem classes before: 
FlexGridItem classes after:
> fix(flex-grid): re-implement FlexGridItem to avoid nth-child selectors

- documentation-site/components/gallery.js
- documentation-site/components/thumbs/index.js
Just a small update to gallery page to match nav structure. `Tables` is its own thing now.
> docs(gallery): update to match tables sections

- src/select/select.js
[`React.ElementConfig<T>`](https://flow.org/en/docs/react/types/#toc-react-elementconfig) gets the type of a component’s props but preserves the optionality of `defaultProps`. It is thus more accurate than simply using `$Shape<TProps>`.
> fix(select): more accurate prop type for Select component

- src/tag/index.d.ts
The tag component was missing type for the title prop. This fixes that.
> fix(tag): update tag types

- documentation-site/components/yard/theme-editor.tsx
- documentation-site/pages/blog/base-web-v7/index.mdx
- documentation-site/pages/blog/getting-started-with-base-web/index.mdx
- documentation-site/pages/blog/responsive-web/index.mdx
- documentation-site/pages/components/base-provider.mdx
- documentation-site/pages/components/input.mdx
- documentation-site/pages/components/layout-grid.mdx
- documentation-site/pages/components/styled.mdx
- documentation-site/pages/components/typography.mdx
- documentation-site/pages/components/use-styletron.mdx
- documentation-site/pages/guides/understanding-overrides.mdx
Noticed some links on site point to older sections on theming guide. Did a sweep to update the anchor tags to the current page sections.
> docs(theming): update anchor links that point to theming guide

- documentation-site/components/yard/config/tooltip.ts
Currently the default `triggerType` for Tooltip `click`. Although, it is not possible to interact with the component in a clickable manner. This PR changes the `triggerType` to `hover`, which should be a more suitable default, and fix the issue.
Example:
> docs(tooltip): change default triggerType to hover

- src/avatar/__tests__/avatar.test.js
- src/avatar/avatar.js
When the avatar's `src` is updated from a valid source to a null-ish value (undefined, null), the `onError` callback will not be triggered and the `noImageAvailable` flag will still be false, thus the Avatar will display broken image.
Here is the [sandbox to reproduce the issue](https://codesandbox.io/s/avatar-xeqg4).
> fix(avatar): reset to error state when src is missing

- src/select/select-component.js
We are currently able to modify the `SelectArrow` svg through overrides, however we cannot currently override the `ClearIcon` with the same API
With this we can modify the `SelectArrow` and `ClearIcon` with the same API
> fix(select): allow clear icon svg overrides

- src/select/select-component.js
1. Place select in overlay
2. Open menu
3. Close overlay by clicking outside of overlay
4. Select will try to update its state which causes the warning and memory leak
Fix contains changes in onBlur handler. Now there is a condition check whether component is still mounted in a dom before performing setState.
#2623
> fix(select): don't perform setState on unmounted component

- documentation-site/examples/dnd-list/overrides_whole_subcomponent.tsx
- documentation-site/examples/input/with-tags.js
- documentation-site/examples/input/with-tags.tsx
- documentation-site/examples/pagination/overrides.tsx
- src/overrides.ts
Fixes #2591
- Add forward ref to the example
- Update the overrides component type to accept ForwardRef hoc
> fix(docs): add forward ref on input tag + update overrides ts types

- documentation-site/components/yard/config/popover.ts
- documentation-site/components/yard/config/tooltip.ts
- documentation-site/pages/components/popover.mdx
- src/datepicker/calendar-header.js
- src/datepicker/datepicker.js
- src/menu/__tests__/menu.e2e.js
- src/menu/maybe-child-menu.js
- src/phone-input/country-select.js
- src/phone-input/default-props.js
- src/popover/__tests__/__snapshots__/popover.test.js.snap
- src/popover/__tests__/__snapshots__/stateful-popover.test.js.snap
- src/popover/__tests__/popover.test.js
- src/popover/default-props.js
- src/popover/popover.js
- src/popover/types.js
- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/select-component.js
- src/tooltip/__tests__/__snapshots__/stateful-tooltip.test.js.snap
- src/tooltip/default-props.js
Fixes #2633 
Added props to popover
focusLock?:  boolean = true - whether to render with FocusLock or not (required for components that use popover but don't expect to be focus locked)
autoFocus?:  boolean = true - whether to autofocus first focusable element within content
returnFocus?: boolean = true - whether to return focus to original element after closing popover
implemented using FocusLock component similar to Drawer
returnFocus needs to be set to `false` if focusing the original element opens the popover in the first place or the popover will open again on close. (i.e. DatePicker)
set `noFocusGuard={true}` prop on FocusLock since it violates a11y rule elements should not have tabindex greater than 0 (e.g. https://dequeuniversity.com/rules/axe/3.2/tabindex)
updated some snapshots …
> feat(popover): add autoFocus and returnFocus

- documentation-site/components/header-navigation.js
Fixes weird outline when Hamburger menu icon is focused on mobile
Before
After
> docs(header-navigation): fix weird padding in burger menu button

- src/menu/option-list.js
- src/menu/styled-components.js
- src/menu/types.js
Fixes #2555 
Add an optional href to menu item. 
When href is provided to a menu item, an anchor tag is rendered within the `li` with href as the link and target as `_blank`.
> feat: add href support to menu item

- src/tree-view/tree-label.js
- src/tree-view/types.js
Fixes #2720 
NOTE: this branch is based off of https://github.com/uber/baseweb/pull/2716
I didn't want to add these changes to the main PR so I'm just putting this here for now.
simply add $isExpanded and $hasChildren styling props to the styled-components inside TreeLabel (i.e. TreeItemContent, ExpandIcon, CollapseIcon, IconContainer).
> fix(tree-view): add $isExpanded and $hasChildren styling props

- scripts/link-checker.js
Removes `fork` from `master` deployment url.
> fix(ci): link checker url typo

- documentation-site/pages/index.js
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
> chore(docs): migrate from deprecated github api param

- src/pin-code/default-props.js
- src/pin-code/pin-code.js
- src/pin-code/types.js
Some developers were confused that `autoComplete` was not included even though it was shown on the docs site. This was due to re-using props from the `Input` component.
> feat(pin-code): add autoComplete prop

- proposals/skeleton.md
This is a proposal for adding a skeleton component for representing loading states to Base Web. It also offers a neat way of dealing with loading states in tests written with React Testing Library.
> docs(skeleton): add proposal

- documentation-site/pages/_document.js
We have to set the `recurringPeriod` to make sure we can resurvey folks (https://delighted.com/docs/api/web)
This doesn't mean we'll show this all the time - the project-level throttling settings are always considered:
> docs(delighted): make the csat survey recurring

- CONTRIBUTING.md
fixes: https://github.com/uber/baseweb/issues/1866
This check uses a package called `commitlint` and it does not provide the ability to customize the error message if your commit is improperly formatted. This pr adds some extra documentation to the contributions page so that new contributors will at least be aware of it.
> chore(docs): add documentation on commit message format

- documentation-site/examples/menu/href.js
- documentation-site/examples/menu/href.tsx
- documentation-site/pages/components/menu.mdx
Update example to show Menu handles the key "href" in items.
Possible related to ticket:
https://github.com/uber/baseweb/pull/2631
N/A
> docs(menu): update example for menu with href,

- scripts/link-checker.js
Would be awesome if they documented how they generate URLs in case their API doesn't return deployment. This is what I'm seeing though:
```
"/" -> "-"
"-" -> "-"
"_" -> ""
"#" -> ""
```
> fix(link-checker): update sanitization

- documentation-site/examples/input/with-tags.js
- documentation-site/examples/input/with-tags.tsx
Fixes #2752
I added a placeholder depending on the tags state in the input
Something like the code sandbox in the issue
**New Changes**
**When there are tags**
N/A
**Note**: this small contribution taught me a lot about how your code is structured and how the workflow is going so I am looking forward to contributing more whenever I'm free :nerd_face:
> docs(input): add placeholder to input tags example

- src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.js.snap
- src/breadcrumbs/__tests__/breadcrumbs.test.js
- src/breadcrumbs/breadcrumbs.js
The `<Breadcrumbs />` component iterates over `children` to insert separators. It seems intuitive to ignore children that are `null`, `true`, or `false` in order to allow some of the idiomatic conditional rendering patterns in React.
Given this example:
```jsx
<Breadcrumbs>
<span>foo</span>
{false && <span>bar</span>}
<span>qux</span>
</Breadcrumbs>
```
I would expect it to render `foo > qux`. However, it renders `foo > > qux`.
This is potentially a breaking change, but I would be suprised if anybody relied on the seemingly unintuitive behaviour to render empty breadcrumb items. Rendering empty items is still possible by using an empty string.
> fix(breadcrumbs): ignore null, true, and false

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
- packages/eslint-plugin-baseui/src/messages.js
This PR updates the `deprecated-component-api` rule in `eslint-plugin-baseui` with some improved logic around importing. This should lead to fewer false positives and, in a few edge cases, fewer false negatives.
---
All rules check to see if the relevant component is imported from `baseui`. So this works now:
```js
// ✅
import {Spinner} from "./spinner.js"
export default () => <Spinner />
```
There are also some improvements around respecting local import aliases. This means the following is now okay:
```js
// ✅
import {StyledSpinnerNext as Spinner} from "baseui/spinner"
export default () => <Spinner />
```
But not this:
```js
// 🚫
import {Spinner as BaseSpinner} from "baseui/spinner"
export default () => <BaseSpinner />
```
The other warnings related to props and overrides check that the …
> feat(eslint-plugin-baseui): improve deprecated-component-api importing logic

- scripts/flow-copy-src.js
Babel does not support maintaining comment position thus leading to unsuppressed flow errors being included in published `.js.flow` files. This change removes any empty lines which will continue suppress flow errors as defined in the source code. This [astexplorer scenario](https://astexplorer.net/#/gist/9b9b721ec08d6e3e7f1440d6a548cf86/d21fd9270463c6311b17a0918f6e90cd98d8795c) reproduces the issue.
> fix(flow): maintain suppression comment position

- src/tabs/index.js
related to https://github.com/uber/baseweb/pull/2497
> fix(build): exclude tabs types from esm target

- src/checkbox/checkbox.js
- src/checkbox/index.d.ts
- src/checkbox/types.js
- src/form-control/__tests__/form-control.test.js
- src/form-control/form-control.js
- src/form-control/index.d.ts
- src/form-control/types.js
- src/input/__tests__/__snapshots__/base-input.test.js.snap
- src/input/__tests__/__snapshots__/input.test.js.snap
- src/input/__tests__/__snapshots__/masked-input.test.js.snap
- src/input/base-input.js
- src/input/types.js
- src/radio/index.d.ts
- src/radio/radiogroup.js
- src/radio/types.js
- src/select/__tests__/__snapshots__/select.test.js.snap
- src/select/default-props.js
- src/select/index.d.ts
- src/select/select-component.js
- src/select/types.js
- src/textarea/__tests__/__snapshots__/textarea.test.js.snap
- adds the `aria-checked` value `mixed` when the checkbox is `indeterminate`.
- applies a `bui` id to the caption element on `form-control`
- if `form-control` has an error, it will send the caption id as `aria-errormessage`
- if `form-control` has a caption, it will send the caption id as `aria-describedby`
- adds `aria-errormessage` prop to `input`
> fix(checkbox): applies screen-reader improvements

- documentation-site/pages/discover-more/roadmap.mdx
- removed the monolithic engine too since it's technically done (and even published), just going through a lengthy review process
> docs: update the roadmap

- src/input/__tests__/input.e2e.js
- src/input/base-input.js
- src/input/styled-components.js
- src/input/types.js
This PR makes the Clear Icon keyboard navigable and interactive. You can activate the clear by focusing the icon button and pressing Enter or Space. The focus indicator uses our standard visibility checks.
> feat(input):  make "clear input" keyboard interactive

- documentation-site/examples/input/focus.js
- documentation-site/examples/input/focus.tsx
- documentation-site/examples/layer/basic-tether.js
- documentation-site/examples/layer/basic.js
You need to use `React.useRef` instead of `React.createRef` in functional components; otherwise, it will return a new reference with each render and that was making the input focus example unreliable.
Also checked the rest of examples and found some unused instances of createRef (also it should never go outside of the component).
> docs: fix some ref examples

- packages/eslint-plugin-baseui/__tests__/deprecated-theme-api-test.js
- packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Cover the case in the eslint plugin, when the user has a variable that's not initialized when declared
> test(eslint-plugin): cover vars without init

- documentation-site/examples/modal/buried-interactive-element.js
- documentation-site/examples/modal/buried-interactive-element.tsx
- src/modal/__tests__/__snapshots__/modal.test.js.snap
- src/modal/__tests__/modal-select.scenario.js
- src/modal/__tests__/modal.e2e.js
- src/modal/__tests__/modal.test.js
- src/modal/modal.js
Handling modal closure on a backdrop click through the Layer's `onDocumentClick` handler solves the issue when multiple layers rendered on top of a modal layer and a backdrop click removes all those layers instead of handling only the top-most layer's handlers.
An example here is a modal that renders a select component. When the select's dropdown is open a click on the backdrop (that is also outside of the select dropdown click) will only close the select's dropdown and the modal will remain open.
> feat(modal): handle modal closure through the Layer's onDocumentClick handler

- src/button/button.js
Originally I was going to update the Popover "hover" trigger to also
trigger on focus events. Reading through our docs, I noticed that we
already have this feature (under the Accessibility section). Sure
enough, we already pass through the focus events to the anchor (or
wrapping span).
The issue is that Button overwrites any `onFocus` and `onBlur` handlers
passed as top level props. It respects overrides for those props but
technically people can pass `onFocus` and `onBlur` as top level props
so this commit updates the handlers to restore that option.
> fix(button): respect focus handler props

- documentation-site/components/yard/config/tree-view.ts
- documentation-site/examples/tree-view/basic.js
- documentation-site/examples/tree-view/basic.tsx
- documentation-site/examples/tree-view/custom-label.js
- documentation-site/examples/tree-view/custom-label.tsx
- documentation-site/examples/tree-view/label-overrides.js
- documentation-site/examples/tree-view/label-overrides.tsx
- documentation-site/examples/tree-view/overrides.js
- documentation-site/examples/tree-view/overrides.tsx
- documentation-site/examples/tree-view/single-expanded.js
- documentation-site/examples/tree-view/single-expanded.tsx
- documentation-site/examples/tree-view/uncontrolled.js
- documentation-site/examples/tree-view/uncontrolled.tsx
- documentation-site/pages/components/tree-view.mdx
- scripts/component-sizes.js
- src/tree-view/__tests__/tree-view-render-all.scenario.js
- src/tree-view/__tests__/tree-view-single-expanded.scenario.js
- src/tree-view/__tests__/tree-view.scenario.js
- src/tree-view/index.d.ts
- src/tree-view/index.js
- Makes the tree view stable.
- Addresses the issue where the TreeView yard example shifts when expanding and collapsing by using a long title on the first item to keep it centered in place.
> feat(tree-view): makes tree-view stable

- src/theme.ts
The typography definitions only had primitives and the eslint plugin deprecated-theme-api would try and fix them to the new API which aren't in the definitions. This syncs up the typography definition with the current flow types.
> fix(typescript): Fix Typography definitions

- src/table-semantic/styled-components.js
- src/table-semantic/table-builder.js
- sortable header has the button role so I added `Enter` and `Space` key handler for activation (an important a11y rule)
- applied nicer focus styles instead of the default outline
- it now announces if the column is sorted + how through the aria-label
> fix(table-semantic): screen-reader fixes and nicer focus

- src/data-table/__tests__/column-numerical.test.js
- src/data-table/__tests__/data-table-columns.e2e.js
- src/data-table/column-numerical.js
All other columns would initial sort in ascending order. Numerical should do the same
> fix(data-table): makes initial sort always ascending

- src/index.js
Adds the `withWrapper` styling util to the base level import path.
> feat(styles): add withWrapper to base module

- .buildkite/pipeline.yml
- scripts/deploy-docs.sh
- scripts/deploy-npm.sh
- scripts/deploy-vscode.sh
In the current deploy step, we've been doing quite a lot
- deploy baseui and the eslint plugin
- deploy the docs to netlify
- deploy the docs to zeit on tag creation
- deploy the vscode extension
If any of these steps failed, the next step failed too. This change makes sure that the jobs are independent of each other.
> chore(build): split deploy steps

- documentation-site/components/theming/breakpoints.js
Documentation site's 'Theming' page provides misleading information regarding `mediaQuery` property usage. This pull request makes `Breakpoint` component to respect `media` prop when passing concern prop to `Property` component, therefore fixes the bug.
> docs(theming): respect media prop

- src/input/index.d.ts
Adds `inputMode` prop to `Input` component — exists in `types.js` but is missing in `index.d.ts`
> fix(input): adds inputMode to props in typescript

- .buildkite/pipeline.yml
- deploy-docs.sh
- deploy-npm.sh
- deploy-vscode.sh
currently, there is no simple way in buildkite to change the current working directory for scripts that are run - because we are running quite a few different binaries from these scripts files, it's quite easy to mix things up
because of these downsides, I am moving back the deploy scripts to the root of the project
> fix(deploy): move deploy scripts back to the root

- deploy-docs.sh
Previously we used account-wide API Keys, instead of the more limited API Tokens
> fix(cf): use bearer token

- src/menu/stateful-container.js
Addresses initial concern here: https://github.com/uber/baseweb/issues/2980, but does not resolve broader issue.
This `setState` call was being used to set the `activeDescendantId`, given the case where `highlightedIndex` is initially provided. This is probably an edge case we don't need to worry about in exchange for resolving the react error
> fix(menu): avoid react error, state update in render

- src/datepicker/__tests__/datepicker.e2e.js
- src/datepicker/calendar-header.js
Due to how NVDA and this dropdown menu both respond to up/down arrow keys, navigation was not possible. Removes a 'tab away' test since focus is now locked
> fix(datepicker): nvda can navigate month dropdown

- src/popover/popover.js
Popover should always apply appropriate aria attributes to anchor
> fix(popover): always apply appropriate aria-attrs

- e2e/storybook/config.js
e2e/config.js is re-invoked with every update, so this was yielding a brand new styletron instance for every update, which would sometimes yield broken styles from order dependency of rendering.
https://github.com/storybookjs/storybook/issues/1417
> fix(storybook): broken styles in storybook after HMR

- src/datepicker/index.js
- src/tabs/index.js
- src/themes/index.js
- src/timepicker/index.js
- src/tooltip/index.js
Remove type definition from esm target.
Follow up work of https://github.com/uber/baseweb/pull/2497.
It fixes the following error:
> fix(build): remove type definition from esm target

- src/timepicker/timepicker.js
In previous versions, the backspace did nothing once a value is selected. This PR restores that behavior.
Why now? A recent PR caused the timepicker to throw an error if the user pressed the backspace
> fix(timepicker): do not remove on backspace

- documentation-site/pages/components/index.mdx
Currently there is no title set in Components page as seen below:
This pull request adds a heading to components page's template and therefore sets title.
> docs(components): add title

- src/select/select-component.js
Fixes #3066
Styling for ClearIcon from Select component can be overridden.
> fix: properly override clearicon styles and props

- documentation-site/examples/spinner/next-span.js
- documentation-site/examples/spinner/next-span.tsx
- documentation-site/pages/components/spinner.mdx
- src/spinner/styled-components.js
Adds a new example to the `Spinner` docs to show how you can manipulate the underlying `StyledSpinnerNext` element.
> docs(spinner): add example showcasing $as prop

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
Fixes an `eslint-plugin-baseui` error when spreading an object in `overrides` for `Modal`.
> fix(eslint-plugin-baseui): object spread crash

- documentation-site/components/example.js
For the ~15 mins or so between deploying the docs site and publishing to npm 'open in codesandbox' would fail to properly load. This change will avoid that by always defaulting to 'latest'
> fix(docs): use latest version in code sandboxer

- documentation-site/pages/components/block.mdx
Fixes incorrect large breakpoint value in documentation.
As per `src/themes/shared/breakpoints.js`, the large breakpoint value is actually `1136` not `1280`.
> fix(docs): fix incorrect breakpoint documentation

- .codesandbox/ci.json
- documentation-site/components/const.js
- package.json
- src/utils/focusVisible.js
- fixes the CodeSandbox setup, `baseui/esm` needs to be used when importing `BaseProvider` so everything is importing from the same source, otherwise things like React context doesn't work, this is a problem only in CodeSandbox since its bundler doesn't respect our esm mapping (Webpack does)
- reverts changes made to not displaying focus-ring,  it was a workaround for this issue... the mystery is solved!
- adds CodeSandbox CI, so every PR should come up with sandbox that will have PR's `baseui` built and loaded
> fix(codesandbox): fix DarkTheme, focus-ring, add CI integration

- documentation-site/components/const.js
- package.json
This should make both CodeSandbox and Webpack happy. We don't need this field since our main file is `./index.js` anyway.
> fix(deps): remove main field

- documentation-site/examples/form-control/validation.js
Clicking on the email input example currently moves focus to the regular input example, because they both have the same id.
> fix(docs): change FormControl email input example id

- packages/baseweb-vscode-extension/ext-src/coloring.ts
bug introduced in https://github.com/uber/baseweb/pull/3172
That specific vscode API accepts only shorthand properties.
> fix(vscode): revert longhand properties

- src/table-semantic/__tests__/table-builder.test.js
- src/table-semantic/styled-components.js
- src/table-semantic/table-builder.js
Fixes #3208 
Exposes row and column information to styled components as `$col`, `$colIndex`, `$row`, `$rowIndex` properties. This will allow overrides access to this information in order to make style changes like highlighting a row for example.
> feat(table-semantic): expose col, colIndex, row, and rowIndex props

- src/input/index.d.ts
Adds `pattern`  to `BaseInput`'s TS types. Also `aria-errormessage` was missing (it's in the flow types) so I added that too.
> fix(input): adds missing props (pattern and aria-errormessage) to the TS defs

- documentation-site/pages/guides/theming.mdx
inline-style-expand-shorthand only works on hyphenated css property names, not camelCased css-is-js properties
> fix(docs): recommend better style util packages

- documentation-site/examples/tabs/custom-keys.js
- documentation-site/examples/tabs/custom-keys.tsx
- documentation-site/pages/components/tabs.mdx
Adds a new example to tabs documentation.
> docs: add tabs example with custom keys

- src/data-table/data-table.js
Fixes: https://github.com/uber/baseweb/issues/3247
The `expandBorderStyles` is useful on components that accept overrides, but it's not necessary in `data-table` components.
> fix(data-table): reverts expand border in non customizable data-table

- src/data-table/__tests__/data-table-batch-action.e2e.js
- src/data-table/header-cell.js
Clicking the 'select-all' checkbox would trigger a column sort. This diff avoids that.
> fix(data-table): avoid sort on select all check click

- src/menu/index.d.ts
- src/menu/types.js
Fix type checking ListItem for type `MenuProps` for typescript and flow
> fix(menu): fix type checking MENUPROPS in menu

- src/layout-grid/index.d.ts
Fixes the ALIGNMENT enum to work with type checking + usage with the `align` prop when using typescript
[constants.js](https://github.com/uber/baseweb/blob/45e52ab24c18a8df7f6025cdb3f716030f8e5a1a/src/layout-grid/constants.js#L14-L18)
> fix(layout-grid): fix ALIGNMENT enum

- src/layout-grid/__tests__/layout-grid.scenario.js
- src/layout-grid/cell.js
- src/layout-grid/grid.js
- src/layout-grid/index.d.ts
- src/layout-grid/types.js
Fixes #3263 
Change grid to use context so that non-cell elements can be used as children to the grid. This will allow you to split up cells into subcomponents that have a react fragment wrapped around them, or be wrapped in HoCs/other wrapped components that still render Cells.
This change should be entirely backwards compatible with any existing code that uses Baseweb.
> feat(layout grid): use Context in grid so React.Fragments can be used

- src/datepicker/__tests__/datepicker.test.js
- src/datepicker/datepicker.js
- src/datepicker/types.js
Fixes #3230
The scenario in the issue is already taken care of, the author just forgot you'll always have a `formatString` if not the passed then the default
<sup>Btw, I love baseweb! Especially the overrides pattern, it's stellar, like it embraces the fact that you'll always have to override something at some point so why not provide a way to do that in the first place. And not to mention it's not just trivial style overrides but [actual overrides in behavior and logic too](https://baseweb.design/guides/understanding-overrides/#override-the-entire-subcomponent) So thank you :)</sup>
> fix(datepicker): inputting a date into input field results in right date

- documentation-site/examples/pin-code/completion.tsx
- src/button/__tests__/button.test.js
- src/button/index.d.ts
Fixed #2652
`Button` is already forwarding the ref to html button element so there won't be any problems in runtime in code on the issue page, only the types weren't reflecting that. [Here's the test](https://codesandbox.io/s/summer-sun-ejnct?file=/example.tsx) for this PR. (there's no type testing strategy in the repo hence testing this way)
Also there are a lot of components that forward the ref but the types don't reflect that so can send a PR that fixes all those types?
Patch: Bug Fix
> fix(button): make .d.ts reflect that it's uses forwardRef

- src/button/__tests__/button-in-form.test.js
- src/button/button.js
Per off line discussion, enhancing the behavior of the Button component to prevent form submission when a button has `isLoading={true}`. The Button currently prevents the onClick handler from firing, so this is just an extension of the idea that the button "should not cause any action when it's in a loading state".
Patch: Bug Fix
> feat(button): prevent form submit when button is loading

- documentation-site/examples/toast/toast-close-from-outside.js
- documentation-site/examples/toast/toast-close-from-outside.tsx
- documentation-site/pages/components/toast.mdx
Closes #3188
This PR improves the [toast documentation](https://baseweb.design/components/toast) by adding an example where you can close the toast from outside of it
> docs(toast): adding new example for toast component

- src/tree-view/tree-view.js
Fixes the error where a ref may be null, but still be fired.
It could be that I'm using the component wrong, maybe I'm not forwarding a ref, but this check should still be in place.
Patch: Bug Fix
> fix: call focus on treeItemRefs if ref is not null

- src/toast/__tests__/toaster.scenario.js
- src/toast/toaster.js
- src/toast/types.js
It lets set the default `closeable` value for all toasts through passing it to `ToasterContainer`
> feat(toast): accept 'closeable' prop on ToasterContainer

- documentation-site/examples/list/menu-adapter.js
- documentation-site/examples/list/menu-adapter.tsx
- documentation-site/examples/menu/profile.js
- documentation-site/examples/menu/profile.tsx
- documentation-site/examples/menu/virtual-list.js
- documentation-site/examples/menu/virtual-list.tsx
- documentation-site/examples/table/filter.js
- documentation-site/examples/table/filter.tsx
- documentation-site/examples/table/pagination.js
- documentation-site/examples/table/pagination.tsx
Noticed that StackBlitz compiles `new Array` a bit strangely and so subsequent `map` calls don't work correctly. https://github.com/stackblitz/core/issues/546
Seems that if you construct an array any other way it works fine. In this PR I've switched to `Array.from` as recommended in the linked issue.
> docs: update examples with prefilled arrays

- src/tree-view/tree-view.js
When `data.length` is 0, it renders `0` in the children.
This PR returns null if `data.length` is 0.
Patch: Bug Fix
> fix(tree-view): ensure nothing is rendered in treeview if data is empty

- documentation-site/pages/getting-started/setup.mdx
It can be viewed on the public site and links to a google doc with comments from Uber employees. This feels inappropriate.
> docs(bedrock): remove references to bedrock from public documentation

- documentation-site/examples/progress-bar/infinite.js
- documentation-site/examples/progress-bar/infinite.tsx
- documentation-site/pages/components/progress-bar.mdx
Yard provides the same functionality, and this has a bug in it, so 🔥
> docs(progress-bar): remove infinite example

- documentation-site/examples/combobox/async-options.js
- documentation-site/examples/combobox/async-options.tsx
- documentation-site/examples/combobox/filtered-options.js
- documentation-site/examples/combobox/filtered-options.tsx
- documentation-site/examples/combobox/input-overrides.js
- documentation-site/examples/combobox/input-overrides.tsx
- documentation-site/examples/combobox/replacement-node.js
- documentation-site/examples/combobox/replacement-node.tsx
- src/combobox/combobox.js
- src/combobox/index.d.ts
- src/combobox/types.js
Chrome tries to autofill combobox example with stored credit card information. Adding a `name` attribute that's unrelated to payment removes the suggestion
Patch: Bug Fix
> fix(combobox): test name attr to remove credit card suggestion on docs site

- src/combobox/__tests__/combobox.test.js
- src/combobox/combobox.js
- src/combobox/index.d.ts
- src/combobox/types.js
In some situations, it's useful to know whether a combobox change came from user-keyboard-input vs user-selection. If a suggestion is selected, the option value will be provided to the change handler, otherwise null.
> feat(combobox): include option in change handler params if suggestion is selected

- src/card/index.d.ts
The index.d.ts for the Card component was importing types from a flow types file causing a typescript error when importing from `baseui/card`:
```
error TS7016: Could not find a declaration file for module './types.js'. '/Users/airhorns/Code/gadget/node_modules/baseui/card/types.js' implicitly has an 'any' type.
3 import {ImagePropsT} from './types.js';
```
The type for the `headerImage` prop is a string or all the props that an `<img>` can take, so this updates the TypeScript type to just use React's built in props list for images.
Patch: Bug Fix
> fix(card): broken typescript defintions

- documentation-site/examples/select/focus.js
- documentation-site/examples/select/focus.tsx
- documentation-site/pages/components/select.mdx
- src/select/__tests__/select.test.js
- src/select/index.d.ts
- src/select/select-component.js
- src/select/types.js
Similar to `<Input/>`, it's useful to be able to get a ref to the inner element so developers can imperatively do stuff to it, like focus it. This adds a `controlRef` prop to `<Select/>` so you can do just that!
It's called `controlRef` and not `inputRef`, which is different than `<Input/>`, but on purpose, because if the Select isn't searchable, then there isn't actually an `<input>` created, just a `<div>` as a container. The Flow and TypeScript types reflect this, but I thought it might be good to make the name and docs clear that it won't always be an input.
Added a test and an example in the docs.
Fixes #3398
> Add a controlRef prop to <Select/>

- packages/eslint-plugin-baseui/src/index.js
Without this, you'll get the following when you try to use the recommended config from an external project:
```
1:1  error  Definition for rule 'deprecated-theme-api' was not found      deprecated-theme-api
1:1  error  Definition for rule 'deprecated-component-api' was not found  deprecated-component-api
1:1  error  Definition for rule 'no-deep-imports' was not found           no-deep-imports
```
Patch: Bug Fix
> fix(eslint-plugin-baseui): add baseui prefix for recommended config

- src/tree-view/index.d.ts
The TreeView TypeScript types were accidentally referring to a Flow type variable `OverrideT` which should just be `Override` like the rest of the TypeScript types, as well as using an older and unnecessary style of expressing a `children` prop. The TypeScript `React.ReactNode` type includes arrays of `React.ReactNode` as well, so the extra stuff isn't necessary.
Patch: Bug Fix
> fix(tree-view): don't refer to non-existent typescript types

- src/button/styled-components.js
The height of a button was changing when setting `isLoading` in some sites. The cause was tracked down to sites applying global styles like `* { box-sizing: border-box; }`. To ensure that all sites have a consistent button height regardless of these global styles we are setting the LoadingSpinner's `<span>` to have its `box-sizing` set to `content-box`.
Patch: Bug Fix
> fix(button): prevent button height change when isLoading

- documentation-site/components/yard/config/select.ts
- documentation-site/examples/select/overriden-tag.js
- documentation-site/examples/select/overriden-tag.tsx
- documentation-site/pages/guides/understanding-overrides.mdx
- src/select/__tests__/stateful-select.test.js
- src/select/index.d.ts
- src/select/multi-value.js
- src/select/select-component.js
- src/select/types.js
Historically, the name `MultiValue` seemed to confuse folks - `Tag` would be probably a better name, as it directly shows what underlying component is being overriden
> feat(select): add alias for tag override

- documentation-site/pages/components/styled.mdx
Noticed broken link to Styletron's `styled` function in [Styled](https://baseweb.design/components/styled/) docs:
❌ https://www.styletron.org/api/#styled
✅ https://www.styletron.org/api-reference#styled
> docs(typo): fix link to styletron's styled api

- .buildkite/pipeline.yml
- scripts/publish-to-npm.js
- scripts/sync-package-versions.js
I moved some files around before putting up the last pr and broke the script. This PR also restores the package.json sync file that's used in the vs-code extension release process
> fix(alpha-publish): correct root_dir in publish script

- src/accordion/index.d.ts
Fixes #3477 
Removed the `$expanded: never` from the index.d.ts type file of the Accordian component.
Patch: Bug Fix
> fix(accordian): remove :never from type file

- jest.e2e.setup.js
If the screenshot errors it hides the true error in the test. This PR adds a try/catch to make sure the real error gets out. Also adds `type: 'png'` to avoid mime type lookups. For some reason this can fail so let's just avoid that situation.
> test: fix possible e2e screenshot issue

- src/form-control/form-control.js
- src/form-control/types.js
FormControls can be passed a single child of any type to contain the actual controls. The `error` and `positive` props are passed down to that single child, which is useful when it's an `<Input/>` or what have you. If it's a `<div/>` or something like that however, React logs a warning (I think only in Strict mode) about passing the non-DOM props `error` and `positive` to a div. You can ideally avoid this warning by not using FormControl's `error` or `positive` functionality at all when using non-baseweb children, but prior to this change the warning would still be logged even when not using those props.
This changes `<FormControl/>` to not pass an `error` or `positive` prop to it's single child unless those props are actually set to something. No more warnings!
Patch: Bug Fix
> fix(form-control): don't pass non-DOM props to DOM children

- src/popover/__tests__/popover-unreliable.e2e.js
> chore(e2e): extend jest timeout on popover e2e tests

- documentation-site/components/table-of-contents.js
Ensures that both anchors and links to them use the same `slugify` method. Fixes currently not working ToC's links to anchors with special chars (i.e. https://baseweb.design/components/tabs-motion/#rendering-&-seo)
Patch: Bug Fix
> docs(toc): use slugify helper to create anchor link

- scripts/alpha-test-web-code.js
- scripts/publish-to-npm.js
corrects the order of args and flags in the npm publish command for eslint plugin
> fix(build): correct eslint publish command

- src/toast/types.js
Fixes #3303
Use React.Node type for Toast Children
Patch: Bug Fix
> fix: toast children flow type

- documentation-site/components/yard/config/combobox.ts
- src/combobox/__tests__/combobox-form-control.scenario.js
- src/combobox/combobox.js
- src/combobox/index.d.ts
- src/combobox/types.js
Add support for setting the `id` attribute of the rendered `<input>`.
Minor
> feat(combobox): adds support for id attribute

- src/tabs-motion/__tests__/tabs-motion-conditional.scenario.js
- src/tabs-motion/__tests__/tabs-motion.e2e.js
- src/tabs-motion/tabs.js
- vrt/config.js
Fixes an issue where conditionally rendering a `Tab` can cause hook mismatches between renders. The fix is to move the inlined `React.Children.map` "components" into actual components and move the early return condition out.
> fix(tabs-motion): handle conditional tabs

- scripts/publish-to-npm.js
More on the solution here https://nodejs.org/api/child_process.html#child_process_options_stdio
This is where the error is visible, but silent: https://buildkite.com/uberopensource/baseweb/builds/17176#30617f3f-944b-4b85-9a8c-1e13235704f8
Ideally , we want to fail the builds
> fix(deploy): proper error handling

- src/textarea/index.d.ts
- src/textarea/types.js
Adds `maxLength` prop which exists in the documentation but is missing from the flow and ts types
Patch: Bug Fix
> Adds maxLength prop to TextareaProps

- src/button-group/index.d.ts
Fixes `node_modules/baseui/button-group/index.d.ts(3,9): error TS2440: Import declaration conflicts with local declaration of 'SHAPE'.` by removing duplicate `SHAPE` definition. [The definitions](https://github.com/uber/baseweb/blob/master/src/button/index.d.ts#L23-L28) are exactly the same, so no breaking changes.
Patch: Bug Fix
> fix(button-group): remove duplicate SHAPE definition

- documentation-site/components/yard/config/textarea.ts
Fixes #3660
Description
Exported ADJOINED constant from textarea/index.js similar to STATE_CHANGE_TYPE & SIZE which were internally fetched from input/constants.js
Reproduced Error : [Video](https://www.loom.com/share/81078fd4eee4433382c675d5fe5d20a9)
Working Fix: [Video](https://www.loom.com/share/651213ac54854d47a3e3fea7f9a7b02e)
Scope
Patch: Bug Fix
> fix(textarea): removes ADJOINED enum

- src/toast/index.d.ts
Fixes #3681 - Add autoFocus prop to typescript ToastProps defintion
Update the typescript definition file for the Toast element. Added the `autoFocus` prop to the types defintion file.
**Patch: Bug Fix**
> Adds autoFocus prop to Toast ts defintion.

- documentation-site/components/yard/config/combobox.ts
- src/combobox/__tests__/combobox.test.js
- src/combobox/combobox.js
- src/combobox/index.d.ts
- src/combobox/types.js
This PR adds an `onFocus` prop to the combobox which returns the current input value, similar to the `onBlur` behavior.
This is useful when trying to manipulate app state outside of the component based on focus/blur behavior
> feat(combobox): add `onFocus` prop to combobox

- documentation-site/components/yard/config/combobox.ts
Fix the yard for combobox. Currently has `onBlur` and `onFocus` handlers that set state.
> docs(combobox): fix yard focus and blur handlers

- src/app-nav-bar/app-nav-bar.js
Just noticed that the `data-baseweb` attr is missing from the app-nav-bar component
> fix(app-nav-bar): add data-baseweb attr

- src/skeleton/styled-components.js
Clears up a warning when using the styletron atomic engine and the animated skeleton component.
> fix(skeleton): clear up warning

- documentation-site/pages/components/use-styletron.mdx
Added the word 'you' to the following sentence in the `useStyletron` docs:
> Doing so saves **you** from needing to import the custom theme type around. See below for an example.
Patch: Bug Fix
> Amend typo in documentation

- src/menu/index.d.ts
Fixes #3746 
Adds OptgroupHeader to Menu overrides type definitions.
> fix(menu): types

- src/styles/styled.js
> fix(styletron): relax styletron-component to accept props

- src/tabs-motion/__tests__/tabs-motion.e2e.js
- src/tabs-motion/index.d.ts
- src/tabs-motion/styled-components.js
- src/tabs-motion/tabs.js
- src/utils/focusVisible.js
Removes focus from `TabPanel` components. Also fixes an issue where focusVisible wasn't propagating properly to root components.
> fix(tabs-motion): remove focus from tabpanel

- src/data-table/column-datetime.js
Fixes datetime column's filter not showing applied categorical filters. The problem was with `if (input.range)` condition which always evaluated to `true` - In case when categorical filter was applied, `input.range` was an empty array which still evaluates to `true`.
Patch: Bug Fix
> fix(data-table): reflect applied filters correctly in datetime filter

- src/theme.ts
Allows TS users to compose custom theme types in a more synchronized way. See [this thread](https://github.com/uber/baseweb/issues/1370#issuecomment-696007001).
> feat(theme): export typescript theme properties

- src/link/index.js
Avoid passing in animateUnderline as attribute. Otherwise results in warning:
```
Warning: React does not recognize the `animateUnderline` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `animateunderline` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Test Plan: Create a Link with animateUnderline prop and no longer see the warning.
> fix(link): avoid passing in animateUnderline as attribute

- src/tabs-motion/tabs.js
I've noticed a bug in docs for [Tabs (Motion)](https://baseweb.design/components/tabs-motion/) example. 
The property `activeKey` isn't updating in yard when switching between the tabs:
As I dug, it happens because the component returns the`activeKey` prop as a number, which causes this issue. 
This fix based on the code implementation from the similar Tab component, where it explicitly converts index to string: https://github.com/uber/baseweb/blob/b144ca682059421fe2fd9cfe0e45af62ad9c3beb/src/tabs/tabs.js#L44
Patch: Bug Fix
> fix(tabs-motion): use string key

- src/typography/index.d.ts
Adds missing typescript definitions for typography components with mono font.
Patch: Bug Fix
> fix(typography): add mono-font components typescript definitions

- src/table-semantic/__tests__/table-builder.test.js
- src/table-semantic/index.d.ts
- src/table-semantic/table-builder.js
- src/table-semantic/types.js
The TableBuilderColumn supports passing React.Node in header prop. 
But the area-label generated for `th` tag doesn't render text properly in this case:
```
<th ... aria-label="[object Object], not sorted">...
```
In this PR I am proposing to add a new optional property `tableHeadAriaLabel` to be shown in aria-label
Patch: Bug Fix
> feat(table-semantic) add aria label prop for head cell

- documentation-site/pages/guides/theming.mdx
Currently in [Primitives section of theming guide](https://baseweb.design/guides/theming/#primitives) links to Flow and Typescript definitions refer to wrong line numbers. This PR fixes it.
Patch: Bug Fix
> fix(docs): update line numbers of theme's primitives types 

- src/test/test-setup.js
Closes: https://github.com/uber/baseweb/issues/2980
After this change, unit-tests will fail if an unexpected `console.warn` or `console.error` is called. This will help to avoid publishing known errors to users
> chore(test): fail unit tests of console warn/error

- .buildkite/pipeline.yml
React 17 will be releasing soon and with that we will likely get an influx of related github issues. This PR adds additional CI jobs for unit-tests and e2e-tests with the next react version
> chore(test): adds react@next CI job

- documentation-site/components/yard/config/table-semantic.ts
- documentation-site/examples/table-semantic/empty-message.js
- documentation-site/examples/table-semantic/empty-message.tsx
- documentation-site/examples/table-semantic/span.js
- documentation-site/examples/table-semantic/span.tsx
- documentation-site/pages/components/table-semantic.mdx
- src/table-semantic/__tests__/table-builder.test.js
- src/table-semantic/__tests__/table-semantic-compose.scenario.js
- src/table-semantic/__tests__/table.test.js
- src/table-semantic/index.d.ts
- src/table-semantic/index.js
- src/table-semantic/styled-components.js
- src/table-semantic/table-builder.js
- src/table-semantic/table.js
- src/table-semantic/types.js
Added loading and empty message support for semantic-table.
`Table` and `TableBuilder` accepts three new properties `isLoading`, `loadingMessage` and `emptyMessage`.
The loading message will be displayed when a property `isLoading` is set to true. Defaults value is `Loading...`
It will expand to the full table width using the `colSpan` attribute of total columns in the table.
The empty message will be displayed when the data array is zero length and `loadingMessage` is provided as property. By default, message value is not set and it won't be shown.
The messages are rendered inside `tr > td` tag to complain to table semantics.
> feat(table-semantic): add loading and empty messages

- documentation-site/components/yard/config/rating.ts
- documentation-site/examples/rating/starReadOnly.js
- documentation-site/examples/rating/starReadOnly.tsx
- documentation-site/pages/components/rating.mdx
- src/rating/__tests__/emoticon-rating.test.js
- src/rating/__tests__/star-rating.test.js
- src/rating/emoticon-rating.js
- src/rating/index.d.ts
- src/rating/star-rating.js
- src/rating/styled-components.js
- src/rating/types.js
Implements enhancement #3741
This new minor feature implements a `readOnly` option for the `StarRating` and `EmoticonRating` components.
This allows one to show a rating without allowing user interactivity with this rating.
I've also added this option to the `EmoticonRating` for consistency, although it does make a little less sense here. But I see no issue with providing this option to the user either way.
> feat(rating): allow read-only rating #3741

- package.json
- src/slider/slider.js
- yarn.lock
fixes: https://github.com/uber/baseweb/issues/3811
https://github.com/uber/baseweb/pull/3833 is no longer needed since the fix is simple enough. baseui slider fails to operate when react-range is version 1.8.0. This didn't show up in our testing because it's locked to 1.7.0. 🤷 The reason it was failing was because baseui code was clobbering the `ref` supplied by the `react-range` library. This diff removed the need for our own ref
Patch: Bug Fix
> fix(slider): updates to react-range 1.8.0 and fixes error

- src/tabs-motion/tabs.js
Removes the 100ms debounce on updates coming from the resize observer. Instead, track tab dimensions after each render and compare them when the resize observer fires.
This fixes an issue where the Tabs can render, a Tab changes width, and then 100ms later the highlight updates. This causes a jump slightly after rendering and can cause VRTs to be flakey.
> fix(tabs-motion): reduce initial re-rendering

- package.json
While working on the project I saw that lint command takes a very long time. Around `30 - 40 seconds` on my machine.
The suggestion is to add two options to eslint command:
- **cache**. Only check changed files. The default cache location is `.eslintcache` file which is already ignored in `.gitignore` [docs](https://eslint.org/docs/user-guide/command-line-interface#caching)
- **fix**. Automatically try to fix as many issues as possible without breaking the code, example adding semicolon ar removing space [docs](https://eslint.org/docs/user-guide/command-line-interface#-fix)
Time differences:
Patch: Bug Fix
> chore(build): use fix and cache eslint options in lint:code command

- src/data-table/__tests__/data-table-text-search.scenario.js
- src/data-table/column-categorical.js
- src/data-table/column-string.js
There are cases where case-agnostic string equality is checked by comparing the results of `toLocaleLowerCase` to the results of `toLowerCase`. This works in most cases, but [for some locales, the output can be different](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase#:~:text=toLocaleLowerCase()%20does%20not%20affect,may%20be%20a%20different%20result.), even if the input strings are identical.
Patch: Bug Fix
> fix(data-table): consistent toLowerCase comparators in textQueryFilter

- documentation-site/components/hooks.js
sets react 16 in stackblitz examples for now
> fix(stackblitz): pin react to v 16

- .buildkite/pipeline.yml
Forgot to change this over from before v17 was officially released in the stable channel
> chore(ci): use stable release in react 17 tests

- src/rating/styled-components.js
empty string is not a valid transform property value
Patch: Bug Fix
> fix(rating): fix styletron warning

- documentation-site/components/gallery.js
- documentation-site/components/table-guide-notification.js
- documentation-site/pages/components/data-table.mdx
- documentation-site/pages/components/table-grid.mdx
- documentation-site/pages/components/table-semantic.mdx
- documentation-site/pages/components/table.mdx
- documentation-site/pages/guides/tables.mdx
- documentation-site/routes.js
Adds a 'table guide' to compare the different options base web publishes
> chore(docs): add table guide

- documentation-site/examples/datepicker/datepicker-with-timezone.js
- documentation-site/examples/datepicker/datepicker-with-timezone.tsx
- documentation-site/examples/datepicker/i18n.js
- documentation-site/examples/datepicker/i18n.tsx
- documentation-site/examples/datepicker/with-mask.js
- documentation-site/examples/datepicker/with-mask.tsx
- documentation-site/pages/components/datepicker.mdx
This PR includes 4 changes to Datepicker documentation page:
1. adds placeholder for `Datepicker with localization` example
2. adds `Datepicker with custom mask` example. It clarifies that three props (formatString, placeholder, mask) for datepicker must be set to work correctly. If `formatString` is not set, manual date input (typing) will not work, example - https://stackblitz.com/edit/react-xvthsy-ebrvmn?file=src/example.js
3. moves `Datepicker with no mask` description text after input
4. fixes a bug where a page crash if a date is removed in `Datepicker with timezone selection` example
Patch: Bug Fix
> fix(datepicker): add with mask example. Fix timezone bug

- src/menu/stateful-container.js
- src/select/dropdown.js
Previous PR was kind of a hacky fix to solve the one particular interaction with modal + select, but this change should completely opt the dropdown out of focus management with the focus lock
Patch: Bug Fix
> fix(select): opt dropdown out of focus locking

- documentation-site/components/yard/config/select.ts
This small change just removes typo on `Select` doc page
Patch: Bug Fix
> docs(select) removed typo artifact

- src/table/__tests__/filter.test.js
- src/table/__tests__/table-filter.scenario.js
- src/table/filter.js
- src/table/index.d.ts
- src/table/types.js
Addresses issue #3955 
**Description**
Added an optional close button, determined by a boolean prop on the filter. This gives developers greater customization for design/accessibility when using the filter.
**Scope**
> added optional filter close button plus tests

- src/spinner/index.d.ts
Fixes #3950 
Removed the duplicate entry for the SIZE enum.
Patch: Bug Fix
> fix(spinner): remove duplicate identifier for size

- src/table/filter.js
- src/table/index.d.ts
- src/table/types.js
Addresses issue #3964 
Added an optional returnFocus prop on Filter component, determined by a boolean prop on the filter, giving developers greater customization for focus management/accessibility.
> added returnFocus prop to Table Filter

- documentation-site/pages/blog/getting-started-with-base-web/index.mdx
* fix codesandbox embed url on password-generator tutuorial
Hi, new to BaseWeb and found it astonishing! While going through the docs, I found that the codesandbox embed is showing import errors.
Forked the sandbox and fixed baseui package version.
https://codesandbox.io/s/password-validatorgenerator-w-base-web-forked-w72nq
Patch: Bug Fix
> docs(blog): fix crashing codesandbox embed

- src/data-table/__tests__/text-search.test.js
- src/data-table/text-search.js
Previously, it was building a regex string from the query. This would break if the query contains reserved tokens like `[` for example
Patch: Bug Fix
> fix(data-table): query handles non-alphanumeric characters

- src/input/styled-components.js
Toggle button (eye) becomes partly invisible when testing on small screen sizes or when the input is cramped.
See: https://stackoverflow.com/a/33811151
Screenshot:
Browser: Firefox
Version: 84.0.1
Patch: Bug Fix
> Fix password input toggle button (eye) visibility when shrunk in Firefox

- src/data-table/filter-menu.js
> fix(data-table): adds y-overflow to filter menu

- src/datepicker/styled-components.js
Closes: https://github.com/uber/baseweb/issues/4007
Change the styles for outside month dates when peekNextMonth prop is passed as true. Attaching here before and after screenshot
Before - 
After -
Patch: Bug Fix
> fix(datepicker): design for outside month dates

- src/datepicker/calendar-header.js
- src/datepicker/styled-components.js
- src/datepicker/utils/date-helpers.js
Fixes #4012 
Entire calendar rerenders everytime we hover over any date in datepicker, it tooks almost 165ms to rerender it. This PR tries to improve this and able to reduce the time to nearly 90ms. This has two fixes.
1. Replace spread operator with native `Object.assign`
2. Calculate the Month Year items only when minYear or maxYear changes. 
Attaching the screenshot for each step.
Patch: Bug Fix
> improve performance of datepicker

- src/theme.ts
This PR adds typescript types for `contentOnColorInverse` and the mono font family.
I don't know where the comment at the top came from - possibly some automated flow stuff in my IDE or perhaps something in the commit hooks in baseweb? I'm assuming it shouldn't be in there, but given it wasn't added by me I'll leave in until told to remove it :)
> fix(typescript): add missing types to ts theme file

- documentation-site/components/code-box.tsx
Use overflow: auto instead of scroll for code blocks so scrollbars only appear when needed.
Before: 
After:
> fix(docs): use overflow: auto instead of scroll for code blocks

- documentation-site/examples/datepicker/with-callback-overrides.js
- documentation-site/examples/datepicker/with-callback-overrides.tsx
- documentation-site/pages/components/datepicker.mdx
- documentation-site/pages/guides/understanding-overrides.mdx
- src/helpers/overrides.js
* Clarify and provide guidance for users seeing the warning: `baseui:Overrides Props as a function will be removed in the next major version`
* Add complex component prop merging example for overrides and datepicker docs.
Fixes #4035
> fix(docs): include guidance to migrate way from overrides props functions

- documentation-site/components/yard/config/drawer.ts
- src/drawer/__tests__/drawer.test.js
- src/drawer/drawer.js
- src/drawer/types.js
Fixing Issue: https://github.com/uber/baseweb/issues/4030
The showBackdrop prop was being used to determine if the backdrop was rendered. The desired behavior is for the backdrop to still render, so it can catch clicks and close the drawer, but be fully transparent instead of partially transparent. 
After inspecting the code, I found where we could pass along the prop into the styled component and use it as an additional check for setting the opacity to 0. 
Since the backdrop should now always be rendered, I've added a new test to ensure that is the case.
I've also turned on this prop in the documentation page as it seems to be have been turned off because it wasn't working properly yet.
Patch: Bug Fix
> fix(drawer): showBackdrop prop fix from Issues

- src/rating/styled-components.js
Currently every single star in the `StarRating` component has `marginRight`. This means that if you're trying to center, or right-align the component, then you'll be out by `$theme.sizing.scale300`
You can side-step this issue by applying the following override:
```
overrides={{
Item: {
style: ({ $index }): StyleObject => {
// currently every single star has
return $index === numItems ? { marginRight: 0 } : {};
},
},
}}
```
but it feels like this should not be necessary.
Patch: Bug Fix
> Don't marginRight on the last star, so as to preserve centering

- src/block/index.d.ts
Setting `id` on a `Block` element results in a TypeScript error:
TypeScript error
No TypeScript error
https://github.com/uber/baseweb/pull/3620
https://github.com/uber/baseweb/issues/2872
> feat(block): add id prop to block TS def

- scripts/publish-to-npm.js
The build is currently failing because in my last PR https://github.com/uber/baseweb/pull/4089 I didn't check that it worked end-to-end, and missed that the publish-to-npm script hardcodes that only `latest` and `alpha` are allowed tags. This PR adds in `next` as an allowed tag
Patch: Bug Fix
> Allow 'next' tag in publishing

- scripts/publish-bleeding-edge.js
- scripts/publish-to-npm.js
Attempt 3 to get https://github.com/uber/baseweb/pull/4089 working properly...! (Sorry for the multiple PRs, this is inherently hard to test end-to-end)
So, apparently my understanding of `npm publish --tag x` was incorrect. Apparently, it just performs the normal publish flow, but then _also_ tags the end result. This means if that package version already exists, `npm publish` will result in a 403
This PR follows the same logic that the alpha release follows, ensuring that we create a unique package version for the release before hitting `npm publish`
Patch: Bug Fix
> Publish 'next' tag with unique semver

- src/menu/stateful-container.js
- src/menu/types.js
- src/select/dropdown.js
Fixes #4098
Adds a "internal" forceHighlight prop to StatefulMenu that Dropdown can use.
The prop disables the mouseLeave highlight removal and sets the highlight to the first item if there are 1 or more items but no highlight.
Patch: Bug Fix
> feat(select): keep dropdown options highlighted

- documentation-site/pages/guides/understanding-overrides.mdx
The label becomes black when dragged.
Fixes a typo.
Patch: Bug Fix
> Fix a typo in understanding-overrides.mdx

- documentation-site/components/yard/config/combobox.ts
- documentation-site/examples/combobox/focus.js
- documentation-site/examples/combobox/focus.tsx
- documentation-site/pages/components/combobox.mdx
- src/combobox/__tests__/combobox.test.js
- src/combobox/combobox.js
- src/combobox/index.d.ts
- src/combobox/types.js
Adds a ref to the Combobox's inner input. This is useful if you want to give focus to the Combobox or manipulate the inner Input control in other ways.
> feat(combobox): adds inputRef to <Combobox/>

- src/timepicker/timepicker.js
Fixes #4079 
Configures the select to use the label as the valueKey to filter by. 
Patch: Bug Fix
> fix(timepicker): fix filtering by label (instead of id)

- documentation-site/components/yard/config/combobox.ts
This PR updates the `Combobox` documentation to the reflect the fact that overrides are available for the `Popover` component.
There is no functionality change, it's just documenting an undocumented feature
The change of `componentName` is not ideal as it's mutating the object but the default value exported is `StatefulPopover` and won't work if left unchanged, I'm more than happy to update the PR with some guidance
Patch: Docs Fix
> docs(combobox): add popover overrides to combobox

- src/radio/styled-components.js
Fixes #4208 
Add clip rect/position absolute to input in radio button to hide in safari.
Patch: Bug Fix
> fix(radio): use position/clip to hide input

- .flowconfig
- package.json
- yarn.lock
Updates styletron-react peer dependencies to include the latest version, which relaxed a react major version issue.
> chore(deps): upgrade styletron-react peer dependencies 

- src/combobox/styled-components.js
Fixes #4253 
Fixed combobox options padding in rtl mode.
Patch: Bug Fix
> fix(combobox): fix combobox options padding issue in rtl mode

- src/popover/popover.js
Fixes #4181 
I have fixed the firing of `onClickOutside` when the user clicks on a popover target or a content in a web component with the approach mentioned in the issue. I have tested this in a web component.
Patch: Bug Fix
> fix(popover): fix onClickOutside event handler for web component

- packages/eslint-plugin-baseui/src/deprecated-theme-api.js
Remove used color tokens for slider component from deprecated list
Link to [PR](https://github.com/uber/baseweb/pull/4249) where the colors tokens are used
> fix(eslint-plugin-baseui): remove slider theme tokens currently in-use

- .buildkite/pipeline.yml
Converting the alpha test job to be available on any commit gated on a buildkite wait step. Verified that anonymous BK users and users not in team cannot trigger the step. One downside with this approach is that the alpha job waits for other jobs to finish
> chore(alpha-test): test block step

- documentation-site/next.config.js
Related: #4265 
Fixes the next configuration to use a different image loader for v10, as next-images no longer support image optimization for exporting (only supports runtime optimization) 
https://nextjs.org/docs/messages/export-image-api
> chore(domain): fix old versions not being deployed

- deploy-versioned-docs.sh
Use yarn to run now command, since it is no longer installed globally as part of #4073 . 
https://buildkite.com/uberopensource/baseweb/builds/18683#d65f6cc8-9c73-410f-88e7-6bb7c307a4c6/176-513
> chore(deploy-script): add yarn due to now command not found

- documentation-site/pages/guides/theming.mdx
Update example for Button overrides to use BaseButton instead of Base per https://baseweb.design/components/button/
Was looking through theming docs and noticed the example given for overrides for <Button> was `Base` when `BaseButton` should be used instead.
Patch: Bug Fix
> docs(theme): update theming.mdx overrides example

- documentation-site/components/yard/config/list-item-label.ts
- error when open list-item-label override
- related #4341
> fix(docs): list-item-label sharedProps error

- documentation-site/pages/_app.js
Fixes the flicker of light theme when refreshing the doc site while dark mode is toggled on.
> chore(doc-site): prevent flicker when refresh in dark mode

- src/button-group/__tests__/button-group.test.js
- src/button-group/button-group.js
Fixes small error in https://github.com/uber/baseweb/commit/32198e946a584813553a2653d39f09627150ddb4
Patch: Bug Fix
> fix(button-group): move isSelected var to after null check

- src/list/index.d.ts
* Related #4355
This fix adds the missing typescript type definitions for `overrides` on the `ListItemLabel`.
The original error that led me to opening this PR:
```ts
Type '{ children: string; overrides: { LabelContent: { style: () => { backgroundColor: string; }; }; }; description: string | null; }' is not assignable to type 'IntrinsicAttributes & LabelPropsT & { children?: ReactNode; }'.
Property 'overrides' does not exist on type 'IntrinsicAttributes & LabelPropsT & { children?: ReactNode; }'.ts(2322)
```
Patch: Bug Fix
> fix(list-item): missing type definition for overrides

- .buildkite/pipeline.yml
Alpha test was green yesterday even though one project unit-tests failed. The `--unhandled-rejections=strict` option ensures that node will exit with a non-zero code and reflects future behavior
> fix(alpha-test): unhandled exceptions should exit with non-zero

- src/toast/toaster.js
Reopens #3414 since moving this to componentDidMount prevents toast messages from being triggered on initial render.
> fix(toast): fix container to render portal if mounted and in browser

- src/combobox/index.d.ts
I found that the `options` type was `OptionT`, but `options` should be an array. So I changed this type and opened a pull request.
Patch: Bug Fix
> fix(combobox): change options type to an array

- src/toast/index.d.ts
There is no type `ToastInnerContainer` in the `ToasterOverrides` , so I added it.
Patch: Bug Fix
> fix(toast): add missing type definition

- documentation-site/components/yard/config/toast.ts
- documentation-site/examples/toast/toast-close-from-outside.js
- documentation-site/examples/toast/toast-close-from-outside.tsx
- documentation-site/examples/toast/toast-notification.js
- documentation-site/examples/toast/toast-notification.tsx
- documentation-site/examples/toast/toast-same-key-notification.js
- documentation-site/examples/toast/toast-same-key-notification.tsx
Updates the docs to no longer show examples of nesting elements within the ToasterContainer. The toaster container will re-render after being mounted, which can cause issues when server side rendered pages remount routes/components.
> docs(toast): update docs to no longer nest children in ToasterContainer

- src/datepicker/datepicker.js
This PR implements the ability to use an empty string as a placeholder in the datepicker. 
Patch: Bug Fix
> fix(datepicker): allow empty placeholder

- documentation-site/examples/select/with-many-options.tsx
Fixes #3991
Padding on the StyledList isn't accounted for with the react-window example, causing a small scroll effect on the containing element. Removing the style prop from the list fixes the issue. 
Doc update
> docs(select): update example to render correctly

- src/input/input.js
- src/list/list-item.js
- src/tag/tag.js
Since React renders everything with the type of number, there is an unexpected behavior when passing `0` into `startEnhancer` or `endEnhancer`. 
The issue leads to zero number being showed as an unstyled element in the following components: `Input`, `Tag` and `ListItem`. 
Consider the screenshots: 
---
The fix for Tag and ListItem would be to do an explicit check. 
However, for the Input enhancers, since it supports React.Nodes, the logic can be extended to show zero number as correct enhancer: 
**After fix:** 
Patch: Bug Fix
> Fix startEnhancer & endEnhancer zero render

- documentation-site/components/yard/config/datepicker.ts
- src/datepicker/calendar.js
- src/datepicker/index.d.ts
- src/datepicker/month.js
- src/datepicker/types.js
Fixes #4465 
Added prop named `fixedHeight` in datepicker to always render 6 rows in calendar
> fix(datepicker): add prop to always render 6 rows in datepicker (#4465)

- src/list/menu-adapter.js
Fixes #3986  
Used mergeOverrides to merge the default and passed override
Patch: Bug Fix
I was getting an error from Flow saying
```
Cannot create `ListItem` element because inexact  `OverridesT` [1] is incompatible with exact  `OverridesT` [2] in property `overrides`
```
So I've disabled flow, please look into it and let me know if I'm missing something.
> fix(list): forward overrides on MenuAdapter

- src/textarea/textarea.js
Remove `value: ''` in `defaultProps` for uncontrolled `<Textarea />`.
Patch: Bug Fix
> fix(textarea): remove "value" in defaultProps

- documentation-site/examples/button-group/wrappable.js
- documentation-site/examples/button-group/wrappable.tsx
- documentation-site/pages/components/button-group.mdx
Fixes #3448
Added an example using flex-wrap property to button-group so that the buttons can wrap on small screens
Minor: Docs
> fix(button-group): add example for responsive styling

- package.json
fixes release from https://github.com/uber/baseweb/pull/4518 (we probably should update the release scripts to handle no 'v' prefix)
> Release v10.2.1

- src/select/select-component.js
Fixes #4531
Trim the internal state inputValue while filtering options in order to prevent leading and trailing spaces to be rendered as a creatable option.
Patch: Bug Fix
> fix(select): trim value in filter options(uber#4531)

- src/table-semantic/index.d.ts
Adds a missing TypeScript type definition for the `size` property of `TableBuilderProps`. The Flow type definition for `TableBuilderProps` already includes `size`, so this PR simply ensures the TypeScript definition matches.
Patch: Bug Fix
> fix(table-semantic): add size prop to TableBuilderProps type definition

- src/index.d.ts
- src/theme.ts
Fixes #4511
Colors was missing the calendarDayBackgroundSelected property for typescript, causing some ts errors when overriding color values. Add it to match the flow ComponentColorTokensT.
Also exports Theme from src/index.d.ts, after seeing the conversation on https://github.com/uber/baseweb/issues/4511
Patch: Bug Fix
> fix(datepicker): add calendarDayBackgroundSelected to Colors interface

- documentation-site/components/cheat-sheet.js
There is a bug on the cheat-sheet page: after scrolling to the element, the page returns to the top again. Happens so fast so looks like the scroll to elements don't actually work.
I've experimenting with `history.scrollRestoration = 'manual';` and next/router [events](https://nextjs.org/docs/api-reference/next/router#routerevents). 
The only solution found so far - do scroll after skipping an event loop cycle. 
Another minor update - use key indexes for child elements, since their names aren't unique.
Patch: Bug Fix
> docs(cheat-sheet): fix scroll to element

- documentation-site/components/floating-marker-container.js
- documentation-site/components/yard/config/floating-marker.ts
- documentation-site/examples/fixed-marker/x-small.js
- documentation-site/examples/fixed-marker/x-small.tsx
- src/map-marker/__tests__/floating-marker.scenario.js
- src/map-marker/constants.js
- src/map-marker/floating-marker.js
- src/map-marker/pin-head.js
- src/map-marker/styled-components.js
Add xSmallSquare and xSmallCircle back to pin head sizes.
> chore(map-marker): add round and square options to pinhead, flow issues, fix examples

- documentation-site/examples/accordion/stateless.tsx
Use correct `key`s in `useState` to showcase initial state 
`patch`
> docs(accordion): fix stateless accordion example

- documentation-site/examples/data-table/customized-column-sort.js
- documentation-site/examples/data-table/customized-column-sort.tsx
- documentation-site/pages/components/data-table.mdx
Fixes #3488  
Added an example for customized column sort as requested in the above issue.
Minor: New example
> docs(data-table): add example for customized column sort

- src/spinner/styled-components.js
Spinner is often used as a placeholder while the main content & components are loading. This can be an issue when React does [reconciliation/hydration](https://reactjs.org/docs/reconciliation.html#dom-elements-of-the-same-type) between the code that comes from server (with spinner) and client (loaded content) since we use `div` for our spinner and that's also the most common tag for any other component. React then incorrectly re-uses the same element/styling and starts spinning unrelated components.
Repro: https://codesandbox.io/s/base-web-spinner-ssr-forked-uh33d?file=/src/index.js
I believe this should be primarily fixed on the side of application making sure that SSR code = client code. But we can at least significantly lower the probability of this issue just by using a different / …
> feat: use different tag than div to prevent hydration issues

- documentation-site/pages/getting-started/setup.mdx
Fixes #4131
Nextjs Styletron template is nice but it doesn't give you working Base Web setup and there are some pitfalls along the way. Let's link the full working example project I am maintaining.
> docs: link working nextjs baseweb project in setup

- src/link/index.d.ts
Fixes #4603 
Add missing `animateUnderline` prop of StyledLink
Patch: Bug Fix
> fix(types): add missing `animateUnderline` prop

- src/rating/emoticon-rating.js
- src/rating/star-rating.js
Fixes #4613
The preview state was getting reset because `Root` component loses focus when clicking on the `Emoticon`/`Star` and `onBlur` is called thus resetting the preview state. The `onBlur` is still needed so that the preview would get reset in case of keyboard navigation.
A check whether the `relatedTarget` (component gaining focus) is within the `currentTarget` (`Root`) seems to fix this issue.
https://user-images.githubusercontent.com/17617175/140793605-b046b327-e719-478f-a0ab-d1055eaf9928.mp4
https://user-images.githubusercontent.com/17617175/140793634-6d854507-a5ab-4b26-a283-e0d415cb9319.mp4
https://user-images.githubusercontent.com/17617175/140793649-32010ee1-33fa-419e-abab-1bb9faec9e58.mp4
https://user-images.githubusercontent.com/17617175/140793654-8c8fe19f-b1e2-49cc-9a13-a5ee3 …
> fix(rating): reset preview on outside blur only

- documentation-site/components/yard/config/datepicker.ts
- src/datepicker/__tests__/datepicker-range-separate-inputs.scenario.js
- src/datepicker/datepicker.js
- src/datepicker/index.d.ts
- src/datepicker/types.js
Fixes #4633 
Added an onOpen (function) prop to the datepicker component. This callback will be called when the datepicker is opened. This is analogous to the existing onClose function already being called when the datepicker is closed.
> feat(datepicker): add onOpen prop; resolves #4633

- documentation-site/examples/snackbar/placement.tsx
- src/combobox/index.d.ts
- src/map-marker/index.d.ts
- src/snackbar/index.d.ts
Fix type definitions for snackbar, combobox and map marker
- combobox - fixed syntax errors for function arguments(had flow syntax)
- map-marker - replaced `ValueOf` with working construction
- snackbar - replaced not working imports from js file, updated documentation example
Patch: Bug Fix
> fix(types): fix typescript definition errors

- documentation-site/examples/select/label.js
Removes errant type `<ValueT>` from the JavaScript "[Select with Custom Labels](https://baseweb.design/components/select/#select-with-custom-labels)" documentation example that was preventing it from working on code sandbox.
Patch: Bug Fix
> fix(documentation:select) Removes `<ValueT>` from JavaScript example

- src/modal/index.d.ts
- src/modal/types.js
update returnFocus type to match with returnFocus type of FocusLock.
So that we don't have to do flow-ignore or ts-ignore.
Patch: Bug Fix
> fix(modal): update returnFocus type to match with returnFocus type of FocusLock

- documentation-site/pages/guides/tables.mdx
I looked in the documentation and found the word `ustilizes`. I think this is a typo and meant to be `utilizes` instead of `ustilizes`.
> docs(guides/tables):Fixed the spelling of utilizes

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
Fix instance where import was renamed and an old typography component name was used within the component (H1 as StyledH1 and later H1 is a valid local variable that should not be renamed). See test for minimally reproduced test case
> fix(eslint): add jsx check if import was renamed

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
Adds early return on `import * as Typography from...` declarations, since we're now processing the entire ImportDeclaration.
> fix(eslint): add test and early return for ImportNamespaceSpecifiers

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
Nested tags weren't getting replaced, since the outer tag would manipulate the closing element, the child elements changed in a different fix function would be overridden. This separates the fix/report issue by processing each opening/closing tag separately.
> fix(eslint): treat opening/closing tags separately

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
Refactors the eslint logic to track imports form the ImportDeclaration rather than running both the Declaration and Specifier on each import.
> feat(eslint): consolidate import logic in ImportDeclaration for perf

- src/drawer/drawer.js
- src/modal/modal.js
- src/popover/popover.js
- src/table/filter.js
Fixes #4743
This change allows a focus-locked component (modal, drawer, popover, table filter) to lose focus only when the focus exits the frame. This will only occur if the component is within an `iframe`
See prop details here https://github.com/theKashey/react-focus-lock/commit/486a7e08428487286d09ef7bfeaa701e8376318d
Patch: Bug Fix
> fix(modal): modal will not lock focus within an iframe only

- documentation-site/components/yard/config/fixed-marker.ts
- documentation-site/examples/fixed-marker/badge-enhancer-text.js
- documentation-site/examples/fixed-marker/badge-enhancer-text.tsx
- src/map-marker/__tests__/eats-pickup-marker.scenario.js
- src/map-marker/__tests__/fixed-marker-map.scenario.js
- src/map-marker/__tests__/fixed-marker.scenario.js
- src/map-marker/badge-enhancer.js
- src/map-marker/drag-shadow.js
- src/map-marker/fixed-marker.js
- src/map-marker/index.d.ts
- src/map-marker/label-enhancer.js
- src/map-marker/needle.js
- src/map-marker/pin-head.js
- src/map-marker/styled-components.js
- src/map-marker/types.js
Remove `badgeEnhancerColor`, `badgeEnhancerBackground` and `labelEnhancerColor`, `labelEnhancerStrokeColor` properties, but still allow to configure them via overrides
Patch: Bug Fix
> Map marker label enhancer no color props

- documentation-site/components/yard/config/fixed-marker.ts
- documentation-site/components/yard/config/floating-marker.ts
- documentation-site/examples/fixed-marker/end-enhancer-color.js
- documentation-site/examples/fixed-marker/end-enhancer-color.tsx
- documentation-site/pages/blog/introducing-base-map-markers/index.mdx
- documentation-site/pages/components/fixed-marker.mdx
- documentation-site/pages/components/floating-marker.mdx
- src/map-marker/__tests__/eats-pickup-marker.scenario.js
- src/map-marker/constants.js
- src/map-marker/fixed-marker.js
- src/map-marker/floating-marker.js
- src/map-marker/index.d.ts
- src/map-marker/index.js
- src/map-marker/types.js
Add `kind`: (`default`, `accent`, `negative`) property to the fixed marker. The colors can still be changed using overrides.
Patch: Bug Fix
> chore(map-marker): add kind property to fixed marker

- src/map-marker/__tests__/tile-grid.js
The following piece had to be removed:
```
<Block
display="flex"
flexDirection="column"
height="150px"
key={index}
>
<Label3 color={contentSecondary}>{label}</Label3>
```
Patch: Bug Fix
> fix(map-marker): mistake during merging conflicts

- src/timezonepicker/__tests__/timezone-picker.test.js
- src/timezonepicker/timezone-picker.js
- src/timezonepicker/types.js
Fixes the onChange param type to align with previous versions, and Date.getTimezoneOffset(). Adds tests to verify any future changes.
> fix(timezone-picker): correct offset value to align with prev versions

- documentation-site/pages/components/modal.mdx
- src/modal/index.d.ts
- src/modal/modal.js
- src/modal/types.js
Removes `autofocus` prop, use the `autoFocus` prop instead.
> feat(modal): removes no-capitalization autofocus prop

- documentation-site/components/yard/config/toast.ts
- documentation-site/pages/components/toast.mdx
Fixes yard config, as all props were being added to the top level element. Adds a blurb about not nesting children inside for SSR.
> fix(docs): fix toast docs

- src/timezonepicker/timezone-picker.js
Some timezones, such as `(GMT-6) America/North Dakota/New_Salem` have multiple underscores (see attached image). Use a regex to replace all of them so the zone will show as `(GMT-6) America/North Dakota/New Salem`.
As an alternative to `replace` with regex `replaceAll` could be used, but browser support is better with `replace`.
Patch: Bug Fix
> fix(TimeZone picker) Proper replace all underscores

- documentation-site/pages/getting-started/setup.mdx
Setup for Base Web for Remix.js React Framework to configure with Styletron.
The setup uses Javascript but it is the same with the Typescript
Minor: Enhancement
> Guide to Styletron/Base Web Setup for Remix.js

- packages/eslint-plugin-baseui/README.md
- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/__tests__/no-block-style.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
- packages/eslint-plugin-baseui/src/index.js
- packages/eslint-plugin-baseui/src/no-block-style.js
Separates the Block style/$style rule into it's own rule, as it's not a deprecated component or api. Will give us more granular ability to enable errors on deprecated components being introduced, without having to refactor Block usage.
> feat(eslint): separate block rule from deprecated component api

- documentation-site/components/yard/config/radio.ts
- documentation-site/examples/radio/overrides.js
- src/radio/radiogroup.js
- src/radio/types.js
Previously, `RadioGroup` accepted overrides for `Radio` which it passed through to `Radio`. This change deprecates that behavior. Users should instead apply `Radio` overrides directly to instances of the `Radio` component itself.
> chore(radio): remove radio group overrides pass through

- packages/eslint-plugin-baseui/src/deprecated-component-api.js
- packages/eslint-plugin-baseui/src/messages.js
- src/select/index.d.ts
- src/select/index.js
- src/select/select-component.js
The `SearchIcon` override for `Select` is deprecated in favor of `SearchIconContainer`.
> Remove select searchicon override

- package.json
- yarn.lock
Uses `vite@2.9.0-beta0` that has some new critical fixes like the new pre-bundling algorithm and ability to resolve imports of `.js` as `.tsx` (important for ESM).
> chore: bump vite and ladle

- documentation-site/examples/select/overridden.tsx
Fixes a typo in docs. TS implementation doesn't need the `// @flow` comment.
Documentation
> Remove unnecessary `// @flow` from TS implementation

- src/input/index.d.ts
- src/input/types.js
Allow for 'any' value for input step. See spec:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-step
> fix(input): allow for 'any' value for input step

- packages/eslint-plugin-baseui/README.md
- packages/eslint-plugin-baseui/__tests__/no-shorthand-properties.test.js
- packages/eslint-plugin-baseui/src/index.js
- packages/eslint-plugin-baseui/src/messages.js
- packages/eslint-plugin-baseui/src/no-shorthand-properties.js
Related: #3845 
Adds a lint rule to check if override properties are using shorthand CSS, which is discouraged in BaseUI. This doesn't catch instances where a variable is passed into overrides, or any other instance where the properties are not inline. Those should be caught via flow/TS, but I'm not sure if flow allows for a type specific enough to disallow the behavior (any `key: string` except border/padding/etc).
> feat(eslint): add no shorthand properties rule

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
`Checkbox`, `Radio`, and `RadioGroup` components have had development time logs for a couple versions now saying that `isError` will be deprecated in favor of `error`. This PR add lint rules to auto-fix this
> feat(eslint-plugin): add rules to fix isError to error

- src/radio/index.d.ts
- src/radio/radio.js
- src/radio/radiogroup.js
- src/radio/styled-components.js
- src/radio/types.js
Removes `isError` from `Radio` and `RadioGroup` components. Lint plugin changes here https://github.com/uber/baseweb/pull/4882
> chore(v11): remove isError from radio/radiogroup

- src/form-control/index.d.ts
Related to #4818
The props passed to child of FormControl seems to have the shape mentioned in https://github.com/uber/baseweb/issues/4818#issuecomment-1093925352
This PR adds the type definition.
> feat: add type of props passed to FormControl child

- src/form-control/styled-components.js
The Label component found in the FormControl component uses font250 which has a default font-weight of 500. 
When creating a theme with an overrides object it is possible to change the font weight of font250. 
This will affect, for example: Button with SIZE.compact, SortableLabel in Table component, etc.
This should also affect the aforementioned Label, but it doesn't because the fontWeight is always set to 500 (which is already the default because of using font250).
Patch: Bug Fix
> fix(form-control.label): label component in form-control overrides theme font-weight

- src/datepicker/types.js
Resolves a small issue I introduced in https://github.com/uber/baseweb/pull/4932 where I made the date param covariant in onChange `onChange: ({ +date: ?T | Array<T> }) => mixed` but this causes problems for existing applications that have explicitly typed their callback fn. This was a test I had made that I neglected to revert before making the previous pr.
```jsx
function MyComponent() {
// state management...
// flow incompatible-variance error below
function handleChange({ date: ?Date | Array<Date> }) {}
return <Datepicker onChange={handleChange} />
}
```
Patch: Bug Fix
> fix(datepicker): remove date callback param covariance

- src/select/__tests__/select-controlref.test.js
- src/select/select-component.js
Fixes [#4936](https://github.com/uber/baseweb/issues/4936)
When we handle a blur event in the select-component, we want to check if
the event is transferring focus to an element which is a child of the
select component before we un-focus.
Because handle blur takes FocusEvents or MouseEvents, there is a hole in
the logic, where a FocusEvent which does not have a relatedTarget (which
is what happens if you imperatively blur with element.blur() or via the
controlRef.setInputBlur() ) will pass to the second conditional check in
handleBlur, which should only be applied to mouse events (i.e. If you
click on a new element, we check if that new element (event.target) is
inside our anchor).
In the case of a FocusEvent, event.target is the element being blurred
(the input) so it will always be …
> fix(select): handleBlur should check event type before bound check

- packages/eslint-plugin-baseui/__tests__/deprecated-component-api.test.js
- packages/eslint-plugin-baseui/src/deprecated-component-api.js
- packages/eslint-plugin-baseui/src/messages.js
Fixes #4908
In v11, `Spinner` was deprecated and `StyledSpinnerNext` was renamed to `Spinner`. Remove the warning as it no longer applies.
Patch: Remove deprecation warning
> chore(spinner): remove styledspinnernext deprecation warning

- documentation-site/components/yard/config/file-uploader.ts
Fixes small typo in docs: `even` -> `event`
> fix(docs): fix typo

- src/badge/utils.js
Badges may have 0 or 1 children. This prevents the erroneous error when calling `Badge` with 0 children (inline badge).
Patch: Bug Fix
> fix(badge): avoid warning for inline badges

- src/accordion/stateless-accordion.tsx
- src/accordion/types.ts
Current type does not allow to pass children like this:
```jsx
<Accordion>
{[
<Panel key="1">1</Panel>,
<Panel key="2">2</Panel>
]}
<Panel key="3">3</Panel>
</Accordion>
```
Making the type less strict (ReactNode instead of only ReactElement), also adding support for primitive values
> fix(types): accordion, relax children type

- src/checkbox/types.ts
- src/themes/index.ts
- src/tree-view/index.ts
- update deprecated alias (issues found testing on typescript project migrating to new types)
- mark default properties in `CheckboxProps` (while in most cases it works as expected because of `defaultProps` static field, it does cause issues with some more advanced use-cases like when inferring props in HOC)
> fix(types): update type aliases, mark optional props for checkbox

- documentation-site/next.config.js
- package.json
- yarn.lock
Microsoft ended support for IE [last month](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge#what-is-the-lifecycle-policy-for-internet-explorer-). Our docs site build spends about ~40% of time transpiling for IE so removing should help speed things up
> chore(docs): remove ie support from docs site - improve build time

- documentation-site/components/yard/config/badge.ts
Badge does not use shared props for its styled components, but the docs
currently imply that it does.
Patch: Bug Fix
> chore(docs): fix Badge shared props

- src/locale/__tests__/unit.test.tsx
- src/locale/index.tsx
Locale provider loses all other values when you override the values in a nested fashion. Instead this creates a new pattern of inheritance where the parent values are inherited into the child. There are some risks that this will introduce copy difference in places where the default values were used. However, this may also improve copy where there were two locale  providers: one parent proving all translations, and a child overriding a selection of values. Now the translations should not be lost. 
Here isa sample of the functionality: https://codesandbox.io/s/green-grass-1pxsz0?file=/src/App.js
> feat(locale): add locale inheritence to provider

- .buildkite/pipeline.yml
- package.json
- yarn.lock
Seeing unit test errors in our react 18 ci job. Updating @testing-library/dom seems to fix the issue and pinning @testing-library/react to a specific version now that a react 18 compatible version has been published to their stable channel
> fix(test): update @testing-library/dom

- src/side-navigation/types.ts
These should be optional, regression from v11.
Patch: Bug Fix
> fix: make optional side-navigation props optional again

- src/progress-bar/styled-components.tsx
Not all members of ```StyleProps``` is required. Regression from v11. 
Patch: Bug Fix
> fix: styled-bar should only require props it uses

- src/input/base-input.tsx
I'm not quite sure why textarea children prop was applied, but it seems to be breaking SSR in react 18. This commit removes it and relies on textarea value prop
Patch: Bug Fix
> fix(textarea): do not apply children

- documentation-site/pages/guides/theming.mdx
recieve -> receive
Patch: Bug Fix
> docs(theming): fix typo

- src/popover/popover.tsx
import * as React from "react";
import { StatefulPopover } from "baseui/popover";
export default () => {
return (
<StatefulPopover
content={() => (
<div>popover content</div>
)}
returnFocus
autoFocus
>
<span><span>Click me</span></span>
</StatefulPopover>
);
}
If you continuously click on “Click me”, the popover content will just flicker.
Patch: Bug Fix
> fix(popover): handle click within anchor children

- src/themes/dark-theme/color-component-tokens.js.flow
- src/themes/dark-theme/color-component-tokens.ts
`Update the buttonPrimaryFill color token dark mode mapping to match design spec` 
Currently all Primary buttons have a component specific color token that maps them to white in a dark mode theme. This change replaces the mapping to the correct color token to match the design spec (`primaryA`)
Note: Long term, we should remap all component color tokens to map to semantic ones (`backgroundInversePrimary`) over the primitives.
Before: 
After:
Bugfix
> Update button background in dark mode to match design spec

- src/skeleton/skeleton.js.flow
- src/skeleton/types.js.flow
- src/skeleton/types.ts
According to the [docs](https://baseweb.design/components/skeleton/) `SkeletonProps.rows` is optional, however it's not so according to the [typings](https://github.com/uber/baseweb/blob/master/src/skeleton/types.ts#L14). This PR makes `SkeletonProps.rows` optional.
Patch: Bug Fix
> fix(types): make SkeletonProps.rows optional to match the docs

- src/header-navigation/types.js.flow
- src/header-navigation/types.ts
`HeaderNavigation.children` is currently missing when paired with `@types/react@18`. This PR fixes addresses that.
Patch: Bug Fix
> fix(types): use React.PropsWithChildren with HeaderNavigationProps

- src/popover/popover.js.flow
- src/popover/types.js.flow
- src/popover/types.ts
Makes the following fields optional to match the [docs](https://baseweb.design/components/popover/):
* `StatefulPopoverProps.triggerType`
* `StatefulPopoverProps.dismissOnClickOutside`
* `StatefulPopoverProps.placement`
* `StatefulPopoverProps.dismissOnEsc` 
Patch: Bug Fix
> fix(types): fix StatefulPopoverProps to match docs

- src/card/types.js.flow
- src/card/types.ts
Makes `CardProps.hasThumbnail` optional as per [docs](https://baseweb.design/components/card/) and [implementation](https://github.com/uber/baseweb/blob/master/src/card/card.tsx#L97) 
Patch: Bug Fix
> fix(types): fix CardProps to match docs

- src/tree-view/tree-label-interactable.js.flow
- src/tree-view/tree-label-interactable.tsx
`TreeLabelInteractable.children` is currently missing when paired with `@types/react@18`. This PR fixes addresses that.
Patch: Bug Fix
> fix(types): fix TreeLabelInteractable to allow children

- src/header-navigation/types.js.flow
- src/header-navigation/types.ts
`HeaderNavigation.children` is currently missing when paired with `@types/react@18`. This PR fixes addresses that.
Patch: Bug Fix
> fix(types): fix HeaderNavigation to allow children

- src/themes/types.ts
A number of optional theme properties is currently not defined correctly in TypeScript and don't match [flow types](https://github.com/uber/baseweb/blob/master/src/themes/types.js.flow#L119-L130). Furthermore, they cause a very annoying issue of not being compatible with `styletron` and `csstype` because of `null`.
It's possible to workaround this with `?? undefined`, however making this change across large code base is not ideal (and shouldn't be necessary IMO)
Patch: Bug Fix
> fix(types): fix definition of optional TS theme properties

- documentation-site/components/yard/knob.tsx
Update react docs link to the new documentation space as the old one is being deprecated now.
Update react docs link to the new documentation space as the old one is being deprecated now.
Patch: Bug Fix
> Update react docs link to new documentation space

- documentation-site/components/yard/config/tile.ts
- documentation-site/examples/tile/action.tsx
- documentation-site/examples/tile/alignment.tsx
- removing setting color for leadingContent and trailingContent for Tile examples
https://github.com/uber/baseweb/assets/48413510/30e0d8e7-32c5-40f5-ac55-fde816068d34
Patch: Bug Fix
> fix: removing color prop from leadingContent and trailingContent

- documentation-site/components/version-selector.jsx
- documentation-site/examples/button-group/dropdown.tsx
- documentation-site/examples/button-group/enhancer.tsx
- documentation-site/examples/button/dropdown.tsx
- documentation-site/examples/button/with-enhancers.tsx
- documentation-site/examples/fixed-marker/dragging.tsx
- documentation-site/examples/fixed-marker/end-enhancer-color.tsx
- documentation-site/examples/fixed-marker/start-enhancer.tsx
- documentation-site/examples/floating-marker/large-square-anchor-start-enhancer.tsx
- documentation-site/examples/floating-marker/start-enhancer.tsx
- documentation-site/examples/floating-route-marker/start-end-enhancer.tsx
- documentation-site/examples/icon/button.tsx
- documentation-site/examples/input/enhancers.tsx
- documentation-site/examples/list/enhancers.tsx
- documentation-site/examples/list/menu-adapter.tsx
- documentation-site/examples/list/sublist.tsx
- documentation-site/examples/list/tap-target.tsx
- documentation-site/examples/snackbar/action-button-usage.tsx
- documentation-site/examples/table/pagination.tsx
add title="" to icons to prevent the wrong name being read on screen readers
E.g.
> fix(icons): add title="" to icons

- documentation-site/examples/input/with-tags.tsx
- documentation-site/examples/table-grid/nested.tsx
- documentation-site/pages/blog/base-web-v7/index.mdx
- documentation-site/pages/blog/nested-overrides-playground/live-editor-tag.jsx
- documentation-site/pages/components/tag.mdx
- src/table-grid/__tests__/table-grid-jobs.scenario.tsx
Recently, `Tag`'s `variant` prop was replaced with `hierarchy`. This change wasn't reflected across the entire doc site.
> fix tag hierarchy issues

- documentation-site/examples/file-uploader-beta/label-hint.tsx
- documentation-site/pages/components/file-uploader-beta.mdx
- Add label hint example
- Remove `processFileOnDrop` from item preview example for brevity
> File uploader beta label hint example
